Commonjava/indy

deployments/launchers/base/src/main/bin/init/aprox
It was killing every process that had "aprox" on command line, even
"mcedit aprox.sh" etc.
Now it stores PID of aprox.sh in /var/run/aprox.pid and when stopping
it run "pgrep -P <PID>" to get PID of descendant java process, which
gets killed.
Also running AProx as user aprox instead of root for better security.
=> Make init script safer when stopping or restarting the daemon

addons/autoprox/common/src/main/java/org/commonjava/aprox/autoprox/data/AutoProxConstants.java, addons/dot-maven/common/src/main/data/templates/settings.xml.groovy, addons/folo/common/src/main/java/org/commonjava/aprox/folo/change/FoloTrackingListener.java, addons/folo/common/src/main/java/org/commonjava/aprox/folo/ctl/FoloConstants.java, addons/httprox/common/src/main/java/org/commonjava/aprox/httprox/HttpProxy.java, addons/httprox/common/src/main/java/org/commonjava/aprox/httprox/conf/HttproxConfig.java, addons/httprox/common/src/main/java/org/commonjava/aprox/httprox/conf/TrackingType.java, addons/httprox/common/src/main/java/org/commonjava/aprox/httprox/handler/ProxyRequestReader.java, addons/httprox/common/src/main/java/org/commonjava/aprox/httprox/handler/ProxyResponseWriter.java, addons/httprox/common/src/main/java/org/commonjava/aprox/httprox/util/HttpProxyConstants.java, addons/httprox/common/src/main/java/org/commonjava/aprox/httprox/util/UserPass.java, addons/httprox/common/src/test/java/org/commonjava/aprox/httprox/HttpProxyTest.java, addons/httprox/ftests/src/main/java/org/commonjava/aprox/httprox/AutoCreateRepoAndRetrievePomTest.java, addons/httprox/ftests/src/main/java/org/commonjava/aprox/httprox/Propagate404NotFoundTest.java, addons/httprox/ftests/src/main/java/org/commonjava/aprox/httprox/Propagate500As502ErrorTest.java, addons/httprox/ftests/src/main/java/org/commonjava/aprox/httprox/RetrievedPomInTrackingReportTest.java, addons/implied-repos/common/src/main/conf/conf.d/implied-repos.conf, addons/implied-repos/common/src/main/java/org/commonjava/aprox/implrepo/change/ImpliedRepositoryDetector.java, addons/implied-repos/common/src/main/java/org/commonjava/aprox/implrepo/conf/ImpliedRepoConfig.java, addons/implied-repos/common/src/main/resources/default-implied-repos.conf, addons/indexer/src/main/java/org/commonjava/aprox/indexer/conf/IndexerConfig.java, addons/setback/common/src/main/data/templates/application_xml/setback-settings.xml.groovy, api/src/main/java/org/commonjava/aprox/conf/AbstractAproxFeatureConfig.java, api/src/main/java/org/commonjava/aprox/util/MimeTyper.java, core/src/main/java/org/commonjava/aprox/core/content/HttpMetadataCleanupGenerator.java, models/core-java/src/main/java/org/commonjava/aprox/model/core/io/StoreKeyDeserializer.java, models/core-java/src/main/java/org/commonjava/aprox/model/core/io/StoreKeySerializer.java, test/fixtures-core/src/main/java/org/commonjava/aprox/test/fixture/core/TestHttpServer.java, uis/layover/pom.xml
* settings templates had javadoc-style license header, which broke the generated output
* implied-repos now has the ability to blacklist detected repos like codehaus.org.
=> fix settings templates, implement blacklisting in implied-repos

addons/depgraph/common/src/main/java/org/commonjava/aprox/depgraph/rest/RenderingController.java, addons/depgraph/common/src/test/java/org/commonjava/aprox/depgraph/dto/PomRecipeTest.java
This just adds null value in the GraphDescription constructor to use the default mutator.
Follows https://github.com/Commonjava/cartographer/pull/87
=> Align with mutator config changes in GraphDescription

core/src/main/java/org/commonjava/aprox/core/expire/ScheduleManager.java
I guess this situation can occur when there is stored a firetime before
current datetime. In this case getFireTimeAfter will return null.
Therefore null should be handled the same way as if nextFire is before
or equals to "to" value.
=> Fix NPE when nextFire is null

addons/folo/common/src/main/java/org/commonjava/indy/folo/change/FoloPomDownloadListener.java, pom.xml
This fixes an issue where something like org.scala-lang:scala-library:2.10.0 as the root of the graph was coming up missing because it only has the terminal-parent relationship in the runtime scope, and the terminal-parent relationship wasn't being added to the graph db...leaving the graph db with the impression scala-library was missing.
=> update to cartographer snapshot

core/src/main/java/org/commonjava/indy/core/content/MavenMetadataGenerator.java
The issue was caused by manual pom upload in a wrong path, specifically
twitter4j-core-4.0.4.redhat-2.pom into version 4.0.4.redhat-2 but in
artifactId twitter4j. The ArtifactPathInfo cannot be parsed from the
path, but the version was still included.
The fix prevents a version inclusion if there is not the correct pom present.
=> Fix #277: NPE in MavenMetadataGenerator

addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexedStorePath.java, addons/folo/model-java/pom.xml, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/common/src/test/java/org/commonjava/indy/promote/data/PromotionManagerTest.java, addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/PathsPromoteResult.java, addons/promote/model-java/src/test/java/org/commonjava/indy/promote/model/PathsPromoteResultTest.java, models/core-java/pom.xml, pom.xml
* race condition in by-path promotion (now synchronizing on target key to force competing promotions to wait on the running promotion)
* classpath of client includes jboss-logging and swagger, which can cause deployment issues in JBoss containers (jboss-logging mostly)
* overwriting a file with smaller content than the existing version didn't truncate the resulting file to the bounds of the new content.
=> fix two bugs, plus one potential bug

ftests/core/pom.xml, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/ContentTimeoutWorkingTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/ProxyRemoteContentTest.java
RCMPROJ-6007: Test Quartz-based timeout of cached remote content
RCMPROJ-6008: Test CacheProvider-based timeout of cached remote content
As 6007 and 6008 is very similar with only differences in validation, I merged these two into one file ContentTimoutWorkingTest.
But I've tested and found that for RCMPROJ-6008 it is not working as well, which means the file still exists when timeout, and the lastModified did not change too. 
Per above and mentioned, I've marked the test as @Ignore.
This PR is refactor to https://github.com/Commonjava/indy/pull/284 which splits two tests to different methods.
=> RCMPROJ-5893: Test that content timeout works in Indy

ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java, ftests/common/src/main/resources/default-test-main.conf, ftests/common/src/main/resources/default-test-scheduler.conf, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/ContentPassthroughTimeoutWorkingTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/ContentTimeoutWorkingTest.java
There were a few problems with the content timeout tests (actually the abstract base ftest class):
* Overwriting main.conf (to set passthrough.timeout, for example) removed a lot of configuration that would have been in the default config file...now we have a default-test-main.conf to append to custom overrides like this.
* Overwriting scheduler.conf to enable wasn't enough; we needed a default-test-scheduler.conf that contained all the quartz properties...to make this speedier, I made the URL an in-memory db.
* The scheduler DB used to be so slow that I disabled it for functional testing...which was causing @ligangty 's tests to fail.
* I added an override-able method to the abstract base ftest to allow a ftest to say that it wanted the scheduler enabled or disabled. As of the last …
=> Content timeout testing fixes

ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/AbstractContentTimeoutWorkingTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/ContentPassthroughTimeoutWorkingTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/ContentTimeoutWorkingTest.java
Seems the ContentTimeoutWorkingTest and ContentPassthroughTimeoutWorkgingTest is totally same with little differences in RemoteRepository attribute, so I extract the same part to a super class to remove the duplicate code.
=> Refactor the two timeout working tests to remove duplicate code

addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexManager.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexObserver.java, api/src/main/java/org/commonjava/indy/change/event/ArtifactStoreEnablementEvent.java, api/src/main/java/org/commonjava/indy/content/DirectContentAccess.java, api/src/main/java/org/commonjava/indy/data/NoOpStoreEventDispatcher.java, api/src/main/java/org/commonjava/indy/data/StoreEventDispatcher.java, core/src/main/java/org/commonjava/indy/core/change/StoreEnablementManager.java, core/src/main/java/org/commonjava/indy/core/change/event/DefaultStoreEventDispatcher.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDirectContentAccess.java, core/src/main/java/org/commonjava/indy/core/ctl/SchedulerController.java, db/memory/src/main/java/org/commonjava/indy/mem/data/MemoryStoreDataManager.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/AbstractContentTimeoutWorkingTest.java, test/db/src/main/java/org/commonjava/indy/core/data/testutil/StoreEventDispatcherStub.java
Working on improving content-indexer responses to events in the system, and formalizing the enable/disable event set so we can listen to it.
This is still under some development, with ContentIndexObserver and StoreEnablementListener in need of some uncommenting / debugging. I believe the concepts are sound though (the ones I have commented in those classes).
@pkocandr I wanted to submit this as a PR anyway to show where I was planning to go with the work, and see if you think it looks like a sound approach. In particular, I was planning to make StoreEnablementManager respond to ArtifactStoreEnablementEvent instead of the ArtifactStoreUpdateEvent that it uses to set the disabled timeout...and even more importantly, the ContentIndexObserver, which has a bunch of commented out code. Those …
=> Working on improving content-index responses to events in Indy

core/src/main/java/org/commonjava/indy/core/expire/EventTypeMatcher.java, core/src/main/java/org/commonjava/indy/core/expire/IndyScheduleListener.java, core/src/main/java/org/commonjava/indy/core/expire/ScheduleManager.java
- remove trigger unscheduling, because even when a trigger is
unscheduled job is still present in the DB and when a new trigger got
scheduled it failed with ObjectAlreadyExistsException. It is better
to use scheduleJob method with replace=true. It performs all needed
cleanup if necessary, creates the job when missing and schedules the
new trigger set.
```
04:29:33.160 [indy-event-dispatch-0] ERROR o.c.i.c.expire.TimeoutEventListener - Failed to set proxy-cache timeouts related to: RepositoryLocation [remote:test-repo]:junit/junit/maven-metadata.xml
org.commonjava.indy.core.expire.IndySchedulerException: Failed to schedule content-expiration job.
at org.commonjava.indy.core.expire.ScheduleManager.scheduleForStore(ScheduleManager.java:351) ~[indy-embedder-savant-0.99.3-SNAPSHOT.jar:na]
at …
```
=> Fix scheduler timeouts

api/src/main/java/org/commonjava/indy/action/IndyLifecycleManager.java, deployments/launchers/savant/src/main/etc/indy/logging/logback.xml, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/inject/CacheProducer.java, subsys/infinispan/src/main/resources/infinispan.xml
also:
* Make CacheProducer implement ShutdownAction so it gets stopped in an orderly fashion during Indy shutdown
* Try to force infinispan cache to persist to disk for content indexing (doesn't do it yet).
=> reinstate INFO logging for CacheProducer, IndyLifecycleManager, plus minor tweaks

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/conf/HttproxConfig.java
...to provide the same default experience for both maven repositories
and general proxy.
This was requested as NCL-1901.
=> Change httprox.secured default value to false

addons/content-index/pom.xml, addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexManager.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexObserver.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexedStorePath.java, addons/content-index/src/test/java/org/commonjava/indy/content/index/DigestTest.java, addons/dot-maven/common/src/main/java/org/commonjava/indy/dotmaven/util/SettingsTemplate.java, addons/setback/common/src/main/java/org/commonjava/indy/setback/data/SetBackSettingsManager.java, api/src/main/java/org/commonjava/indy/data/StoreDataManager.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java, core/src/main/java/org/commonjava/indy/core/ctl/ContentController.java, core/src/main/java/org/commonjava/indy/core/ctl/StatsController.java, models/core-java/src/main/java/org/commonjava/indy/model/core/StoreKey.java, subsys/groovy/src/main/java/org/commonjava/indy/subsys/template/TemplatingEngine.java
hopefully this will shrink the memory requirement for content indexing.
=> use md5 digests for IndexStorePath fields to make it smaller

addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCache.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/conf/HttproxConfig.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyAcceptHandler.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyResponseWriter.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/util/HttpConduitWrapper.java, addons/httprox/common/src/test/java/org/commonjava/indy/httprox/HttpProxyTest.java, addons/httprox/ftests/pom.xml, addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/AbstractHttproxFunctionalTest.java, addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/AbstractHttproxTrackingFunctionalTest.java, addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/ProxyReleasesFileLockOnCompletionTest.java, addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/RetrievedPomInAlwaysOnTrackingReportTest.java, addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/RetrievedPomInSuffixTrackingReportTest.java, addons/httprox/ftests/src/main/resources/META-INF/beans.xml, addons/httprox/ftests/src/main/resources/logback.xml, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java, db/memory/src/main/java/org/commonjava/indy/mem/data/MemoryStoreDataManager.java, embedders/savant/pom.xml, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java, pom.xml, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/inject/CacheProducer.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/ResourceManagementFilter.java
HTTProx regression was caused by Transfer.touch() waiting for write lock.
This requires rebuild of galley and partyline snapshots.
=> Fixing test regression introduced by PR#306, and fixing httprox regression

api/src/main/java/org/commonjava/indy/content/DownloadManager.java, core/src/main/java/org/commonjava/indy/core/content/AbstractMergedContentGenerator.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java
I created an overloaded method allowing us to get the Transfer no matter if the store is disabled or not.
This issue affects only 0.99.1.x branch, because in master it is already refactored to use DirectContentAccess.
The error in the log was:
```
2016-05-31 11:28:22.166 [DELETE /group/public/com/sun/istack/istack-commons-runtime/maven-metadata.xml] DEBUG o.c.i.c.c.MavenMetadataGenerator - Deleting merged file: null
2016-05-31 11:28:22.166 [XNIO-2 task-42] ERROR io.undertow.request - UT005023: Exception handling request to /api/group/public/com/sun/istack/istack-commons-runtime/maven-metadata.xml
org.jboss.resteasy.spi.UnhandledException: java.lang.NullPointerException
at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:76) …
```
=> Fix NPE when someone attempts to delete content from a disabled group

addons/depgraph/jaxrs/src/main/java/org/commonjava/indy/depgraph/jaxrs/render/RepositoryResource.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/ResponseUtils.java
The error response was formated but not thrown, only returned and then not used anymore. Instead there was null returned which led to "204 No Content" response.
Also once fixed the error message was not separated from error ID by a new line.
=> Fix error response for urlmap and content

addons/depgraph/jaxrs/src/main/java/org/commonjava/indy/depgraph/jaxrs/render/RepositoryResource.java
In case a urlmap was created with usage of hosted repositories, the
resulting urls for some artifacts looked like
http://localhost:8080/api/depgraph/repo/urlmap/api/hosted/local-repo/...
instead of just
http://localhost:8080/api/hosted/local-repo/...
The same problem was found for downlog and content.
=> Fix building of local urls in urlmap

core/src/main/java/org/commonjava/indy/core/expire/TimeoutEventListener.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/ContentRescheduleTimeoutTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/MetadataRescheduleTimeoutTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/MixContentRescheduleTimeoutTest.java
I've split the .listing.txt metadata ftest to a single commit as it still has problem.
BTW, @jdcasey I've seen that you have concern about if the metadata will never be set timeout if we did this change to TimeoutEventListner, when I did the MetadataRescheduleTimoutTest, seems the metadata is successfully be deleted when timeout arrived. And I think the initial timeout is set in onFileStorageEvent but not onFileAccessEvent. What's your opinions about this?
=> Change rescheduling approach for metadata and .listing.txt files

api/src/main/java/org/commonjava/indy/content/ContentGenerator.java, core/src/main/java/org/commonjava/indy/core/content/ArchetypeCatalogGenerator.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, core/src/main/java/org/commonjava/indy/core/content/HttpMetadataCleanupGenerator.java, core/src/main/java/org/commonjava/indy/core/content/MavenMetadataGenerator.java
There is a strange repository at http://deadlock.netbeans.org/maven2/
which sometimes for non-existing content returns status 200 with 404
error page. It happens for some maven-metadata.xml files. So when Indy
tries to create the merged content, it parses the 404 page, but it is
not a valid XML so it results in parse error and the generator returns
null, because no other store in the group provides the requested path.
In the end no other generator produces the requested resource so it
tries to cycle through the stores in the group if one of them provides
content with matching path and there it hits the error page and returns
it as regular content.
I think the best solution is to strictly say "if a path is handled by
a content generator, nothing else will be tried to provide the content". …
=> Fix 404 page with status 200

addons/autoprox/common/src/main/java/org/commonjava/indy/autoprox/data/AutoProxDataManagerDecorator.java
when requesting a non-existing group containing a non existing store
like "group:central+bla" when no store bla is available.
Backport of #354 into 0.99.1.x.
=> Fix ConcurrentModificationException

addons/folo/common/src/main/java/org/commonjava/indy/folo/change/FoloTrackingListener.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/ctl/FoloAdminController.java, addons/folo/common/src/test/java/org/commonjava/indy/folo/data/FoloRecordCacheTest.java, addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloContentAccessResource.java, addons/folo/model-java/src/main/java/org/commonjava/indy/folo/dto/TrackedContentEntryDTO.java, addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/TrackedContentEntry.java, addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/TrackingKey.java, addons/folo/model-java/src/test/java/org/commonjava/indy/folo/dto/TrackedContentDTOTest.java, addons/folo/model-java/src/test/java/org/commonjava/indy/folo/dto/TrackedContentEntryDTOTest.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyResponseWriter.java, models/core-java/src/main/java/org/commonjava/indy/model/core/AccessChannel.java
This is adding access channel into folo tracking report. There are currently 2 access channels - Maven repo and generic proxy. This is stored directly into the tracking report with the request, because a generic proxy repo created by httprox can also be accessed via regular Maven repo access path, so we want to distinguish between the access channels, not between addons that created the repo, although this will be probably interesting for other usages.
I'm just not sure, if "access channel" is the best name. Another option was "entry point". Or maybe there is some other even better.
=> Access channel

addons/folo/common/src/main/java/org/commonjava/indy/folo/change/FoloTrackingListener.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/ctl/FoloAdminController.java, addons/folo/common/src/test/java/org/commonjava/indy/folo/data/FoloRecordCacheTest.java, addons/folo/model-java/src/main/java/org/commonjava/indy/folo/dto/TrackedContentEntryDTO.java, addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/TrackedContentEntry.java, addons/folo/model-java/src/test/java/org/commonjava/indy/folo/dto/TrackedContentEntryDTOTest.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidationTools.java, api/src/main/java/org/commonjava/indy/content/ArtifactData.java, api/src/main/java/org/commonjava/indy/content/ContentManager.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java
Added `size` to `TrackedContentEntry` and `TrackedContentEntryDTO`.
In order not to download the artifact twice, the size is calculated together with hashes of the artifact.
The `ContentManager#digest` method has been changed to return newly created `ArtifactData`, that contains hashes and size.
=> NCL-2266: artifact size exposed in TrackedContentEntryDTO

addons/koji/common/src/main/data/scripts/stores/koji-repo-creator.groovy
There is no build class property nor a method parameter or local
variable with such name, but nvr is passed as a method param. The
exception was:
```
2016-09-07 10:26:17.720 [HEAD /group/builds-untested/org/jbpm/jbpm-case-mgmt/6.4.0.Final-redhat-3/jbpm-case-mgmt-6.4.0.Final-redhat-3.pom (1473258369888.4687940368073419)] ERROR o.c.i.c.b.jaxrs.ContentAccessHandler - Failed to download artifact: org/jbpm/jbpm-case-mgmt/6.4.0.Final-redhat-3/jbpm-case-mgmt-6.4.0.Final-redhat-3.pom from: builds-untested. Reason: Cannot retrieve builds for: org.jbpm:jbpm-case-mgmt:pom:6.4.0.Final-redhat-3. Error: Koji withSession lambda command failed: No such property: build for class: org.commonjava.indy.koji.RepoCreator
org.commonjava.indy.IndyWorkflowException: Cannot retrieve builds for: …
```
=> Fix MissingPropertyException in brew pull

addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexedStorePath.java
The error this fixes was:
```
org.infinispan.commons.CacheException: Unable to invoke method public void org.infinispan.persistence.manager.PersistenceManagerImpl.start() on object of type PersistenceManagerImpl
at org.infinispan.commons.util.ReflectionUtil.invokeAccessibly(ReflectionUtil.java:172)
at org.infinispan.factories.AbstractComponentRegistry$PrioritizedMethod.invoke(AbstractComponentRegistry.java:859)
at org.infinispan.factories.AbstractComponentRegistry.invokeStartMethods(AbstractComponentRegistry.java:628)
at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:617)
at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:542)
at org.infinispan.factories.ComponentRegistry.start(ComponentRegistry.java:2 …
```
=> Fix NCL-2108 - NPM download is not always successful via Indy proxy

addons/implied-repos/common/src/main/java/org/commonjava/indy/implrepo/change/ImpliedRepositoryDetector.java
FIX: NOS-549, [github] Implied repos should not be processed from a profile, update the call method from indy
=> FIX: NOS-549, [github] Implied repos should not be processed from a profile, update the call method from indy

addons/promote/common/src/main/java/org/commonjava/indy/promote/conf/PromoteConfig.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/common/src/test/java/org/commonjava/indy/promote/data/PromotionManagerTest.java, db/memory/src/main/java/org/commonjava/indy/mem/data/MemoryStoreDataManager.java
* Use ReentrantLock associated with target StoreKey for by-path promotion, instead of synchronizing on StoreKey instance
* Use MemoryDataStore as synchronization object for all manipulation of group-member reverse mapping (was inconsistent before)
* Use timeout (default 30s, configurable) for attempting to lock promotion target
* turn off revisions add-on by default
=> turn off revisions, improve locking/sync for promote and groupsContaining

addons/promote/common/src/main/java/org/commonjava/indy/promote/conf/PromoteConfig.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/common/src/test/java/org/commonjava/indy/promote/data/PromotionManagerTest.java, db/memory/src/main/java/org/commonjava/indy/mem/data/MemoryStoreDataManager.java
* ReentrantLock is mapped to target StoreKey to lock the target and allow only one promotion on that target at a time
* MemoryStoreDataManager synchronization was using StoreKey in one case and `this` in other cases when dealing with group-member reverse mapping. Fixed to always synchronize on MemoryStoreDataManager instance in order to keep monitor effects localized
=> use ReentrantLock for by-path promotions and fix sync in getGroupsContaining

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/GroupPromoteThenHostedRepoTimeoutTest.java, core/src/main/java/org/commonjava/indy/core/expire/ScheduleManager.java, core/src/main/java/org/commonjava/indy/core/expire/TimeoutEventListener.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/HostedRepositoryNullTimeoutTest.java, models/core-java/src/main/java/org/commonjava/indy/model/core/HostedRepository.java
@jdcasey
this PR, add some null timeout deal logic and hosted timeout nullify in group promotion manager, also add the ftest (GroupPromoteThenHostedRepoTimeoutTest) for this, also add another extra ftest in indy-ftest-core for null timeout check (HostedRepositoryNullTimeoutTest), pls check, all the ftests run passed in my local's integration test.
=> FIX: NOS-602, By-Group Promotion should cancel hosted repository expiration

addons/implied-repos/common/src/main/java/org/commonjava/indy/implrepo/data/ValidRemoteStoreDataManagerDecorator.java, addons/implied-repos/common/src/test/java/org/commonjava/indy/implrepo/data/ValidRemoteStoreDataManagerTest.java, addons/implied-repos/common/src/test/java/org/commonjava/indy/implrepo/fixture/TestValidRemoteStoreDataManager.java, embedders/savant/src/main/resources/META-INF/beans.xml, ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/RemoteRepoInValidUrlTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/RemoteRepoValidUrlTest.java
@jdcasey
The commit has resolved the validation function, two ftest and one unit test included, TestValidRemoteStoreDataManager is provided for the unit test (ValidRemoteStoreDataManagerTest), all the tests are passed in my local.
=> FIX: NOS-682, adding url validation for RemoteRepository in #359

addons/promote/common/src/main/data/promote/rules/project-artifacts.groovy
Promotion validation failed in project-artifacts.groovy, line 21.
It seems the leftShift (<<) operator does not work well with empty string in groovy 2.2.1.
The error was:
```
groovy.lang.MissingMethodException: No signature of method: [Ljava.lang.String;.leftShift() is applicable for argument types: (java.lang.String) values: []
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55) ~[groovy-all-2.2.1.jar:2.2.1]
at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46) ~[groovy-all-2.2.1.jar:2.2.1]
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) ~[groovy-all-2.2.1.jar:2.2.1]
at org.commonjava.indy.promote.rules.ProjectArtifacts$_validate_closure1.doCall(script1479867641229204414979 …
```
=> Fix groovy.lang.MissingMethodException in template rule script

pom.xml
It is true Indy does not depend on atlas db drivers. I can run mvn clean install successfully without them. I remove them from pom.xml.
=> Remove unused atlas-driver dependency

core/src/main/java/org/commonjava/indy/core/expire/LegacyQuartzDBMigrationAction.java
lack of this constructor may break CDI bean constructor injection.
=> add no param construtor for LegacyQuartzDBMigrationAction

addons/promote/common/src/main/data/promote/rules/no-pre-existing-paths.groovy, addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidationTools.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/rule/FullRuleStack_GroupWithOneOfTwoHosts_RuleTest.java
When the no-pre-existing-path.groovy was performed for a remote repo,
e.g. check if a GAV is not already present in Maven Central, it
successfully found the artifact only if it was cached. For artifacts
not in cache it acted like it was not present, because tools.getTransfer
does not retrieve an artifact from a remote repo and returns a not-null
value only for artifacts present in local storage.
One option was to use exists, which is what I chose, but bear in mind
that this way we are loosing the info about source repo, e.g. instead of
"... is already available in: remote:central" we get "... is already
available in: group:public". To preserve the info about the source repo
we would need to use retrieve, which returns Transfer containing the
necessary info, but retrieving the artifacts …
=> Fix promotion validation - pre-existence of paths for remote repos

addons/promote/common/src/main/data/promote/rules/no-pre-existing-paths.groovy, addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidationTools.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/rule/FullRuleStack_GroupWithOneOfTwoHosts_RuleTest.java
When the no-pre-existing-path.groovy was performed for a remote repo,
e.g. check if a GAV is not already present in Maven Central, it
successfully found the artifact only if it was cached. For artifacts
not in cache it acted like it was not present, because tools.getTransfer
does not retrieve an artifact from a remote repo and returns a not-null
value only for artifacts present in local storage.
One option was to use exists, which is what I chose, but bear in mind
that this way we are loosing the info about source repo, e.g. instead of
"... is already available in: remote:central" we get "... is already
available in: group:public". To preserve the info about the source repo
we would need to use retrieve, which returns Transfer containing the
necessary info, but retrieving the artifacts …
=> Fix promotion validation - pre-existence of artifacts for remote repos

core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/NestedStoreInGroupWithErrorTest.java
Currently some implied remote repo references some meaningless remote repo, which will throw back http 40X error, and block the pnc build by 500 error. This is not good as these repos are not used actually by the build itself. So we need to bypass these errors to let the build go on.
=> NCL-2736 fix the build block by remote 401 problem

ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/MixContentRescheduleTimeoutTest.java, pom.xml, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/IndyDeployment.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/ResourceManagementFilter.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/UnhandledIOExceptionHandler.java
Add unhandled IOException handler to ensure they get logged.
=> Fix resource tracking and cleanup using new Weft ThreadContext

subsys/groovy/src/test/java/org/commonjava/indy/subsys/template/fixture/MockDownloadManager.java, subsys/groovy/src/test/resources/META-INF/beans.xml
Seems the new ContentDigest lost the DownloadManager dependency for
injection in groovy subsystem module, which caused the ScriptEngineTest
failed.
=> Adds MockDownloadManager for groovy subysystem module to pass unit-test

addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidationTools.java
The problem to solve here that we want to promote a build repo into builds-untested while checking for pre-existence in group:redhat-builds containing mrrc and builds-untested. Reason for using this approach is to avoid triggering BB pull for builds-untested alone, so we used different group name not matching the BB pull tag pattern.
=> [promote] Allow getting validation stores without the target one

bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/ResponseUtils.java
Without it user in a browser can't tell what the response was and even
if any response was received at all or the browser just gave up, because
previous page is still shown, at least in Firefox.
This also adds a newline character after error ID in error message which
was missing before.
=> Fix #361: Add some content along with 404 status

bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/ResponseUtils.java
Without it user in a browser can't tell what the response was and even
if any response was received at all or the browser just gave up, because
previous page is still shown, at least in Firefox.
This also adds a newline character after error ID in error message which
was missing before.
=> Fix #361: Add some content along with 404 (backport to 1.1.x)

.gitignore, addons/promote/ftests/pom.xml, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/CacheCheckingforPromoteWithRemoteTest.java
@jdcasey, I've a discussion with @pkocandr for NCL-2766 last Thur, and @pkocandr gave one suspect on the issue of the outdated cache. So I've created this ftest to prove if it is a problem, but seems this ftest does fail, which means problem not popped up. One possible cause maybe that the content checking is through the client but not directly the content index cache layer. I did not find a good way here to check the content index layer now, and need further check.
=> A promote ftest to prove promote cache content from remote to host in a group

addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexManager.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexObserver.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/RecursiveGroupMetadataFoundAfterMemberAddTest.java, addons/pkg-maven/ftests/src/main/resources/logback-test.xml, addons/promote/ftests/pom.xml, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/AbstractPromotionManagerTest.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/RecursiveGroupMetadataFoundAfterMemberPromotedTest.java, clients/core-java/src/main/java/org/commonjava/indy/client/core/helper/HttpResources.java, clients/core-java/src/main/java/org/commonjava/indy/client/core/module/IndyContentClientModule.java, ftests/common/src/main/java/org/commonjava/indy/ftest/core/fixture/ThreadDumper.java
The problem seems to be somewhere in a multilayer group configuration. The requested maven-metadata.xml doesn't exist at first
but should become available when a hosted repo containing it is promoted (by-group) into the lowest layer of the multilayer group config.
This does not seem to make the metadata file available via the topmost group in the PNC environment.
I cannot reproduce this scenario so far.
=> NFC not cleared when metadata file added to multilayer group structure via leaf repository upload.

addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexCacheProducer.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexManager.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexObserver.java, addons/diagnostics/ftests/src/main/java/org/commonjava/indy/diags/ftest/DownloadDiagBundleTest.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloCacheProducer.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/ArchetypeCatalogGenerator.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, addons/pkg-maven/common/src/test/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGeneratorTest.java, api/src/main/java/org/commonjava/indy/core/content/MergedContentAction.java, clients/core-java/src/main/java/org/commonjava/indy/client/core/Indy.java, core/src/main/java/org/commonjava/indy/core/content/AbstractMergedContentGenerator.java, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java, subsys/infinispan/src/main/resources/infinispan.xml
* Use MergedContentAction to tightly coordinate de-indexing with core actions implemented by ContentGenerator implementations
* Remove duplicate logic for removing merged files from affected groups
* Configure index storage locations for content-index and folo sealed records to avoid file lock collisions during testing and organize indexing better on deployed systems
* Deprecate old Indy client API constructors in favor of those using SiteConfiguration or to eliminate those with arbitrary subsets of config options
* Switch Infinispan indexed field mappings to @Factory-annotated methods that are referenced from infinispan.xml, to enable more uniform control via this configuration file
=> Coordinate maintenance of merged files better and fix index storage for infinispan caches.

subsys/flatfile/src/main/java/org/commonjava/indy/subsys/datafile/conf/DataFileConfiguration.java
LegacyQuartzDBMigrationActionTest somehow fails on my local due to sys indy.home loading earlier in DataFileConfiguration than being set in the test which causes invalid final constants values. Fixing it by replacing the constants with methods.
=> LegacyQuartzDBMigrationActionTest somehow fails on my local

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/GroupHostedMetadataRemergedOnNewMemberTest.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/RecursiveGroupMetadataClearOnMemberAddTest.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/RecursiveGroupMetadataClearOnUploadTest.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/RecursiveGroupMetadataFoundAfterMemberAddTest.java, addons/pkg-maven/ftests/src/test/resources/META-INF/beans.xml, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractContentManagementTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/GroupContentCopiedEarlierInMembershipIsReturnedTest.java
This seems to be happening at times when by-group promotion completes. My initial attempt has been to reproduce the effect of the promotion in a simpler context, by manually adding a new member and re-checking the metadata content. It does not reproduce the problem yet.
It's not clear whether this is a race condition, or under what conditions we can verify this as an actual bug.
=> working on reproducing error where group metadata sometimes not re-merged

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiBuildAuthority.java
* fix the filtering to not use only files with the excluded endings
* trim the contents of a loaded md5 file to remove possible newline
character at the end
* change type ordering to use other file types like zip or tar.gz rather
than poms and xmls
* fix a typo
=> (master) Fix koji authority handling

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiBuildAuthority.java
* fix the filtering to not use only files with the excluded endings
* trim the contents of a loaded md5 file to remove possible newline
character at the end
* change type ordering to use other file types like zip or tar.gz rather
than poms and xmls
* fix a typo
=> Fix koji authority handling

pom.xml
This contains fix for nos-749 JoinableFileManager - Failed to close: OUTPUT. This requires "https://github.com/Commonjava/partyline/pull/52" to be merged first.
=> Use partyline 1.9.2-SNAPSHOT

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiBuildAuthority.java
Previously all Brew content was dropped and only versions available in
Indy was included in generated maven-metadata.xml files..
=> Skip only invalid builds when reading versions from Brew

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiBuildAuthority.java
Previously all Brew content was dropped and only versions available in
Indy was included in generated maven-metadata.xml files..
=> (master) Skip only invalid builds when reading versions from Brew

addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/util/HttpConduitWrapper.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiBuildAuthority.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java, core/src/main/java/org/commonjava/indy/core/ctl/ContentController.java, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractContentManagementTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/GroupHttpHeadersFromSameRepoAsPomTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/GroupHttpHeadersFromSameRepoWhenNotInPathMaskTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/GroupPreferContentFromFirstMemberTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/NestedStoreInGroupWithErrorTest.java, ftests/core/src/main/resources/META-INF/beans.xml
* Reuse existing Transfer to lookup http-metadata when possible to avoid need to re-lookup that main Transfer.
* When looking for content in a group, search the index **and try retrieve() or getTransfer()** for each member before moving on. This avoids situation where a lower member may have its content indexed but a higher member also contains the content...it's just not indexed. If we try all indexes before trying to retrieve the content from any member, the lower member's index may grant precedence to its content even though an un-indexed system would grant precedence to the higher member's content.
* Avoid recursion in the retrieve() / getTransfer() / getIndexedMemberTransfer(), using a List and while loop.
* Implement a couple of potential failure scenarios where misaligned content …
=> Improve http-metadata retrieval and consistency of content-indexing usage

addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/util/HttpConduitWrapper.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiBuildAuthority.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java, core/src/main/java/org/commonjava/indy/core/ctl/ContentController.java, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractContentManagementTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/GroupHttpHeadersFromSameRepoAsPomTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/GroupHttpHeadersFromSameRepoWhenNotInPathMaskTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/GroupPreferContentFromFirstMemberTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/NestedStoreInGroupWithErrorTest.java, ftests/core/src/main/resources/META-INF/beans.xml
* Reuse existing Transfer to lookup http-metadata when possible to avoid need to re-lookup that main Transfer.
* When looking for content in a group, search the index **and try retrieve() or getTransfer()** for each member before moving on. This avoids situation where a lower member may have its content indexed but a higher member also contains the content...it's just not indexed. If we try all indexes before trying to retrieve the content from any member, the lower member's index may grant precedence to its content even though an un-indexed system would grant precedence to the higher member's content.
* Avoid recursion in the retrieve() / getTransfer() / getIndexedMemberTransfer(), using a List and while loop.
* Implement a couple of potential failure scenarios where misaligned content …
=> (master) Improve http-metadata retrieval and consistency of content-indexing usage

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiBuildAuthority.java
There is build org.jboss-jboss-parent-10_redhat_2-2 which contains
sources in file org.jboss-jboss-parent-10_redhat_2-sources.zip. This
file is not a valid Maven artifact, which causes the build to be thrown
away and a PNC build fails because of missing artifact.
So the excluded file endings were updated to cover this one and also to
better match only what we want to exclude - e.g. sources.jar would also
match a resources.jar etc, so the hyphen was added to avoid this. It is
still not 100% but IMO better than before.
=> (1.1.x) Fix dropping of builds with old source.zip format

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiBuildAuthority.java
There is build org.jboss-jboss-parent-10_redhat_2-2 which contains
sources in file org.jboss-jboss-parent-10_redhat_2-sources.zip. This
file is not a valid Maven artifact, which causes the build to be thrown
away and a PNC build fails because of missing artifact.
So the excluded file endings were updated to cover this one and also to
better match only what we want to exclude - e.g. sources.jar would also
match a resources.jar etc, so the hyphen was added to avoid this. It is
still not 100% but IMO better than before.
=> (master) Fix dropping of builds with old source.zip format

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java
Switch back to listing artifacts and perform the filtering on the client side.
Also enhance the original seenBuilds concept - a build once seen does not have to be checked again even without further requests to koji, because if it was checked already, so I assume no new info making it pass in the metadata cannot be found.
=> Fix what was broken a few hours ago in maven metadata generation

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiBuildAuthority.java
Brew contains many builds that produced rpms along with Maven artifacts.
Those were skipped because they had no artifactId for the rpm archives.
=> (master) Do not drop builds containing non-maven artifacts

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java
Do not check the same version multiple times if a different build of the
same version is already added to the list.
=> Koji metadata generation speedup

addons/koji/common/src/test/java/org/commonjava/indy/koji/content/KojiMavenMetadataProviderTest.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, addons/pkg-maven/common/src/test/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGeneratorTest.java, api/src/main/java/org/commonjava/indy/content/DirectContentAccess.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDirectContentAccess.java
When directory listing for a group is generated MavenMetadataGenerator
needs to list all subdirectories to decide if maven-metadata.xml should
be part of the list. (The decision is based on if a pom is found in one
of the subdirectories.) So to speed up the listings we can perform them
in parallel for all subdirectories.
When generating the maven metadata themselves there is a similar
situation - we need to merge metadata from all constituents of the group
so collecting those can run in parallel.
The executor services in these cases are intentionally not limited to a
maximum thread count, because the limitation happens in galley on the
http level so it is limited anyway and IMO the limitation here does not
make much sense.
=> Perform requests in parallel for metadata generator

addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/TrackedContentEntry.java
When there are 2 not-yet-sealed tracking reports, i.e. 2 builds running in parallel, and they use the same dependency, it does not get tracked correctly for the second download. This resolves the comparison problem.
=> Fix tracking of similar downloads in 2 different tracking keys

addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/TrackedContentEntry.java
When there are 2 not-yet-sealed tracking reports, i.e. 2 builds running in parallel, and they use the same dependency, it does not get tracked correctly for the second download. This resolves the comparison problem.
=> (master) Fix tracking of similar downloads in 2 different tracking keys

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyResponseWriter.java, addons/httprox/common/src/test/java/org/commonjava/indy/httprox/HttpProxyTest.java, addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/AutoCreateRepoAndRetrievePomTest.java, addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/Propagate404NotFoundTest.java, addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/ProxyReleasesFileLockOnCompletionTest.java
This way we can hit an issue when a server hosts different contents on
different ports. We've hit it recently in npm build when one build
published results to a server on port 49158 which was configured to be
used in a following build but since Indy already had a remote repo on
the same host but port 49160 it used that one instead of the requested
one.
Also once we drop the fallback lookup by name we need to add name
collision checking.
=> [httprox] Do not find repo by name without checking url

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyResponseWriter.java, addons/httprox/common/src/test/java/org/commonjava/indy/httprox/HttpProxyTest.java, addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/AutoCreateRepoAndRetrievePomTest.java, addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/Propagate404NotFoundTest.java, addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/ProxyReleasesFileLockOnCompletionTest.java
This way we can hit an issue when a server hosts different contents on
different ports. We've hit it recently in npm build when one build
published results to a server on port 49158 which was configured to be
used in a following build but since Indy already had a remote repo on
the same host but port 49160 it used that one instead of the requested
one.
Also once we drop the fallback lookup by name we need to add name
collision checking.
=> [master] [httprox] Do not find repo by name without checking url

subsys/infinispan/src/main/resources/infinispan.xml
If eviction strategy is missing, the default is NONE (Never evict entries). This should fix the problem.
=> Fix folo-sealed infinispan cache size not work by adding right strategy

addons/relate/ftests/src/main/java/org/commonjava/indy/relate/ftest/PomDownloadDepFromParentTest.java, addons/relate/ftests/src/main/java/org/commonjava/indy/relate/ftest/PomDownloadListenerTest.java, addons/relate/ftests/src/main/java/org/commonjava/indy/relate/ftest/PomDownloadSimpleDepTest.java, addons/relate/ftests/src/main/java/org/commonjava/indy/relate/ftest/PomDownloadViaGroupListenerTest.java, addons/relate/ftests/src/main/java/org/commonjava/indy/relate/ftest/PomUploadListenerTest.java, addons/relate/ftests/src/main/java/org/commonjava/indy/relate/ftest/RelDownloadPomNotFound404Test.java, addons/relate/ftests/src/main/resources/dep-from-parent/output/rel.json, addons/relate/ftests/src/main/resources/dep-from-parent/repo/org/bar/dep/1.1/dep-1.1.pom, addons/relate/ftests/src/main/resources/dep-from-parent/repo/org/foo/consumer/1/consumer-1.pom, addons/relate/ftests/src/main/resources/dep-from-parent/repo/org/foo/parent/1/parent-1.pom, addons/relate/ftests/src/main/resources/simple-dep/output/rel.json, addons/relate/ftests/src/main/resources/simple-dep/repo/org/bar/dep/1.1/dep-1.1.pom, addons/relate/ftests/src/main/resources/simple-dep/repo/org/foo/consumer/1/consumer-1.pom
I add 3 tests for relate addon.
1. PomDownloadViaGroupListenerTest: gets rel via group
2. RelDownloadPomNotFound404Test: get rel but 404 to simulate upstream error; re-register expectation to 200, retry again to simulate upstream fixed. 
3. PomDownloadWithDependencyViaGroupListenerTest: two poms, one depends on another, put them in two repos, add to a group, then get .rel via this group. 
The first two are Okay. What is confusing is the last one. The dep pom is not downloaded automatically. I remember you mentioned 
MavenPomView pomView = mavenPomReader.read( ref, transfer, supplementalLocations, ALL_PROFILES );
will download dep/parent/etc poms. I need to look into the code. If you have any insights into this, please shed light on it.
=> Add ftests for addons/relate

subsys/infinispan/src/main/resources/infinispan.xml
Add eviction for folo-in-progress. Testing shows the memory footprint keeps increasing if this is ignored.
=> Add infinispan eviction for folo-in-progress cache to avoid memory leak

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyRequestReader.java, api/src/main/java/org/commonjava/indy/conf/DefaultIndyConfiguration.java, embedders/savant/src/main/resources/META-INF/beans.xml, ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/RemoteRepoInValidUrlTest.java, pom.xml
* update to latest partyline snapshot
* update default remote repo request timeout to 30 seconds (can be configured back to 5s where needed via `request.timeout` in main.conf)
* disable validation of urls when remote repos are stored, since it's too aggressive
=> Bump partyline to work on size/checksum mismatch coming from folo tracking records

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyRequestReader.java, api/src/main/java/org/commonjava/indy/conf/DefaultIndyConfiguration.java, embedders/savant/src/main/resources/META-INF/beans.xml, ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/RemoteRepoInValidUrlTest.java, subsys/git/src/main/java/org/commonjava/indy/subsys/git/GitManager.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/UnhandledRuntimeExceptionHandler.java
* update request timeout default value to 30 seconds (it's still globally configurable)
* clean up ConnectionClosedException in httprox
* disable URL validations on remote repositories as current impl is too aggressive
* add handler for unhandled RuntimeException for Resteasy to use
* use blocking locks in GitManager to prevent slow filesystems from messing up git storage
=> Catch up to indy-1.1.x changes resulting from checksum mismatch bug hunt

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/group/MavenMetadataMerger.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RepositoryPathMaskMetadataTest.java
By using the last item in versions array. I do not change the way lastUpdated is merged, since current test cases all use it in assert. And the original way (most recent in versions array) is safe too.
=> Fix wrong latest/release versions for MavenMetadataMerger

addons/folo/common/src/main/java/org/commonjava/indy/folo/change/FoloTrackingListener.java, addons/folo/ftests/pom.xml, addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/report/RecalculateMissingChecksumForTrackingRecordTest.java, addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/report/UseChecksumFromTransferDecoratorForTrackingRecordTest.java, addons/folo/ftests/src/test/resources/logback-test.xml, core/src/main/java/org/commonjava/indy/core/content/DefaultContentDigester.java
We need to avoid constantly recalculating checksums on file reads once the checksums are cached.
Also, when FoloTrackingListener triggers onFileStorage, we need to make sure that's an UPLOAD
TransferOperation before we try to track it. For downloads, this will trigger via onFileAccess.
Adding two specific tests to guard against NPE we're seeing now.
=> (1.1.x) Turn off folo tracking for STORAGE of downloads, and avoid recalculating checksums on reads

addons/folo/common/src/main/java/org/commonjava/indy/folo/change/FoloTrackingListener.java, addons/folo/ftests/pom.xml, addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/report/RecalculateMissingChecksumForTrackingRecordTest.java, addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/report/UseChecksumFromTransferDecoratorForTrackingRecordTest.java, addons/folo/ftests/src/test/resources/logback-test.xml, core/src/main/java/org/commonjava/indy/core/content/DefaultContentDigester.java
We need to avoid constantly recalculating checksums on file reads once the checksums are cached.
Also, when FoloTrackingListener triggers onFileStorage, we need to make sure that's an UPLOAD
TransferOperation before we try to track it. For downloads, this will trigger via onFileAccess.
Adding two specific tests to guard against NPE we're seeing now.
=> Turn off folo tracking for STORAGE of downloads, and avoid recalculating checksums on reads

addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/report/RecalculateMissingChecksumForTrackingRecordTest.java, addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/report/UseChecksumFromTransferDecoratorForTrackingRecordTest.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/RecursiveGroupMetadataClearOnUploadTest.java, embedders/pom.xml, ftests/common/src/main/java/org/commonjava/indy/ftest/core/category/BytemanTest.java
Byteman uses a predictable port on the system for injecting its rules.
This means if more than one process/thread starts Byteman separately,
they may compete for the port. It may be possible to assign different
ports to different tests, but this would be hard to maintain
appropriately.
Instead, we can just run these tests in non-forking mode. It's not
perfect (multiple concurrent builds in CI could still collide), but
it should be okay as a workaround until we can develop dynamic port
allocation for Byteman and get it contributed.
=> Add a new category for Byteman tests

addons/folo/common/src/main/java/org/commonjava/indy/folo/content/FoloChecksumAdvisor.java, api/src/main/java/org/commonjava/indy/content/IndyChecksumAdvisor.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentDigester.java, filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java, pom.xml
The old ChecksummingTransferDecorator implementation from galley didn't provide much flexibility
in terms of turning checksumming on/off, and its configuration was a mass of confusion. We don't
need to calculate checksums, except in two cases:
* when we generate a file, such as maven-metadata.xml
* when we store or download a file via Folo tracking
This change takes advantage of a refactored ChecksummingTransferDecorator, which introduces a
ChecksummingDecoratorAdvisor interface. Two of these are passed into the decorator's constructor,
one for reads and another for writes. Indy extends this concept with IndyChecksumAdvisor. Where
ChecksummingDecoratorAdvisor returns a ChecksumAdvice value, IndyChecksumAdvisor returns one of
these values wrapped in Optional. This allows the Indy advisor …
=> Add IndyChecksumAdvisor to allow add-ons to determine when content checksums are calculated

addons/diagnostics/jaxrs/src/main/java/org/commonjava/indy/diag/bind/jaxrs/DiagnosticsResource.java, api/src/main/java/org/commonjava/indy/util/ApplicationHeader.java, uis/layover/app/index.html
This patch changes the diagnostic bundle REST endpoint to suggest
a filename and prompt the browser to download the file instead of
just displaying it to the screen. It also adds a UI menu item to
help the user access the bundle.
=> (1.1.x) Add drop-down menu item for Diagnostic Bundle download

api/src/main/java/org/commonjava/indy/action/IndyLifecycleManager.java, boot/jaxrs/src/main/java/org/commonjava/indy/boot/jaxrs/JaxRsBooter.java, deployments/docker/base/src/main/docker/Dockerfile, deployments/docker/base/src/main/scripts/start-indy.py, deployments/docker/pom.xml, deployments/launchers/base/src/main/bin/indy.sh
Previously, somewhere in the start-indy.py or indy.sh scripts, SIGTERM
was being discarded. This meant that Indy's shutdown hook was never
executing, and the shutdown for Infinispan and the scheduler DB were
never running. This is why we've been seeing corrupted scheduler data
periodically...but it's also potentially why things in the Infinispan
cache go missing. Infinispan caches are supposed to write through by
default IIRC when persistence is setup, but it seems possible with a
misconfiguration we might end up with a tracking record or something
sitting in memory without being pushed to disk. If this happens and
Indy is killed (SIGKILL) or doesn't run its shutdown hook, it could
result in that data being discarded.
This change uses exec in the indy.sh script, and sets up a signal …
=> (1.1.x) Fix SIGTERM propagation in Docker images

api/src/main/java/org/commonjava/indy/action/IndyLifecycleManager.java, boot/jaxrs/src/main/java/org/commonjava/indy/boot/jaxrs/JaxRsBooter.java, deployments/docker/base/src/main/docker/Dockerfile, deployments/docker/base/src/main/scripts/start-indy.py, deployments/docker/pom.xml, deployments/launchers/base/src/main/bin/indy.sh
Previously, somewhere in the start-indy.py or indy.sh scripts, SIGTERM
was being discarded. This meant that Indy's shutdown hook was never
executing, and the shutdown for Infinispan and the scheduler DB were
never running. This is why we've been seeing corrupted scheduler data
periodically...but it's also potentially why things in the Infinispan
cache go missing. Infinispan caches are supposed to write through by
default IIRC when persistence is setup, but it seems possible with a
misconfiguration we might end up with a tracking record or something
sitting in memory without being pushed to disk. If this happens and
Indy is killed (SIGKILL) or doesn't run its shutdown hook, it could
result in that data being discarded.
This change uses exec in the indy.sh script, and sets up a signal …
=> (master) Fix SIGTERM propagation in Docker images

core/src/main/java/org/commonjava/indy/core/ctl/ReplicationController.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/lifecycle/HttpSiteConfigTest.java, subsys/http/src/main/conf/http.conf, subsys/http/src/main/java/org/commonjava/indy/subsys/http/IndyHttpProvider.java, subsys/http/src/main/java/org/commonjava/indy/subsys/http/conf/IndyHttpConfig.java, subsys/http/src/main/java/org/commonjava/indy/subsys/http/util/IndySiteConfigLookup.java, subsys/http/src/main/resources/default-http.conf, subsys/http/src/test/java/org/commonjava/indy/subsys/http/util/IndySiteConfigLookupTest.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/keycloak/BasicAuthenticationOAuthTranslator.java, subsys/metrics/src/main/java/org/commonjava/indy/metrics/zabbix/sender/IndyZabbixSender.java, test/fixtures-core/src/main/java/org/commonjava/indy/test/fixture/core/HttpTestFixture.java
I simplified the way we define site Ids. Basically, all site Ids are hostnames after replacing '.' with underscores (because '.' is used to separate site id with a key name). When the getClient/Context method is called, Indy tries to find the corresponding site config and use it if found. If not found, fall back to default. 
There is a TODO in the ftest. The problem is I can see the config is loaded from log. But I can not inject a siteConfigLookup in ftest code and test it. Any idea?
=> Add site config for http subsys for special request

bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java
The whole directory tree from a hosted repo was deleted when somebody
requested a directory listing from a group where this hosted repo was a
constituent without an ending slash in URL.
The deletion only makes sense if the content is file and the source repo
allows downloading, i.e. we can refresh the contents from the remote
location. Otherwise we risk losing data from a hosted repo.
=> [1.1.x] Fix NOS-881: Random content deletion

bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java
The whole directory tree from a hosted repo was deleted when somebody
requested a directory listing from a group where this hosted repo was a
constituent without an ending slash in URL.
The deletion only makes sense if the content is file and the source repo
allows downloading, i.e. we can refresh the contents from the remote
location. Otherwise we risk losing data from a hosted repo.
=> [master] Fix NOS-881: Random content deletion

ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/StoreThenGetUnSuffixedDirAndDownloadTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/StoreThenGetUnSuffixedDirAndDownloadViaGroupTest.java, models/core-java/src/main/java/org/commonjava/indy/model/core/GenericPackageTypeDescriptor.java, models/core-java/src/main/java/org/commonjava/indy/pkg/maven/model/MavenPackageTypeDescriptor.java
A PR has already been submitted which indicates the conditions under which
NOS-881 can occur. When the user uploads content to a hosted repository, then
retrieves a directory listing without using either a trailing slash '/' or
'/index.html' on that same directory path, Indy for some reason deletes the
entire directory. I assume this was something aimed at remote repositories,
to prompt a refresh of the directory listing. But even for that, it seems to
cut too deep.
And of course, for hosted repositories deleting a directory is a disaster.
This change adds a test that reproduces the simple case, where content
is stored, then the directory referenced in a GET request (prompting deletion
in the old code), and finally the originally stored artifact is re-requested
via simple GET.
[NOS-881] …
=> (master) Fix broken imports, and add reproducer test for NOS-881

bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java
* remove the deletion causing the previous issues completely - the code was not reachable at all in current state. There was another possible solution to reduce the condition to "location.allowsDowenloading()" only, but IMO it doesn't make sense anyway, because it would delete the directory and then recreate it to refresh the listing, but the refresh can happen also without the deletion of everything cached in it. Another thing would be if it tried to cache a file with the same name instead of directory, but that's not what is happening there.
=> [1.1.x] Cleanups

bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java
* remove the deletion causing the previous issues completely - the code was not reachable at all in current state. There was another possible solution to reduce the condition to "location.allowsDowenloading()" only, but IMO it doesn't make sense anyway, because it would delete the directory and then recreate it to refresh the listing, but the refresh can happen also without the deletion of everything cached in it. Another thing would be if it tried to cache a file with the same name instead of directory, but that's not what is happening there.
* use correct package type in ContentAccessHandler.doCreate()
=> [master] Cleanups

scripts/folo-repair/folofix/command.py, scripts/folo-repair/folofix/downloader.py, scripts/folo-repair/folofix/reporter.py
I have it run after fixing some problems. The most exciting outcome is it does produce some mismatch files. It sounds like we have a way to reproduce the jar/sha/md5 mismatch issues. What I did: 1. start up a local indy, and run the multibuild script to do some builds, 2. run this script "$ tracking-check http://localhost:8080". There I can see some mismatch.json files.
=> Fix some folo-repair script issues and make it runnable

scripts/folo-repair/folofix/command.py, scripts/folo-repair/folofix/downloader.py, scripts/folo-repair/folofix/reporter.py, scripts/multibuild/mb/builder.py
Usage example:
tracking-check http://localhost:8080 --storage_dir ${indy.home}/var/lib/indy/storage
It will print something like:
... 
"size": {
"record": 19686, 
"calculated": 19685, 
"storage": 19686, 
"success": false
},
=> Add storage file size check to scripts/folo-repair/folofix/command.tracking-check

deployments/launchers/base/src/main/bin/indy.sh
We found that there are always some unhandled exception directed to the system log but not indy log file, which make some very fatal error flushed in system journal and makes it hard to trace. After check, I think it is caused by the jboss-weld-logging provider issue. So set it in start script.
@jdcasey I'm not sure if this is the good place to set the logger, if it is not, you can point out where is the best place.
=> Set jboss logging provider to slf4j in start script

core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RepositoryPathMaskExtTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RepositoryPathMaskMetadataTest.java
Backport #690 to 1.1.x in an attempt to have faster mask checking.
=> [1.1.x] NOS-939: Differentiate between plaintext and regexps in path mask patterns

scripts/multibuild/mb/builder.py, scripts/multibuild/mb/util.py
I happened to find that scripts/multibuild/mb/util.py is missing in 1.1.x branch. Add it back. Also add "-DskipTests" to bultibuild/mb/build script to do build fast.
=> Fix missing scripts/multibuild/mb/util.py

core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RepositoryPathMaskMetadataExcludeTest.java
The RepositoryPathMaskMetadataTest and the new RepositoryPathMaskMetadataExcludeTest should have covered both cases.
=> Move path-mask checking to DefaultDownloadManager from DefaultContetManager

addons/httprox/common/src/test/java/org/commonjava/indy/httprox/HttpProxyTest.java, addons/pkg-maven/common/src/test/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGeneratorTest.java, addons/promote/common/src/test/java/org/commonjava/indy/promote/data/PromotionManagerTest.java, clients/core-java/src/main/java/org/commonjava/indy/client/core/Indy.java, clients/core-java/src/main/java/org/commonjava/indy/client/core/module/IndyNfcClientModule.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java, core/src/main/java/org/commonjava/indy/core/inject/ExpiringMemoryNotFoundCache.java, core/src/test/java/org/commonjava/indy/core/content/DefaultDownloadManagerTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/ContentRescheduleTimeoutTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/HostedMissingAddToNFCTest.java
Currently the NFC only applies on group level and remote but not on
hosted, so we will add NFC in DownloadManager to give the support on
hosted too to reduce the cost on missing resource check.
And also did some code optimization in this commit, like diamond
operator using and map.computeIfAbsent using.
=> Use NFC in DownloadManager to record missing resources for hosted

addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/util/ReadOnlyTransfer.java
There is a recently added overloaded method openOutputStream() in
Transfer which should be also overriden in ReadOnlyTransfer to prevent
writing into a read-only transfer.
=> Add missing ReadOnlyTransfer.openOutputStream() override

addons/koji/common/pom.xml, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java
We will set all koji remote repo athoritative index enabled, which means
all brew artifacts will only be fetched if they have been indexed in cache.
That should let all koji artifacts pre-indexed in the content index cache.
=> Add authoritativeIndex field to AbstractRepository - koji remote part

addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexManager.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingDirectContentAccessDecorator.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/conf/AuthoritativeIndexSettingManager.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/conf/ContentIndexConfig.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/AuthoritativeIndexedContentInHostedTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/AuthoritativeIndexedContentInRemoteTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/HostedAuthIndexWithReadonly.java
The authoritative index support will let all store which
enabled the authoritative fetch the artifacts which are only
cached in content index. By doing this, it will enhance the
performance by avoid meaningless artifact path findings in repo
(all existed artifacts will be cached in content index firstly)
=> Implement conditional support for authoritative indexing

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/PromoteAllTest.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/PromoteDryRunTest.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/RollbackTwoArtifactsTest.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java, core/pom.xml, core/src/main/java/org/commonjava/indy/core/ctl/ContentController.java, core/src/main/java/org/commonjava/indy/core/model/StoreHttpExchangeMetadata.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/DownloadContentHasLengthHeaderHostedTest.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/ResponseUtils.java
@jdcasey 
The build for PR#750 tests failed, and seem the ContentAccessHandler head handling still has some problems. http://pastebin.test.redhat.com/505685
1. Make all kinds of items getting from getTransfer regardless with its cacheOnly value, will result the content could still be retrieved from the disabled stores by the physical transfer? That’s why ContentNotAvailableInGroupWithDisabledRemoteTest failed.
2. ContentLength was not aligned, reason in Line https://github.com/Commonjava/indy/blob/master/bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java#L264 , group/hosted has no httpMetadata generated before, but now we have it, so item will still be kept as null by the judgment ‘if ( httpMetadata == null )’, this will make Content-Length 0 when …
=> Build on #750 by fixing ftests for http-metadata generation on content storage

addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexManager.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/NFCContentListener.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/NestedStoreInGroupWithErrorTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/TwoGroupsWithSameHostedNFCTest.java
When group loop fetching with recursion done, if the transfer is not found, should cached it in NFC, and clear it from NFC vice versa. 
Also did a refactor:
* Extracts the group constituents loop part into one single method, with a supplier lambda definition.
=> Apply NFC of nested groups too, not just concrete repos

deployments/launchers/savant/src/main/resources/META-INF/beans.xml
KojiContentManagerDecorator is designed to execute ONLY when normal content
retrieval fails. In this case, it will query into Koji to see if a matching
build exists, then wire up a RemoteRepository to proxy that build. In subsequent
requests for that content, the normal content retrieval logic will apply, using
the new RemoteRepository.
Because of this, KojiContentManagerDecorator should be the outermost (or among
the outermost, in the event we implement another failover-style decorator).
Putting this inside other decorators risks exposing it to implementation details
of those decorators that can circumvent the failover behavior, which only works
in the context of group content retrieval.
This change reorders the ContentManager decorators, and adds a comment to the
beans.xml in …
=> [1.1.x] Change the decorator ordering for ContentManager to make failover to koji work.

deployments/launchers/savant/src/main/resources/META-INF/beans.xml
KojiContentManagerDecorator is designed to execute ONLY when normal content
retrieval fails. In this case, it will query into Koji to see if a matching
build exists, then wire up a RemoteRepository to proxy that build. In subsequent
requests for that content, the normal content retrieval logic will apply, using
the new RemoteRepository.
Because of this, KojiContentManagerDecorator should be the outermost (or among
the outermost, in the event we implement another failover-style decorator).
Putting this inside other decorators risks exposing it to implementation details
of those decorators that can circumvent the failover behavior, which only works
in the context of group content retrieval.
This change reorders the ContentManager decorators, and adds a comment to the
beans.xml in …
=> [master] Change the decorator ordering for ContentManager to make failover to koji work.

core/src/main/java/org/commonjava/indy/core/change/StoreEnablementManager.java
When a store is unavailale and requests end by timeouts an
IndyStoreErrorEvent is fired, so in case of ArtifactStoreEnablementEvent
it is always a manual action triggered by a client and hence it does not
make sense to schedule an automatic re-enablement.
=> [NOS-1054] Remove automatic store re-enablement when disabling manually

core/src/main/java/org/commonjava/indy/core/change/StoreEnablementManager.java
When a store is unavailale and requests end by timeouts an
IndyStoreErrorEvent is fired, so in case of ArtifactStoreEnablementEvent
it is always a manual action triggered by a client and hence it does not
make sense to schedule an automatic re-enablement.
=> [1.1.x][NOS-1054] Remove automatic store re-enablement when disabling manually

core/src/main/java/org/commonjava/indy/core/expire/ScheduleManager.java
PNC devel env found that there were NPE happening in
ScheduleManager.expired of the infinispan cache timeout working, so
added some code to check potential NPE and rethrow
IllegalArgumentException to make sure the NPE location. And also added
the event.isPre to make sure the event instance is passed in after the real event happening
=> [1.2.x]Add some potential NPE checking in ScheduleManager

core/src/main/java/org/commonjava/indy/core/expire/ScheduleManager.java
PNC devel env found that there were NPE happening in
ScheduleManager.expired of the infinispan cache timeout working, so
added some code to check potential NPE and rethrow
IllegalArgumentException to make sure the NPE location. And also added
the event.isPre to make sure the event instance is passed in after the real event happening
=> [MASTER] Add some potential NPE checking in ScheduleManager

addons/koji/common/pom.xml, addons/koji/common/src/main/java/org/commonjava/indy/koji/conf/IndyKojiConfig.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/inject/KojijiProvider.java, addons/koji/common/src/test/java/org/commonjava/indy/koji/content/KojiMavenMetadataProviderTest.java, addons/koji/ftests/src/main/java/org/commonjava/indy/koji/ftest/AbstractKojiIT.java, addons/koji/ftests/src/main/java/org/commonjava/indy/koji/ftest/ProxyRemoteKojiContentTest.java, pom.xml
Changes in KojiContentManagerDecorator: 
1. Two places are using multicall. I have commented them. 
The old flow is: KojiDecorator asks to listBuildsContaining ( inside it, Kojiji send listArchives by GAV; Koji return a list of builds; Kojiji then call getBuild for each of them to retrieve some details); for each build, it calls listTags to get the tags, do some check, etc. The new flow is: KojiDecorator asks to listBuildsContaining ( inside it, Kojiji send listArchives by GAV; Koji return a list of builds; Kojiji then use multicall to get buildInfo for all builds); KojiDecorator then calls multicall form of listTags( all build ids ... ) to get the tags for all builds in one RPC request.
2. I found patterns.addAll( ...a.getGroupId().replace...) threw an NPE when I tested it by …
=> Adopt kojiji2.0/RWX2.0 and use Kojiji multicall in KojiContentDecorator

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java
kojiji was refactored and the listArchivesForBuild method does not use
maven package type anymore and because of that the result is missing the
maven-specific fields like groupId, artifactId etc and that causes NPE.
Workarounding it by building the query ourselves adding the type there.
The stacktrace was:
```
org.commonjava.indy.IndyWorkflowException: Cannot retrieve builds for: org.optaplanner:optaplanner-bom:pom:6.5.0.Final-redhat-16. Error: Koji withSession lambda command failed: null
at org.commonjava.indy.koji.content.KojiContentManagerDecorator.proxyKojiBuild(KojiContentManagerDecorator.java:380) ~[indy-embedder-savant-1.1.11.jar:na]
at org.commonjava.indy.koji.content.KojiContentManagerDecorator.findKojiBuildAnd(KojiContentManagerDecorator.java:288) …
```
=> [1.1.x] Fix NPE in koji add-on

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java
kojiji was refactored and the listArchivesForBuild method does not use
maven package type anymore and because of that the result is missing the
maven-specific fields like groupId, artifactId etc and that causes NPE.
Workarounding it by building the query ourselves adding the type there.
The stacktrace was:
```
org.commonjava.indy.IndyWorkflowException: Cannot retrieve builds for: org.optaplanner:optaplanner-bom:pom:6.5.0.Final-redhat-16. Error: Koji withSession lambda command failed: null
at org.commonjava.indy.koji.content.KojiContentManagerDecorator.proxyKojiBuild(KojiContentManagerDecorator.java:380) ~[indy-embedder-savant-1.1.11.jar:na]
at org.commonjava.indy.koji.content.KojiContentManagerDecorator.findKojiBuildAnd(KojiContentManagerDecorator.java:288) …
```
=> [master] Fix NPE in koji add-on

pom.xml
The 1.7-SNAPSHOT artifact for jhttpc cannot be downloaded anymore. We can either put the version to the released version 1.7 or to 1.8-SNAPSHOT. This PR sets the version to the released version 1.7
=> Adjust jhttpc version to 1.7

core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java
Sometimes it prints thousands of lines of group members in DEBUG log. It is not necessary since we can easily get the members of a group via UI or api.
=> Move log for printing group members from DEBUG to TRACE in retrieve()

addons/promote/ftests/pom.xml, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/ByPathPromotionWithPurgeMayDisruptMetadataTest.java
Explicit the logic: when the group metadata is created but removed by promotion/purge, a user will get null but the next request will restore the right group metadata.
=> Add ByPathPromotionWithPurgeMayDisruptMetadataTest

addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessHandler.java, api/src/main/java/org/commonjava/indy/util/ApplicationHeader.java, core/src/main/java/org/commonjava/indy/core/ctl/ContentController.java
- npm response content-type should be distinctive for json and tarball.
- npm doHead method should fetch the http-meta as the mapping path directly to get the headers info for further header set.
- npm remote retrieves the content which has downloaded once, should turn to the content of mapping path.
=> [npm] resolve npm response header customized content-type, http-meta mapping fetching path, and remote re-download mapping path issue

addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, core/src/main/java/org/commonjava/indy/core/content/group/GroupMergeHelper.java, db/flat/src/main/java/org/commonjava/indy/flat/data/DataFileStoreDataManager.java, embedder-tests/savant/pom.xml, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/GroupMembershipAddMayDisruptMetadataTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/GroupMembershipChangeUpdateMetadataTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/GroupMembershipDeletionMayDisruptMetadataTest.java
1. Allow return null but not add the result to NFC so next req can try again
2. Add positive test GroupMembershipChangeUpdateMetadataTest
3. Add Byteman tests GroupMembershipAdd/DeletionMayDisruptMetadataTest
=> Handle case that metadata generated/exists but return null due to group membership change

api/src/main/java/org/commonjava/indy/model/galley/CacheOnlyLocation.java, api/src/main/java/org/commonjava/indy/model/galley/LocationStoreUpdateListener.java, api/src/main/java/org/commonjava/indy/util/LocationUtils.java, bin/test-setup.sh, core/src/test/java/org/commonjava/indy/core/content/DefaultDownloadManagerTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/HostedRepositoryDeleteNotAllowedWhenReadonly.java, models/core-java/src/main/java/org/commonjava/indy/model/core/ArtifactStore.java, scripts/multibuild/mb/command.py
Main change here is to make ArtifactStore keep the associated Location object as a transient metadata attached to the store to prevent recreating it, and save on object instances in the CacheProvider Transfer map.
=> [master] minor test-script fixes and make ArtifactStore Location instances sticky

api/src/main/java/org/commonjava/indy/model/galley/CacheOnlyLocation.java, api/src/main/java/org/commonjava/indy/model/galley/LocationStoreUpdateListener.java, api/src/main/java/org/commonjava/indy/util/LocationUtils.java, bin/test-setup.sh, core/src/test/java/org/commonjava/indy/core/content/DefaultDownloadManagerTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/HostedRepositoryDeleteNotAllowedWhenReadonly.java, models/core-java/src/main/java/org/commonjava/indy/model/core/ArtifactStore.java, scripts/multibuild/mb/command.py
Main change here is to make ArtifactStore keep the associated Location object as a transient metadata attached to the store to prevent recreating it, and save on object instances in the CacheProvider Transfer map.
=> [1.2.x] Minor test script changes, and make ArtifactStore Locations sticky

core/src/main/java/org/commonjava/indy/core/expire/ScheduleKey.java, core/src/main/java/org/commonjava/indy/core/expire/StoreKeyMatcher.java
This is going to fix the bug of NOS-1108, although didn't catch the real configs to cause this when  maven-metadata download, it has been checked that this should occur in the process of cancelling/removing existed timeout schedules from cache, the code could prevent the NPE throw during that in some extent.
=> fix potential NPE problem for metadata timeout schedule caused by ScheduleKey missing (empty values) in cache

api/src/main/java/org/commonjava/indy/conf/DefaultIndyConfiguration.java, api/src/main/java/org/commonjava/indy/conf/IndyConfiguration.java, core/src/main/java/org/commonjava/indy/core/inject/ExpiringMemoryNotFoundCache.java, core/src/main/resources/default-main.conf, deployments/launchers/base/src/main/conf/main.conf
We had a problem waiting to happen in the NFC. If the expiration reaper thread
was executing and iterating over a large set of entries, it might still be in
progress when Indy tried to add a new NFC entry. This would have resulted in
ConcurrentModificationException on the missingWithTimeout map. I have added
code to make defensive copies of the map keys whenever we need to iterate, and
to synchronize for any modification or large access of the map (including copying
the set of keys).
Additionally, the reaper thread was hard-coded to run every 8 hours, which is
really infrequent compared to the default 5-minute timeout of NFC entries. I
made this configurable in the Indy main.conf (nfc.sweep.minutes parameter),
and set the default value to 30 minutes. I also updated the default config
file …
=> Guard against concurrent modification in NFC, add sweep configuration

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataMergeListner.java, addons/pkg-maven/ftests/pom.xml, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/StoreGeneratedMetadataInRemoteTest.java, addons/pkg-maven/ftests/src/main/resources/logback-test.xml, core/src/main/java/org/commonjava/indy/core/change/event/DefaultStoreEventDispatcher.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, ftests/common/src/main/resources/logback-test.xml, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/StoreGeneratedMetadataInRemoteTest.java
Basic fixes:
1. Generate meta for remote repositories when it is not available during group meta request
- Make downloadMissingMemberMetadata return store where the meta downloading fails.
- Add generateMissingMemberMetadata after it to generate those missings.
2. Listen to ArtifactStoreDeletePreEvent in MetadataMergeListner
- Otherwise, when deleting a store, it won't trigger the cascade group meta update
Other fixes:
1. Clear obsolete HTTP download meta.json after a meta is generated. Otherwise, it will fail the rendering of group meta file due to Content-length 0 problem (which is caused by unsuccessfully attempting to download it in the previous try). 
2. Update maven-pkg add-on pom so that we can run ftest inside IDEA.
3. Comment the executor usage in DefaultStoreEventDispatcher. …
=> Generated metadata in remote repo during group meta request and surrounding fixes

addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexedStorePath.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/NFCContentListener.java, core/src/main/java/org/commonjava/indy/core/inject/IspnNotFoundCache.java, models/core-java/src/main/java/org/commonjava/indy/model/core/StoreKey.java
The package type is missing in IndexedStorePath and cause the store not found when generating NFC keys.
=> NPE when clearing artifact from NFC due to missing NPM package type

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/change/MetadataMergePomChangeListener.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/GroupHostedMetadataRemergedOnNewMemberTest.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/GroupHostedMetadataRemergedOnPomDeletionTest.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/GroupHostedMetadataRemergedOnPomUploadTest.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/GroupMetadata401ErrorTest.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/GroupMetadataChecksumRequestedFirstTest.java, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractContentManagementTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/HostedMissingAddToNFCTest.java
In bug NOS-1126 and NOS-1053, the maven-metadata.xml versioning/versions didn't align to the artifacts that should be existed, or sometimes it would appear less/more than the actuals.
Indy should handle the versions alignment: for a new version (pom) upload/deletion, clear the maven meta and version cache to trigger meta regen process, not only for the hosted or group constituents change or meta self change just as before (MetadataMergeListner).
=> add version (pom) upload/deletion change listener to align the versions in maven meta file

README.md
This is to force rebuild Indy 1.2 snapshot after "turn off stream finalizer registration".
=> Rebuild 1.2 indy snapshot using new partyline latest 1.3 snapshot

addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloContentAccessResource.java, addons/pkg-maven/jaxrs/src/main/java/org/commonjava/indy/pkg/maven/jaxrs/MavenContentAccessResource.java, addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessResource.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/AbstractPromotionManagerTest.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/PromoteAllTest.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/PromoteDryRunTest.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/RollbackTwoArtifactsTest.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/DeprecatedContentAccessResource.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/util/RequestUtils.java, clients/core-java/src/main/java/org/commonjava/indy/client/core/util/UrlUtils.java, core/src/main/java/org/commonjava/indy/core/content/HttpMetadataCleanupGenerator.java, filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/StoreArtifactsAndRemoveThenHttpMetaDeletedTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/StoreArtifactsThenHttpMetaGeneratedTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/StoreMetaThenHttpMetaNotGeneratedTest.java
For new FastLocalCacheProvider, sometimes when large file uploading not finished and some clients request these files, they will get incorrect file metadata like file length, which will cause file mismatch problem. So we need to store the correct file metadata before the file uploading in a http-metadata.json, like what we have done for the remote pulling of the artifacts. Something different is that these metadata is from client http request headers.
=> Implement http-metadata generation for file uploading

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, api/src/main/java/org/commonjava/indy/action/IndyLifecycleEventManager.java, api/src/main/java/org/commonjava/indy/change/EventUtils.java, core/src/main/java/org/commonjava/indy/core/change/event/DefaultStoreEventDispatcher.java, core/src/main/java/org/commonjava/indy/core/change/event/IndyFileEventManager.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java, core/src/main/java/org/commonjava/indy/core/expire/ScheduleManager.java, subsys/flatfile/src/main/java/org/commonjava/indy/subsys/datafile/change/DataFileEventManager.java
This PR enables NFC management when files are uploaded. It also cherry-picks two commits from the indy-1.2.x branch which were not ported over to the master branch. These are:
* Consolidate event firing behind EventUtils
* Synchronize retrieval of ReentrantLock in MavenMetadataGenerator to make it safer
=> update NFC on file storage, and sync changes from 1.2.x branch

core/src/main/java/org/commonjava/indy/core/expire/ScheduleManager.java
Due to starting to use ISPN cache expiration mechanism to manage all
indy scheduler, the thread-safe stuff is proxied to ISPN to manage. So
these lock monitors are not neccessary now.
=> [MASTER] Remove all lock monitors in ScheduleManager

core/src/main/java/org/commonjava/indy/core/expire/ScheduleManager.java
Due to starting to use ISPN cache expiration mechanism to manage all
indy scheduler, the thread-safe stuff is proxied to ISPN to manage. So
these lock monitors are not neccessary now.
=> Remove all lock monitors in ScheduleManager

bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/util/TransferStreamingOutput.java
As partyline has removed the stream closing finalizers, the split
thread pool in TSO is useless now. So revert this commit.
=> Revert "NOS-1155 Use a split thread pool in TSO to avoid stream escaping problem"

bin/test-setup.sh, deployments/launcher/src/main/bin/indy.sh
The indy.sh is missing in the previous simple-distro PR. Add it back. 
Update the bin/test-setup.sh accordingly.
=> Restore the missing indy.sh

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyAcceptHandler.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyResponseWriter.java, deployments/launcher/src/main/etc/indy/logging/logback.xml
This uses a variation of the code found in ResourceManagementFilter.
Instead of using the logger 'org.commonjava.topic.rest.inbound', this
one doesn't handle REST requests. Accordingly, the httprox logger is
'org.commonjava.topic.httprox.inbound'.
Modify logging config to account for new httprox inbound logging
=> Adding HTTP request inbound START/END logging to topical logger

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/group/MavenMetadataMerger.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/GroupMetadataMergeWithInvalidVersionTest.java
In cases where Indy is trying to merge maven-metadata.xml files, and
encounters an invalid / unparsable version like '${project.version}',
it currently fails the whole merge operation with the unchecked
InvalidVersionSpecificationException. This is incorrect, since it
makes it impossible to arrive at a maven-metadata.xml file for that G:A
coordinate in that group.
This change ignores invalid / unparsable versions and filters them out
of the resulting merged metadata file. Included is a test which verifies
this new behavior.
=> [1.1.x] Ignore invalid versions when sorting merged maven-metadata.xml

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/group/MavenMetadataMerger.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/GroupMetadataMergeWithInvalidVersionTest.java
In cases where Indy is trying to merge maven-metadata.xml files, and
encounters an invalid / unparsable version like '${project.version}',
it currently fails the whole merge operation with the unchecked
InvalidVersionSpecificationException. This is incorrect, since it
makes it impossible to arrive at a maven-metadata.xml file for that G:A
coordinate in that group.
This change ignores invalid / unparsable versions and filters them out
of the resulting merged metadata file. Included is a test which verifies
this new behavior.
=> [1.2.x] Ignore invalid versions when sorting merged maven-metadata.xml

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/group/MavenMetadataMerger.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/GroupMetadataMergeWithInvalidVersionTest.java
In cases where Indy is trying to merge maven-metadata.xml files, and
encounters an invalid / unparsable version like '${project.version}',
it currently fails the whole merge operation with the unchecked
InvalidVersionSpecificationException. This is incorrect, since it
makes it impossible to arrive at a maven-metadata.xml file for that G:A
coordinate in that group.
This change ignores invalid / unparsable versions and filters them out
of the resulting merged metadata file. Included is a test which verifies
this new behavior.
=> [master] Ignore invalid versions when sorting merged maven-metadata.xml

tools/assemblies/src/main/resources/assemblies/dataset.xml
@jdcasey   I find you remove format jar of dataset in 12/14/2017, so indy build can not find the dependency.
So I re-add it.
ruhan's PR maybe not correct.
https://github.com/Commonjava/indy/pull/910
Please review it
=> re-add format jar for fix indy pr build failed

deployments/launcher/src/main/bin/indy.sh
When indy start I found that it is importing jboss logging classes from weld-se with old version, which will make infinispan debug logging incompatible. So I make the jboss-logging jar placed before weld-se in classpath settings, and seems it works.
=> Make jboss-logging lib import first in classpath to avoid import from weld with old version

addons/koji/common/src/main/java/org/commonjava/indy/koji/conf/IndyKojiConfig.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/inject/KojiMavenVersionMetadataLocks.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/inject/KojijiProvider.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataMembershipListener.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataMergeListener.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataMergeListner.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataStoreListener.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/common/src/test/java/org/commonjava/indy/promote/data/PromotionManagerTest.java, api/src/main/java/org/commonjava/indy/change/EventUtils.java, core/src/main/java/org/commonjava/indy/core/content/AbstractMergedContentGenerator.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, core/src/main/java/org/commonjava/indy/core/content/group/GroupMergeHelper.java, core/src/main/java/org/commonjava/indy/core/inject/CoreLockerProducer.java, core/src/main/java/org/commonjava/indy/core/inject/GroupMembershipLocks.java, core/src/main/java/org/commonjava/indy/core/inject/StoreContentLocks.java, db/memory/src/main/java/org/commonjava/indy/mem/data/MemoryStoreDataManager.java, ftests/common/src/main/resources/logback-test.xml, ftests/core/pom.xml, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/StoreGeneratedMetadataInRemoteTest.java, ftests/core/src/main/resources/logback-test.xml, pom.xml
We have two basic problems reported that triggered this PR, and I've rolled them together to try to get it all done in one sweep of the CI PR builder...or rather, one set of builds to get the PR build + the snapshot built.
First is the invalid metadata coming from ibiblio.org, which was an index.html file, and caused the metadata merge to fail. I've reviewed code from the master branch and looked at how we throw exceptions when member metadata fails. I have some hesitance here, since caching partial metadata in the event a member repo is temporarily throwing 503's is a problem if we ignore failed member metadatas...but in the end, it's **probably** less disruptive, especially after I fixed the listing in the maven-metadata.xml.info file. This file will **ONLY** contain contributing member …
=> [1.2.x] backport metadata fixes and stop throwing errors from member metadata

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, deployments/docker/pom.xml, deployments/launchers/pom.xml, embedders/pom.xml, models/core-java/src/main/java/org/commonjava/indy/model/core/ArtifactStore.java, models/core-java/src/main/java/org/commonjava/indy/model/core/StoreKey.java, pom.xml
It seems we had a race condition in the MavenMetadataGenerator. Actually, a couple things were wrong with it:
* the cache retrieval, which results in a set of ArtifactStore's that don't have cached metadata, seems to return a set with duplicates!
* there seems to be something that modifies the missing set when download / generate is starting, but AFTER the latch is created. It creates a periodic off-by-one problem in the latch.
We had a NPE after my refactor of the KojiMavenMetadataProvider, where the old short-circuit logic for disqualifying archives / builds wasn't preserved. I fixed that here.
Finally, to make the lock management more consistent I introduced the Locker class in Weft. This change uses the Weft 1.7 release, which includes that class.
=> Upgrade to Weft release; fix apparent race in maven metadata aggregation

deployments/launcher/src/main/bin/indy.sh
In recent indy prod logs, I found that indy met some "ssl handshake peer shutdown" problem. After google & SO searching, seems this can solve the problem: System.setProperty("https.protocols", "TLSv1,TLSv1.1,TLSv1.2"); 
So added this property to indy startup script.
P.S: SO discussion here: https://stackoverflow.com/questions/28908835/ssl-peer-shut-down-incorrectly-in-java?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
=> Add ssl protocols in system properties to avoid ssl handshake problem

addons/revisions/common/src/main/java/org/commonjava/indy/revisions/RevisionsManager.java, addons/revisions/common/src/test/java/org/commonjava/indy/revisions/RevisionsManagerTest.java, subsys/git/src/main/java/org/commonjava/indy/subsys/git/ChangelogEntry.java, subsys/git/src/main/java/org/commonjava/indy/subsys/git/GitManager.java, subsys/git/src/test/java/org/commonjava/indy/subsys/git/GitManagerConcurrentTest.java, subsys/git/src/test/java/org/commonjava/indy/subsys/git/GitManagerTest.java
One question is: when deleting files the old code use commit.setOnly(path) following rm.addFilepattern(). I don't know why and removed it. If this is necessary, please let me know.
=> Refactor Git audit log for data files

subsys/metrics/src/main/java/org/commonjava/indy/IndyMetricsManager.java, subsys/metrics/src/main/java/org/commonjava/indy/measure/annotation/MetricNamed.java, subsys/metrics/src/main/java/org/commonjava/indy/metrics/jaxrs/interceptor/MetricsInterceptor.java
This can simplify the usage of metric anno without defining the names beforehand. E.g., new anno looks like:
@IndyMetrics( measure = @Measure( timers = @MetricNamed(), meters = @MetricNamed(), ... ))
=> Support default name for Indy metric annotation

subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/metrics/IspnCheckRegistrySet.java, subsys/infinispan/src/main/resources/infinispan.xml, subsys/metrics/src/main/conf/conf.d/metrics.conf, subsys/metrics/src/main/java/org/commonjava/indy/IndyMetricsManager.java, subsys/metrics/src/main/java/org/commonjava/indy/metrics/jaxrs/producer/IndyMetricProducer.java, subsys/metrics/src/main/resources/default-metrics.conf
I found metric is not started when I wanted to test ispn metric via console reporter. It must have been triggerred by accessing something. I added it to start-up actions. 
And I enabled transport,ispn,koji by default if the overall metric subsys is enabled in default-metric.conf. After the change, I can see ispn garges printed like:
indy.ispn.content-index.CurrentNumberOfEntries
value = -1
indy.ispn.content-index.CurrentNumberOfEntriesInMemory
value = -1
I also see,
healthcheck.ThreadDeadlock
value = 1
This proves that the healthcheck impl is wrong (ref my email yesterday). I will fix it later.
=> Add metric to start-up action and adjust some default config

subsys/infinispan/src/main/resources/infinispan.xml
The interval of expiration is by milliseconds not seconds. This need to be updated to pnc-indy-etc too.
=> Fix expiration errors in infinispan.xml by milliseconds per xsd

addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexManager.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCache.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/change/MetadataMergePomChangeListener.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, core/src/main/java/org/commonjava/indy/core/inject/GroupMembershipLocks.java, core/src/main/java/org/commonjava/indy/core/inject/StoreContentLocks.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/infinispan/CacheProducerMergeXmlTest.java, pom.xml, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/metrics/IspnCheckRegistrySet.java, subsys/infinispan/src/main/resources/infinispan.xml
I revert to ISPN 8.x based on the latest code, so we don't lose @ligangty 's fix for log conflict, etc. 
I also add a missing config "content-metadata" to infinispan.xml, and remove 3 "ConfigureCache" annotations (I think they are misused because we use CacheProducer to produce all ISPN caches).
=> Revert ISPN to 8.2 due to persistence incompatibility

core/src/main/java/org/commonjava/indy/core/inject/IspnNotFoundCache.java
This is my bug. :( The old code removed NFC entry when it is "missing" (It should not. It should only remove it when "timeout"). This bug caused NFC malfunction and made the retrievals very slow.
=> Fix NFC timeout bug which caused entry to be removed incorrectly

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java
Seems that currently we clear nfc each time for a transfer promote,
but I think we can clear that after all transfer promotion done for once
in a bundle.
And I changed some of the collection stream to use parallel stream to
see if that helps enhance performance.
=> [Performance] change NFC clear sequence in path promotion

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java
Seems that currently we clear nfc each time for a transfer promote,
but I think we can clear that after all transfer promotion done for once
in a bundle.
And I changed some of the collection stream to use parallel stream to
see if that helps enhance performance.
=> [Master][Performance] change NFC clear sequence in path promotion

addons/koji/common/src/main/java/org/commonjava/indy/koji/prefetch/KojiContentListBuilder.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java, core/src/main/java/org/commonjava/indy/core/content/PathMaskChecker.java, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/prefetch/AbstractRemotePrefetchTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/prefetch/RemotePrefetchDisableTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/prefetch/RemotePrefetchDownloadWithPathMaskPlaintextTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/prefetch/RemotePrefetchDownloadWithPathMaskRegsTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/prefetch/RemotePrefetchDownloadingTest.java, subsys/prefetch/pom.xml, subsys/prefetch/src/main/java/org/commonjava/indy/subsys/prefetch/HtmlContentListBuilder.java, subsys/prefetch/src/main/java/org/commonjava/indy/subsys/prefetch/PrefetchFrontier.java, subsys/prefetch/src/main/java/org/commonjava/indy/subsys/prefetch/PrefetchManager.java, subsys/prefetch/src/main/java/org/commonjava/indy/subsys/prefetch/PrefetchWorker.java
We should care about path mask cases for prefetch. This PR will give this:
* If a remote repo contains some regex styled path masks, it will still use the root path as the initial start point of downloading
* If a remote repo only contains plaintext styled path masks, will directly use the path masks as the downloading list.
* Whatever path masks the repo has, if it has, the prefetcher will only download the path mask permitted artifacts.
=>  [Prefetch] Use path mask firstly if repo has path mask patterns

subsys/infinispan/src/main/resources/infinispan.xml
This will help devel and stage env where we don't have custom infinispan.xml.
=> Set default NFC infinispan expiration to 3 hours

addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java
Seems we're using a wrong store key in content index layer, it should be the key get from the cache value, but not the cache key.
=> [Content Index] Fix wrong usage of the indexed store key

ftests/metrics/src/main/java/org/commonjava/indy/ftest/metrics/jaxrs/MetricsTestResource.java, subsys/metrics/src/main/java/org/commonjava/indy/metrics/jaxrs/interceptor/MetricsInterceptor.java, subsys/metrics/src/main/java/org/commonjava/indy/metrics/reporter/ReporterIntializer.java
The old reporter assumes names begin with "org.commonjava.indy". But 1.3 changed to short names. This causes "no point" error in Grafana.
=> Fix metrics reporter filters to align with metric name change

scripts/git-hooks/README.md, scripts/git-hooks/hooks/pre-push
Want to share some git hooks, so we can use it to do some git control actions, like misoperation to push directly to upstream indy repo.
If we have some other useful git hooks files, we can also keep it in scripts/git-hooks/hooks folder which I added in this PR
=> Add git hooks folder to store git hooks for indy

bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/admin/MaintenanceHandler.java, core/src/main/java/org/commonjava/indy/core/ctl/IspnCacheController.java
I tested it manually. First I use curl to produce an NFC entry, then use the new API "curl -X DELETE http://localhost:8080/api/admin/maint/infinispan/cache/nfc" to clean it. At last, go look from UI and the entry is removed.
=> Add API to clean infinispan cache

addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexManager.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexedStorePath.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/warmer/ContentIndexWarmer.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/util/TransferStreamingOutput.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/ContentIndexGroupUsageTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/ContentIndexRemoteRepoUsageTest.java, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/metrics/IspnCheckRegistrySet.java
But this time, background the whole operation and wait until all concrete stores are processed before processing group content-index references.
=> reimplement more comprehensive cache warming

addons/content-index/src/main/java/org/commonjava/indy/content/index/change/StoreChangeListener.java, embedder-tests/savant/src/test/resources/logback-test.xml, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/ContentIndexNestedGroupAndStoreDeletionTest.java
I found the indices were really not cleaned when a repo/group were deleted. This could cause a lot of useless entries left in the cache. Fix it by listening to the store post deletion event.
=> Add c.o.i.content.index.change.StoreChangeListener to clean up indices when store is deleted

addons/content-index/src/main/java/org/commonjava/indy/content/index/DefaultContentIndexManager.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java, addons/koji/common/src/test/java/org/commonjava/indy/koji/content/KojiMavenMetadataProviderTest.java, rest/api/pom.xml
* Fix NPE introduced by changes for group-level indexing fix
* Refactored KojiMavenMetadataProducer to use a thread pool for scanning archives matching a certain GA when trying to formulate entries to augment aggregated maven-metadata.xml files
* Try to prevent `-DskipTests=true` or `-DskipSurefire=true` from turning off the JUnit test code that is used to generate the Swagger API documentation JSON/YAML. This should allow us to turn off other tests when they're redundant without losing the ability to publish swagger docs.
=> Bugfixes, and parallelize Koji archive scanning for metadata generation

addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexCacheProducer.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexManager.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/DefaultContentIndexManager.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/DirectoryLvContentIndexManagerDecorator.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingDirectContentAccessDecorator.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/warmer/ContentIndexWarmer.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/ContentIndexNestedGroupAndStoreDeletionTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/ContentIndexDirLvWithArtifactsTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/ContentIndexDirLvWithMetadataTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/ContentIndexGroupUsageTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/ContentIndexRemoteRepoUsageTest.java
This leaves out the complexity/confusion of IndexedStorePath being as the "value" of content-index cache. If the StoreKey to be as the value is conceptually enough? Please review.
=> Change content index cache value object type to StoreKey

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java
We should not need to login in order to query Koji about archives, builds, and tags. This is all we need in order to proxy Koji content and formulate metadata for content Koji can offer. The login/logout process takes hundreds of milliseconds in both systems I've tested, and seems to roughly double the times for the calls themselves somehow (maybe owing to session tracking).
I've turned session usage off and tried the new code in our staging environment, and it seems to function much faster. This is a particular problem when we use something like PME to align dependencies, and the call is made to Indy to find out what versions are available.
=> Turn off use of Koji sessions

deployments/docker/pom.xml, embedder-tests/pom.xml, embedder-tests/savant/pom.xml, pom.xml, test/docker/gogs-test-appliance/pom.xml, test/docker/keycloak-test-appliance/pom.xml, test/docker/pom.xml
@jdcasey I don't know how you modify the versions in pom s when doing release. But I found some are not updated to 1.3.2-snapshot.
=> Update version to 1.3.2-SNAPSHOT for some poms

addons/koji/common/src/main/java/org/commonjava/indy/koji/conf/IndyKojiConfig.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/CachedKojiContentProvider.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiBuildAuthority.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/data/KojiRepairManager.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/inject/KojijiProvider.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/metrics/KojiIspnCacheRegistry.java, addons/koji/common/src/test/java/org/commonjava/indy/koji/content/KojiMavenMetadataProviderTest.java, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/CacheHandle.java, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/metrics/IspnCacheRegistry.java, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/metrics/IspnRegistrySetProvider.java
1. Mode all direct kojiClient calls to CachedKojiContentProvider to cache the content. 
2. Add koji config to enable/disable query caches. Add config to expire volatile cache entries. 
I tested it via external Koji test and the caches are working. 
TODO: the caches are acquired via cache manager API. So by default, we don't need to define them in infinispan.xml. However, the current ISPN metrics won't include these because metric registers before these caches are created (they are created the first time being used). I need to figure out a way to include them in ISPN metrics.
=> Cache Koji content aggressively

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyAcceptHandler.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyResponseWriter.java, addons/httprox/common/src/test/java/org/commonjava/indy/httprox/HttpProxyTest.java, bin/test-setup.sh
The ProxyResponseWriter is not a CDI bean so the default way to do metrics does not work. Measure metrics via API.
=> Measure metrics for ProxyResponseWriter

uis/layover/app/partials/group-edit.html, uis/layover/app/partials/includes/group-view.html
I think this group prepend config can only control member adding through "addConstituent" method, like promotion to group. Other way like directly store change from json(like ui page changes) will not be influenced by this config.
=> UI checkbox to setup prepend of new members to group

core/src/main/java/org/commonjava/indy/core/expire/cache/ScheduleCacheProducer.java
I found this listener is not used (when I go through ISPN code to support remote cache).
=> Remove not used ISPN @Listener

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, api/src/main/java/org/commonjava/indy/conf/DefaultIndyConfiguration.java, api/src/main/java/org/commonjava/indy/conf/IndyConfiguration.java, api/src/main/java/org/commonjava/indy/content/DirectContentAccess.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDirectContentAccess.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java, deployments/launcher/src/main/etc/indy/main.conf, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/MetaListingRescheduleTimeoutTest.java, pom.xml
This commit add config to be able to disable remote content listing
download. That means when this is disabled, only the content that's
stored/cached in the system can be viewed on the UI of directory content
listing for remote repository.(or groups with remote repo)
P.S: this PR depends on galley PR: https://github.com/Commonjava/galley/pull/252
=> Add config to disable remote content listing download

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyRequestReader.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/IndyKojiContentProvider.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiBuildAuthority.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiPathPatternFormatter.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/data/KojiRepairManager.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/metrics/KojiIspnCacheRegistry.java, addons/koji/jaxrs/src/main/java/org/commonjava/indy/koji/bind/jaxrs/KojiRepairResource.java, addons/koji/model-java/src/main/java/org/commonjava/indy/koji/model/IndyKojiConstants.java, addons/koji/model-java/src/main/java/org/commonjava/indy/koji/model/KojiMultiRepairResult.java, addons/koji/model-java/src/main/java/org/commonjava/indy/koji/model/KojiRepairResult.java, core/src/main/java/org/commonjava/indy/core/change/StoreEnablementManager.java, db/memory/src/main/java/org/commonjava/indy/mem/data/MemoryStoreDataManager.java, models/core-java/src/main/java/org/commonjava/indy/model/core/ArtifactStore.java, models/core-java/src/main/java/org/commonjava/indy/model/core/Group.java
* koji path-mask calculation didn't work after changes in Kojiji to separate listArchives from retrieval of type-specific info (https://github.com/release-engineering/kojiji/pull/95)
* implement /api/repair/koji/mask/all REST endpoint to avoid need to identify broken repos
* improve path masking efficiency (at cost of lost precision) to use regex and improve time to disqualify a repo
* add in missing field copy operations from ArtifactStore.copyOf() implementations
* add trace logging of generic-proxy request headers once parsed
This PR is mainly to address path-masking problems in the Koji integration that were introduced with Kojiji v2.3. It also introduces a repair-all-masks REST endpoint to complement the repair-repo-masks endpoint added recently. This eliminates the need to identify …
=> Fixing path masks in koji remotes and improve repair endpoints

addons/koji/pom.xml, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataInfo.java, embedder/pom.xml, subsys/metrics/src/main/java/org/commonjava/indy/metrics/IndyMetricsManager.java
MavenMetadataGenerator has a cache value class that it uses, but it was not serializable. This resulted in Infinispan throwing exceptions when asked to cache the value, as it tried to push it into the database.
This will have affected metadata version caching ever since we switched to using the database for cache persistence. That in turn has had a potentially major effect on production performance.
=> disable ftests module in koji addon, and fix serializability in maven metadata generator cache

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyResponseWriter.java
Reverts Commonjava/indy#1085
We have evidence that this isn't the cause of the freeze we're seeing, so I'm pushing this change to a branch on my fork and will roll it back here until we determine that we really need it.
=> Revert "Completely disconnect support for CONNECT when MITM mode is disabled."

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyMITMSSLServer.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxySSLTunnel.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/util/HttpConduitWrapper.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/util/HttpProxyConstants.java, bin/test-setup.sh
A very important fix for SSL tunnel. If MITM takes a long time to download a file, the tunnel socket may timeout which cause the MITM write-to-tunnel hang. With this fix, I can successfully run the "npm install phantomjs-prebuilt" which usually takes 10~20 min on my local.
=> Set SO_TIMEOUT for ProxySSLTunnel to 30 min to avoid tunnel write hang

addons/implied-repos/common/src/main/java/org/commonjava/indy/implrepo/change/ImpliedRepositoryDetector.java, addons/implied-repos/common/src/test/java/org/commonjava/indy/implrepo/change/ImpliedRepositoryDetectorTest.java, addons/implied-repos/ftests/src/main/java/org/commonjava/indy/implrepo/maint/AbstractMaintFunctionalTest.java, addons/implied-repos/ftests/src/main/java/org/commonjava/indy/implrepo/maint/CreateGroupWithMemberImplicationsTest.java, addons/implied-repos/ftests/src/main/java/org/commonjava/indy/implrepo/skim/AbstractSkimFunctionalTest.java, addons/implied-repos/ftests/src/main/java/org/commonjava/indy/implrepo/skim/DisabledGroupNotAddingImpliedTest.java, addons/implied-repos/ftests/src/main/java/org/commonjava/indy/implrepo/skim/EnabledGroupAddingImpliedTest.java, addons/implied-repos/ftests/src/main/java/org/commonjava/indy/implrepo/skim/PomWithPluginRepoAddsRepoToGroupTest.java, addons/implied-repos/ftests/src/main/java/org/commonjava/indy/implrepo/skim/PomWithRepoAddsRepoToGroupTest.java, addons/implied-repos/ftests/src/main/java/org/commonjava/indy/implrepo/skim/ResolveDepViaSkimmedRepoInGroupTest.java, embedder/src/test/resources/logback-test.xml
When adding implied to group, the implied detector does not check implied configuration "enabled.group". So even we disabled groups in  implied config, these disabled groups will also contain the implied repos, which is obviously not reasonable.
=> Fix implied detector problem when adding implied to groups

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/util/HttpConduitWrapper.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/SetContentTypeFromUpstreamIfExistsTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/SetContentTypeNotExistsTest.java, pom.xml, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/ResponseUtils.java
Let's use the content-type from upstream instead of ignoring it,
and use the JDK's mime-typing classes for that has no such field
in upstream server.
=> Set the content-type from upstream

subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/metrics/IspnCheckRegistrySet.java
so we always get some metrics even if others malfunction
=> Wrap ISPN metric gauge retrievals to block Throwable

addons/content-index/src/main/java/org/commonjava/indy/content/index/DefaultContentIndexManager.java, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/BasicCacheHandle.java, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/CacheHandle.java, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/RemoteCacheHandle.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/ResourceManagementFilter.java, subsys/metrics/src/main/java/org/commonjava/indy/measure/annotation/MetricNamed.java, subsys/metrics/src/main/java/org/commonjava/indy/metrics/IndyMetricsConstants.java, subsys/metrics/src/main/java/org/commonjava/indy/metrics/IndyMetricsManager.java, subsys/metrics/src/main/java/org/commonjava/indy/metrics/jaxrs/interceptor/MetricsInterceptor.java
* Also provides a new wrapWithStandardMetrics() method in IndyMetricsManager to allow us to measure specific code blocks with custom names, not just at the method / interceptor level.
* Provides support for empty @Measure annotation, which will use the standard set of timing/counting metrics (as with the new method above)
=> Add metrics to subdivide content requests and provide cache execution timing/count

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyMITMSSLServer.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyRequestReader.java, addons/httprox/ftests/src/main/resources/logback-test.xml
When I looked deep into the httproxy MITM performance, I found it spends a few seconds to do the SSL handshakes. This should not be that long. I found the doRead() always wait for one second before it read 0 bytes (the EOF, indicating the reading is done). I set channel.awaitReadable to 100 mill and the handshakes are finished much faster (within one second). I believe this will boost MITM (and HTTP download) performance quite a bit. I guess it can reduce 1/3 of total downloading time for NPM/yarn builds.
=> Reduce httproxy awaitReadable time from 1 sec to 100 mill

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/index/MavenIndexingStrategy.java
I saw that most metadata which should be fetched from group level
when accessing group is mergable, so I think we should just avoid
mergable metadata files in this strategy
=> Change to use !isMergable for GAV content index strategy

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/index/MavenIndexingStrategy.java
I saw that most metadata which should be fetched from group level
when accessing group is mergable, so I think we should just avoid
mergable metadata files in this strategy
=> [Port to master] Change to use !isMergable for GAV content index strategy

addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexCacheProducer.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/DefaultContentIndexManager.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexedStorePath.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/change/StoreChangeListener.java, addons/promote/common/src/main/data/promote/rules/no-snapshots.groovy, deployments/cache-migrator/test-env/indy-env/infinispan.xml, deployments/cache-migrator/test-env/indy-env/logging/logback.xml, deployments/cache-migrator/test-env/local-env-setup.sh, deployments/docker/pom.xml, embedder/pom.xml, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/ContentIndexDirLvWithArtifactsTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/ContentIndexDirLvWithMetadataTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/ContentIndexGroupUsageTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/ContentIndexNestedGroupAndStoreDeletionTest.java, models/core-java/src/main/java/org/commonjava/indy/model/core/RemoteRepository.java, pom.xml, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/BasicCacheHandle.java, subsys/metrics/reporter/src/test/java/org/commonjava/indy/metrics/socket/ZabbixSocketServer.java, tools/assemblies/src/main/resources/assemblies/complete.xml
Switched back to using IndexedStorePath as value in content-index cache, and switch to use of ISPN Query API when clearing index entries for a store (on store deletion). This avoids iterating all keys in the content index (which can have millions of entries) and the horrible memory profiles that implies.
=> refactor content index store clear / data format

addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexActions.java, addons/diagnostics/jaxrs/src/main/java/org/commonjava/indy/diag/bind/jaxrs/DiagnosticsResource.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/ctl/FoloAdminController.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/data/KojiRepairManager.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, api/src/main/java/org/commonjava/indy/content/StoreContentAction.java, core/src/main/java/org/commonjava/indy/core/change/StoreContentListener.java, core/src/main/java/org/commonjava/indy/core/content/AbstractMergedContentGenerator.java, core/src/main/java/org/commonjava/indy/core/expire/TimeoutEventListener.java, db/memory/src/main/java/org/commonjava/indy/mem/data/MemoryArtifactStoreQuery.java, pom.xml
I've reviewed the use of parallel streams and found the places where the work performed is non-trivial. For the other things, I've changed to use non-parallel streams. 
For non-trivial work, I've added use of a CompletionService implementation that I added to Weft, which allows us to load up a series of Callables and then watch the service as they complete, tallying or accumulating the results. This allows us to use Weft tor threadpool control and monitoring, while still allowing us to process results and wait for tasks to complete without having to know the number of tasks up front.
This change supercedes #1143.
=> Move away from Streams API, especially parallelized forms

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidator.java, api/src/main/java/org/commonjava/indy/content/StoreContentAction.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDirectContentAccess.java, deployments/launcher/src/main/etc/indy/logging/logback.xml, pom.xml
Promotion requests used to bypass the request threadpool for sync calls, which also bypassed the load check in the threadpool. This change uses the Future<> from those async versions of the call and simply performs a Future.get(), returning the result afterward. That will force all requests to go through the threadpool, which subjects them all to the same capacity check.
Also, incorporating the kafka log appender so we can start learning to send logs to Kafka.
=> Integrate kafka log appender changes and align promotion request styles

addons/content-index/src/main/java/org/commonjava/indy/content/index/DefaultContentIndexManager.java, api/src/main/java/org/commonjava/indy/action/IndyLifecycleManager.java, core/src/main/java/org/commonjava/indy/core/expire/ScheduleManager.java, core/src/main/java/org/commonjava/indy/core/expire/ScheduleManagerBooter.java, deployments/cache-migrator/test-env/indy-env/conf.d/connection-pools.conf, deployments/cache-migrator/test-env/indy-env/infinispan.xml, embedder/pom.xml, pom.xml, subsys/cpool/pom.xml, subsys/cpool/src/main/conf/conf.d/connection-pools.conf, subsys/cpool/src/main/java/org/commonjava/indy/subsys/cpool/CPInitialContextFactory.java, subsys/cpool/src/main/java/org/commonjava/indy/subsys/cpool/ConnectionPoolBooter.java, subsys/cpool/src/main/java/org/commonjava/indy/subsys/cpool/ConnectionPoolConfig.java, subsys/cpool/src/main/java/org/commonjava/indy/subsys/cpool/ConnectionPoolInfo.java, subsys/cpool/src/main/java/org/commonjava/indy/subsys/cpool/ConnectionPoolProvider.java, subsys/cpool/src/test/java/org/commonjava/indy/subsys/cpool/ContextBindAndLookupTest.java, subsys/infinispan/src/main/resources/infinispan.xml, subsys/pom.xml
This will help us reuse the same DataSource in all Infinispan caches that get persisted to the DB.
Basically, this allows us to configure a datasource in the new conf.d/connection-pools.conf file,
which will be bound to a JNDI context that is only available within Indy, then lookup those
datasources elsewhere in the application.
Note that, if we use the old style of BootupAction implementation that's part of a class which
uses an Infinispan cache, it may trigger Infinispan to initialize before the datasource is actually
bound!
=> Add JNDI data sources

addons/content-index/src/main/java/org/commonjava/indy/content/index/DefaultContentIndexManager.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/rule/ProjectVersionPatternRuleForTempBuildTest.java, api/src/main/java/org/commonjava/indy/action/IndyLifecycleManager.java, core/src/main/java/org/commonjava/indy/core/expire/ScheduleManager.java, core/src/main/java/org/commonjava/indy/core/expire/ScheduleManagerBooter.java, deployments/cache-migrator/test-env/indy-env/conf.d/connection-pools.conf, deployments/cache-migrator/test-env/indy-env/infinispan.xml, embedder/pom.xml, pom.xml, subsys/cpool/pom.xml, subsys/cpool/src/main/conf/conf.d/connection-pools.conf, subsys/cpool/src/main/java/org/commonjava/indy/subsys/cpool/CPInitialContextFactory.java, subsys/cpool/src/main/java/org/commonjava/indy/subsys/cpool/ConnectionPoolBooter.java, subsys/cpool/src/main/java/org/commonjava/indy/subsys/cpool/ConnectionPoolConfig.java, subsys/cpool/src/main/java/org/commonjava/indy/subsys/cpool/ConnectionPoolInfo.java, subsys/cpool/src/main/java/org/commonjava/indy/subsys/cpool/ConnectionPoolProvider.java, subsys/cpool/src/test/java/org/commonjava/indy/subsys/cpool/ContextBindAndLookupTest.java, subsys/infinispan/src/main/resources/infinispan.xml, subsys/pom.xml
Porting validation rule test from indy-1.7.x branch (1cf4bebaf8b5fc95e0a6960419434552b22763fd)
Porting 3 commits from indy-1.7.x which add support for JNDI DataSources, which allow us to configure a single connection pool for all ISPN caches to use, instead of creating one connection pool per cache, which puts a lot of extra load on the DB.
=> [prod] Add JNDI DataSources (for ISPN) and validation rule pattern test

models/core-java/src/main/java/org/commonjava/indy/model/core/RemoteRepository.java
I really don't think this exception stack trace is needed as all
useful info has been logged, And it occupied bunch of the log space and
polluted the log reading. So removed it.
=> Remove exception stacktrace for remote url Malformed exception

addons/implied-repos/common/src/main/java/org/commonjava/indy/implrepo/change/ImpliedRepositoryDetector.java, addons/implied-repos/common/src/test/java/org/commonjava/indy/implrepo/change/ImpliedRepositoryDetectorTest.java, addons/implied-repos/model-java/src/main/java/org/commonjava/indy/implrepo/data/ImpliedRepoMetadataManager.java
When I test the other PR, two implied repo tests failed because of no metadata IMPLIED_BY_STORES in the origin repo. 
I found that the repo is not persisted after setting the metadata. These two cases passed in the past because of the memory store manager hold the instances in the memory. After switching it to ISPN store manager, we must persist it.
=> Store ArtifactStore after setting metadata IMPLIED_BY_STORES

addons/content-index/src/main/java/org/commonjava/indy/content/index/DefaultContentIndexManager.java
I found this issue when doing the other test. It seems for the self-to-self index, the value object does not have the origin (null) which make the caller think the index not exist.
=> Fix content-index self-to-self entry not found issue

models/core-java/src/main/java/org/commonjava/indy/model/core/ArtifactStore.java
I think this is a typo of the method. Correct me if I'm wrong.
=> [1.7.x] Fix typo of Storertifact.copyBase()

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/GroupMetadataForRemoteTest.java, pom.xml
Maven plugins have special metadata.xml which do not have versions. See http://maven.apache.org/ref/3.3.9/maven-repository-metadata/
This cause the regression where Maven cannot download plugin meta from Indy. See NOSSUP-46. 
p.s. there is a change in pom which I port from master to fix the missing debug log. You can just ignore it.
=> [1.7.x] Generate metadata for a group containing Maven plugins artifacts

addons/promote/common/src/main/data/promote/rules/artifact-refs-via.groovy, addons/promote/common/src/main/data/promote/rules/no-pre-existing-paths.groovy, addons/promote/common/src/main/data/promote/rules/no-snapshots.groovy, addons/promote/common/src/main/data/promote/rules/no-version-ranges.groovy, addons/promote/common/src/main/data/promote/rules/parsable-pom.groovy, addons/promote/common/src/main/data/promote/rules/project-artifacts.groovy, addons/promote/common/src/main/data/promote/rules/project-version-pattern.groovy, addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidationTools.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidator.java, addons/promote/common/src/test/java/org/commonjava/indy/promote/data/PromotionManagerTest.java, subsys/metrics/reporter/src/main/java/org/commonjava/indy/metrics/jaxrs/interceptor/MetricsInterceptor.java
This is for NOSSUP-45. Basically, the promotion ran very slowly. I looked at the grafana for Apr 4 and 5, and found (for some period):
1. promote-rules-executor and promote-rules-runner each run took up to 10 minutes (I suspect there was timeout. The default timeout is 10 minutes).
2. promote-rules-executor load-factor was up to 30,000 %. There are 200 threads in the pool. That adds up to 60,000 tasks waiting in the queue. 
I add a few changes in this PR:
1. remove synchronized(error) from groovy scripts. Use a synchronizedList() instead. This surely will help but not sure how much time it can save. 
2. add forEach() in the validation tool to do serialized execution. I use it to replace some nested paralleledEach() in groovy rules to reduce the parallel tasks to a level that Java can work …
=> [1.7.x] Indy promote perf

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/GroupMetadataForRemoteTest.java
Port from 1.7.x. ==>
Maven plugins have special metadata.xml which do not have versions. See http://maven.apache.org/ref/3.3.9/maven-repository-metadata/
This cause the regression where Maven cannot download plugin meta from Indy. See NOSSUP-46.
=> Generate metadata for a group containing Maven plugins artifacts

addons/promote/common/src/main/data/promote/rules/artifact-refs-via.groovy, addons/promote/common/src/main/data/promote/rules/no-pre-existing-paths.groovy, addons/promote/common/src/main/data/promote/rules/no-snapshots.groovy, addons/promote/common/src/main/data/promote/rules/no-version-ranges.groovy, addons/promote/common/src/main/data/promote/rules/parsable-pom.groovy, addons/promote/common/src/main/data/promote/rules/project-artifacts.groovy, addons/promote/common/src/main/data/promote/rules/project-version-pattern.groovy, addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidationTools.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidator.java, addons/promote/common/src/test/java/org/commonjava/indy/promote/data/PromotionManagerTest.java, subsys/metrics/reporter/src/main/java/org/commonjava/indy/metrics/jaxrs/interceptor/MetricsInterceptor.java
* Performance fixes for promotion
* Throw timeout exception in runParallelAndWait
* Revert default promotion groovy to use paralleledEach
=> [master] Indy promote perf (#1205) (ported from 1.7.x)

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiPathPatternFormatter.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/data/KojiRepairManager.java
This is for NOSSUP-45 where we want to repair the koji repo's path mask but blocked by the pattern test. After applying this fix, we can do the repair again.
=> [1.7.x] Add skipVersionTest flag when doing Koji path mask repair

addons/changelog/common/src/main/java/org/commonjava/indy/changelog/RepoChangeHandler.java, addons/changelog/ftests/src/main/java/org/commonjava/indy/changelog/RepoChangelogStoreTest.java, addons/changelog/jaxrs/src/main/java/org/commonjava/indy/changelog/bind/jaxrs/RepoChangelogResource.java, addons/changelog/model-java/src/main/java/org/commonjava/indy/changelog/model/RepositoryChangeLog.java
To avoid copy StoreKey class to auditquery service, we should keep all fields in RepositoryChangelog pojo using primitive or string for compatible.
=> Use string for storekey in repo change log for auditquery compatible

addons/koji/jaxrs/src/main/java/org/commonjava/indy/koji/bind/jaxrs/KojiRepairResource.java, addons/promote/common/src/main/data/promote/rules/parsable-pom.groovy, addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidator.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/rule/AbstractValidationRuleTest.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/rule/ParsablePomRuleByPathTest.java, addons/promote/jaxrs/src/main/java/org/commonjava/indy/promote/bind/jaxrs/PromoteResource.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/JaxRsUriFormatter.java
The way we use to generate a baseUrl is wrong. This will fail all bypath validations. Briefly, the build(...) is used to pass parameters' values to the path, not append path elements. When doing byPath validation, we create a temp remote repo with this baseUrl as the 'remoteUrl'.
See also NOS-1694.
=> [1.7.x] Fix baseUrl

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/GroupPromoteFailsValidationAsyncTest.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/GroupPromoteFailsValidationTest.java, addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/AbstractPromoteResult.java, addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/GroupPromoteResult.java, addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/PathsPromoteResult.java
Set a top-level error if validation fails, and add a succeeded() method too. Also, pull the error/validation handling up into the abstract class, and set a constructor so we can call super()
=> [1.7.x] Promotion error consistency and improved by-path lock scoping

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/PathsPromoteResult.java, subsys/metrics/reporter/src/main/java/org/commonjava/indy/metrics/IndyMetricsManager.java
When I look at Grafana "Paths Promotion Files", they always say "184,0,184", never change. This should be the result of the first promotion (following each Indy reboot) because the registry does not replace the old gauges with the new ones when we call doPathPromoteMetrics(). Actually, we don't need to add/register new gauges every time. We just add them once and update their return values in doPathPromoteMetrics.
=> Fix byPath promotion gauges

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/PathsPromoteResult.java, subsys/metrics/reporter/src/main/java/org/commonjava/indy/metrics/IndyMetricsManager.java
=> [1.7.x] Fix byPath promotion gauges

addons/folo/common/src/main/java/org/commonjava/indy/folo/data/idxmodel/TrackingKey2StringMapper.java, addons/folo/common/src/test/java/org/commonjava/indy/folo/data/TrackingKey2StringMapperTest.java, addons/folo/model-java/src/test/java/org/commonjava/indy/folo/model/TrackedContentEntryTest.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromoteValidationsManager.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidationTools.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidator.java, addons/promote/common/src/test/java/org/commonjava/indy/promote/validate/PromotionValidationToolsTest.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/GroupPromoteFailsValidationAsyncTest.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/GroupPromoteFailsValidationTest.java, addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/AbstractPromoteResult.java, addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/GroupPromoteResult.java, addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/PathsPromoteResult.java, core/src/main/java/org/commonjava/indy/core/expire/ScheduleManagerBooter.java, filers/default/pom.xml, filers/default/src/main/java/org/commonjava/indy/filer/def/metrics/DefaultStoragePathProvider.java, models/core-java/src/main/java/org/commonjava/indy/model/core/RemoteRepository.java, subsys/cpool/src/main/java/org/commonjava/indy/subsys/cpool/CPInitialContextFactory.java, subsys/cpool/src/main/java/org/commonjava/indy/subsys/cpool/ConnectionPoolBooter.java, subsys/cpool/src/main/java/org/commonjava/indy/subsys/cpool/ConnectionPoolConfig.java, subsys/cpool/src/main/java/org/commonjava/indy/subsys/cpool/ConnectionPoolInfo.java, subsys/cpool/src/main/java/org/commonjava/indy/subsys/cpool/ConnectionPoolProvider.java, subsys/cpool/src/test/java/org/commonjava/indy/subsys/cpool/ContextBindAndLookupTest.java, subsys/groovy/src/test/java/org/commonjava/indy/subsys/template/fixture/MockStoragePathProvider.java, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/AbstractIndyKey2StringMapper.java, subsys/metrics/core/src/main/java/org/commonjava/indy/metrics/system/StoragePathProvider.java, subsys/metrics/core/src/main/java/org/commonjava/indy/metrics/system/SystemGaugesSet.java, subsys/metrics/reporter/src/main/java/org/commonjava/indy/metrics/system/SystemGaugesSetProvider.java
This PR merges 1.7.x code change to master. I did:
git merge 1.7.x
Then I saw a lot of diff. I went back to 1.7.x and found the corresponding commit ids and cherry-pick them to master. I did it several times and until the 'git merge' reports only the pom.xml changes; and at last I use 'git merge -s ours' and push. Unless the pom.xml has dependencies changes, this PR should pass CI test.
The 1.7.x has piled so many changes that make the merge a bit hard. Please review.
=> Master merge 1.7.x

deployments/docker/scripts/start-indy.py
Because python2 goes EOL in 2020: https://pythonclock.org/
=> Python3 support in start-indy.py

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionHelper.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/PromoteIgnoreMissingNonDecoratableTest.java
This check is dupped. We should use the one in PromotionManager so to apply proper result flag.
=> Remove dup transfer.exists check in PromotionHelper

addons/folo/common/src/test/java/org/commonjava/indy/folo/data/FoloRecordZipTest.java
Tool class. Use FoloRecordZipTest to make a zip from tracking record JSON (in order to repair the broken record).
=> Add FoloRecordZipTest for repair broken records

addons/folo/common/src/test/java/org/commonjava/indy/folo/data/FoloRecordZipTest.java, addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/TrackedContentEntry.java
we see NumberFormatException: For input string: "null" in parseInt. It might be because we forget to persist the trackingKey for some reason. In this case, we just ignore it and continues.
=> Fix readExternal problem when read a null trackingId in TrackedContentEntry

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/common/src/test/java/org/commonjava/indy/promote/data/PromotionManagerTest.java, addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/PathsPromoteRequest.java
We agree to check pre-existence of artifacts by validation rule. The flag only used for internal use (ftest).
=> Set path promotion failWhenExists default to false

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/PathsPromoteRequest.java
PNC build group runs concurrent builds which promote to shared-imports where paths always conflict. This PR enables the conflict-check only when the failWhenExists is true. 
Briefly, when they promote to pnc-builds, this flag should be true. When promoting to shared-imports, this should be false.
=> Enable path conflict check only when failWhenExists is true

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/change/MetadataMergePomChangeListener.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataCacheKey.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataCacheKey2StringMapper.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataMergeListener.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataStoreListener.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataUtil.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/cache/MavenMetadataCache.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/cache/MetadataCacheProducer.java, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMGroupDeleteFileTest.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, models/core-java/src/main/java/org/commonjava/indy/IndyContentConstants.java, pom.xml, subsys/infinispan/src/main/resources/infinispan-jdbc.xml
The current maven-metadata cache value is a map which does not align with ISPN well. Once we put a new entry to cache, we have to put the whole map again. This also makes the cache expiration malfunction when some cache is used frequently. 
This pr also fixes a deletion problem (mention in NOS-1836). When we get a cache-only DELETE request, we should not return too soon. Actually, we just need to follow the normal code path.
=> Change maven-metadata cache key type to avoid manipulating paths map

core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java
We have a UI to delete an artifact. This helps to prevent misoperation from users. For those read-only hosted, this is not necessary (already protected).
=> Protect hosted from being deleted when cache-only is true

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/change/MetadataMergePomChangeListener.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataCacheManager.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataKey.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataKey2StringMapper.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataKeyTransformer.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataMergeListener.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataStoreListener.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataUtil.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/StoreKeyBridge.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/cache/MavenMetadataKeyCache.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/cache/MetadataCacheProducer.java, addons/pkg-maven/common/src/test/java/org/commonjava/indy/pkg/maven/content/MetadataCacheManagerTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/infinispan/CacheProducerMergeXmlTest.java, subsys/infinispan/src/main/resources/infinispan-jdbc.xml, subsys/infinispan/src/main/resources/infinispan.xml
As talked, I use a keyCache to improve query performance. I stick to the ISPN cache to store values since we are moving to cluster. A disk-based value store won't match well there.
=> Improve maven metadata cache query via keyCache

addons/content-index/src/main/java/org/commonjava/indy/content/index/DefaultContentIndexManager.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/change/MetadataStoreContentAction.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataStoreListener.java, core/src/main/java/org/commonjava/indy/core/change/StoreChangeUtil.java, core/src/main/java/org/commonjava/indy/core/change/StoreContentListener.java, core/src/main/java/org/commonjava/indy/core/change/StoreEnablementManager.java, core/src/main/java/org/commonjava/indy/core/expire/ScheduleManager.java, core/src/main/java/org/commonjava/indy/core/expire/TimeoutEventListener.java, core/src/main/java/org/commonjava/indy/core/inject/NfcStoreContentAction.java, core/src/test/java/org/commonjava/indy/core/change/StoreChangeUtilTest.java
I have done below to clean up the cache clean-up (both cached files and ISPN), and fix the threading and performance issues. 
1. Use getDiffMembers to replace getDivergedMembers (in StoreChangeUtil.java)
The getDiverged code finds the divergence point and iterates to clean-up for all repos after it. E.g, if pnc-builds group got 700+ members and we remove 1 in the middle, the diverged would be 350, which means we have to do clean-up for the rest 350 repos. It is not necessary AIUI. The new one getDiff find the added and removed repos, and only clean-up these. 
2. Abandon DrainingExecutorCompletionService in StoreContentListener. We need to make the clean-up completely thread-off since it may take a very long time. I also use bigger granularity. I throw all paths for a single repo to one …
=> Improve the cache clean-up on store dis/enable and update events

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiPathPatternFormatter.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/data/KojiRepairManager.java, pom.xml
This addresses a bug in production when we attempt to proxy a Koji build that contains a mixed bag of maven and non-maven archives.
Also included here are some fixes for property keys in the root pom.xml to address merge errors I introduced.
=> Constrain path-mask calculation to maven-type archives from Koji/Brew

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiPathPatternFormatter.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/data/KojiRepairManager.java
This addresses a bug in production when we attempt to proxy a Koji build that contains a mixed bag of maven and non-maven archives.
=> constrain path-mask calc to maven-type archives from Koji

pom.xml, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/CacheProducer.java
Currently when there are both class-path and customized ispn-cluster.xml, the merging logic is not correct which ignored the class-path one, because it always merging the config to default cacheManager but not clusterCacheManager.
=> Fix configuration merging problem for cluster ispn config

subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/CacheProducer.java
After checking, I agree that the cluster cache starting logic should
be both working for class-path only and customized provided mode.
=> Update cluster cache starting logic in CacheProducer

addons/httprox/common/src/test/java/org/commonjava/indy/httprox/HttpProxyTest.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/RecursiveGroupMetadataClearOnUploadTest.java, addons/promote/common/src/test/java/org/commonjava/indy/promote/data/PromotionManagerTest.java, core/src/main/java/org/commonjava/indy/core/content/ContentGeneratorManager.java, core/src/main/java/org/commonjava/indy/core/content/ContentMetadataGenerator.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentDigester.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, core/src/main/java/org/commonjava/indy/core/content/RepairChecksumAdvisor.java, core/src/main/java/org/commonjava/indy/core/inject/CoreCacheProducer.java, core/src/test/java/org/commonjava/indy/core/content/DefaultDownloadManagerTest.java, core/src/test/java/org/commonjava/indy/core/ctl/ContentControllerTest.java, embedder/src/test/resources/logback-test.xml, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/HostedGenerateMissingChecksumTest.java
This is to address NOS-1885 -- Allow automatic generation of checksums also for hosted repos.
The word "metadata" is misleading. It means content metadata, e.g, the checksum files, and probably the http-metadata (not in this case). I borrow this concept from Galley.
Briefly, if there is any file in hosted repo missing checksum, this will generate the checksum for them once requested.
I added the ContentMetaGenerator and found the usage of Generators scattered in different places. So I add a manager for them to align their behavior. One major change: in the past if the canProcess returns true, but the generate fails (return null), we ignore the other generators. In this pr, I don't only rely on canProcess but also the return value of generateFileContent. If this method returns null, we …
=> Generate missing checksum for hosted repo content

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/common/src/test/java/org/commonjava/indy/promote/data/PromotionManagerTest.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/HostedMetadataRemergedOnPathPromoteTest.java, subsys/infinispan/src/main/resources/infinispan.xml
This is to fix (NOS-1903) By-Path promotion doesn't merge maven-metadata.xml
This includes the test code in https://github.com/Commonjava/indy/pull/1272
To make it a real case, I add a pom file to A and B repo. Those pom files are necessary for generating metadata.xml. 
In order to compare metadata files, I have to groom them a bit. See details in the test case.
=> Fix by-Path promotion doesn't merge maven-metadata issue

core/src/main/java/org/commonjava/indy/core/expire/ScheduleManager.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/MetadataTimeoutTest.java
This is to fix NOS-1846 (Remote metadata expiration does not work correctly). 
I got the same test result as @pkocandr. Briefly, we find that the metadata.xml is cleaned correctly when it timeout. But if we retrieve it again, it will stay there forever. This is caused by scheduleEventLockCache. I see we put stuff in it but never clean them. Then the code checks it and returns/blocks the event propagation. 
The ftest in this PR shows the second time expiration check fails before the fix. 
This cache might have something to do with cluster but apparently, we have to leave out it for now. 
@ligangty might know more about it.
=> Fix remote metadata expiration regression

addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloContentAccessResource.java, addons/httprox/common/pom.xml, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyAcceptHandler.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyResponseWriter.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/util/HttpConduitWrapper.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/util/ProxyResponseHelper.java, addons/sli/jaxrs/pom.xml, addons/sli/jaxrs/src/main/java/org/commonjava/indy/sli/jaxrs/GoldenSignalsFilter.java, addons/sli/jaxrs/src/main/java/org/commonjava/indy/sli/jaxrs/GoldenSignalsFilterMapper.java, addons/sli/jaxrs/src/main/java/org/commonjava/indy/sli/jaxrs/SLIDeploymentProvider.java, addons/sli/jaxrs/src/main/java/org/commonjava/indy/sli/metrics/GoldenSignalsFunctionMetrics.java, addons/sli/jaxrs/src/main/java/org/commonjava/indy/sli/metrics/GoldenSignalsMetricSet.java, addons/sli/jaxrs/src/main/java/org/commonjava/indy/sli/metrics/GoldenSignalsMetricSetProvider.java, addons/sli/pom.xml, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java, embedder/pom.xml, pom.xml, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/MDCManager.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/RequestContextHelper.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/ResourceManagementFilter.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/ResponseUtils.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/RestInterceptor.java
This approach will use a servlet filter to wrap REST traffic and analyze it using previously
established metadata (currently added to the MDC, but eventually copied to ThreadContext).
Then this analysis will be used to classify the Indy function that the request accessed, and
log metrics by function. Metrics will be limited to latency, errors, and throughput. Saturation
will be measured separately for now...until we understand it better.
I still need to add the actual classification logic, and copy the classification information
from the MDC into the ThreadContext. Using MDC for anything except logging is kind of an ugly hack.
=> Implement 4 golden signals directly in Indy metrics

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/group/MavenMetadataMerger.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/HostedMetadataRemergedOnPathPromoteSnapshotTest.java, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractContentManagementTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/HostedMetadataMergeSnapshotTest.java
I found a problem when doing more test for snapshot metadata merging. Briefly, my new test failed and I get the new metadata when retrieving it. But I expect to get a merged one. 
This is because for some reason the promote begins with the pom file. When it is copied, it triggered the clean up of parent metadata (artifact level metadata.xml). Then the new artifact level metadata is copied and no existing file there ATM, so it is copied there. 
The main fix is at PromoteManager doPathTransfer() where I take special action for metadata. I.e., if the target is metadata, we just simply do not copy it (skip it). Furthermore, if the file exists we remove it and trigger clean-up in affected groups as well. 
With this fix, we leave out all metadata during the promotion. ie., we deal with it by 2 …
=> Fix byPath promotion metadata problem and add snapshot merging test

addons/changelog/common/src/main/java/org/commonjava/indy/changelog/DiffUtil.java, core/src/main/java/org/commonjava/indy/core/ctl/ContentController.java, core/src/test/java/org/commonjava/indy/core/ctl/ControllerTest.java
Port NOS-1910 fixe and one fix from Gang from the master.
=> Port fixes from master

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyMITMSSLServer.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyResponseWriter.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/util/ProxyMeter.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/util/ProxyResponseHelper.java
REST latency / request summary reporting happens when Indy logical execution is complete,
but BEFORE the content transfer is finished (this usually happens via a StreamingOutput
implementation, or is otherwise rendered as a string if it's not normal content.
In contrast, generic proxy latency is currently measured when the socket is closed,
which means it's after the content is completely transferred. This is a flawed conception
of latency, which is meant to measure the time it takes to START transferring content
back to the client.
This patch corrects the situation by reporting latency and the request summary in a
finally clause at the end of the ProxyResponseWriter.doHandleEvent() method, which is
only responsible for setting up a socket-close listener...not actually closing the socket. …
=> Fix httprox latency / request summary reporting

core/src/main/java/org/commonjava/indy/core/change/StoreContentListener.java, pom.xml
We have a race condition reported, and it's because we started processing the clearance of metadata files asynchronously on group membership change. We need to go back to using a process that waits for all files to be cleared appropriately before returning.
=> drain all pending clearPath() operations before returning from StoreContentListener

core/src/main/java/org/commonjava/indy/core/change/StoreContentListener.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/GroupMembershipAddMayDisruptMetadataRefreshTest.java
Also, adding a regression test to ensure this doesn't happen again.
=> Fix path-cleanup submit to drain service, not to executor service.

addons/httprox/ftests/pom.xml, addons/pkg-maven/common/pom.xml, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenContentsFilteringTransferDecorator.java, addons/pkg-maven/common/src/test/java/org/commonjava/indy/pkg/maven/content/MavenContentFilteringTransferDecoratorTest.java, addons/pkg-maven/common/src/test/java/org/commonjava/indy/pkg/maven/content/group/MavenMetadataMergerTest.java, addons/pkg-npm/common/pom.xml, addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/DecoratorUtils.java, addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/NPMPackageMaskingTransferDecorator.java, addons/pkg-npm/common/src/test/java/org/commonjava/indy/pkg/npm/content/DecoratorUtilsTest.java, addons/pkg-npm/common/src/test/java/org/commonjava/indy/pkg/npm/content/NPMPackageMaskingTransferDecoratorTest.java, addons/pkg-npm/common/src/test/java/org/commonjava/indy/pkg/npm/content/group/PackageMetadataMergerTest.java, addons/pkg-npm/common/src/test/resources/metadata/package-1-decorated.json, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMGroupContentMergeRetrieveTest.java, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMRemoteMetadataContentDecoratorTest.java, addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessHandler.java, addons/promote/common/src/test/java/org/commonjava/indy/promote/fixture/GalleyFixture.java, api/src/main/java/org/commonjava/indy/content/ContentManager.java, core/src/test/java/org/commonjava/indy/fixture/GalleyFixture.java, filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java, pom.xml, subsys/groovy/src/test/java/org/commonjava/indy/subsys/template/fixture/TestProvider.java, test/fixtures-core/pom.xml, test/fixtures-core/src/main/java/org/commonjava/indy/test/fixture/core/HttpTestFixture.java, test/fixtures-core/src/main/java/org/commonjava/indy/test/fixture/core/TestCacheProvider.java, test/fixtures-core/src/main/java/org/commonjava/indy/test/fixture/core/TestFileEventManager.java
This is for NOS-1907 - NPM metadata should replace tarball urls with Indy ones. I implement it via NPM PackageMaskingTransferDecorator. 
This PR also move ContentsFilteringTransfer (and test code about it) from Galley to Indy. 
This depends on https://github.com/Commonjava/galley/pull/282
=> Apply maven ContentsFilteringTransfer and NPM PackageMaskingTransfer decorators

addons/httprox/ftests/pom.xml, addons/pkg-maven/common/pom.xml, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenContentsFilteringTransferDecorator.java, addons/pkg-maven/common/src/test/java/org/commonjava/indy/pkg/maven/content/MavenContentFilteringTransferDecoratorTest.java, addons/pkg-maven/common/src/test/java/org/commonjava/indy/pkg/maven/content/group/MavenMetadataMergerTest.java, addons/pkg-npm/common/pom.xml, addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/DecoratorUtils.java, addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/NPMPackageMaskingTransferDecorator.java, addons/pkg-npm/common/src/test/java/org/commonjava/indy/pkg/npm/content/DecoratorUtilsTest.java, addons/pkg-npm/common/src/test/java/org/commonjava/indy/pkg/npm/content/NPMPackageMaskingTransferDecoratorTest.java, addons/pkg-npm/common/src/test/java/org/commonjava/indy/pkg/npm/content/group/PackageMetadataMergerTest.java, addons/pkg-npm/common/src/test/resources/metadata/package-1-decorated.json, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMGroupContentMergeRetrieveTest.java, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMRemoteMetadataContentDecoratorTest.java, addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessHandler.java, addons/promote/common/src/test/java/org/commonjava/indy/promote/fixture/GalleyFixture.java, api/src/main/java/org/commonjava/indy/content/ContentManager.java, core/src/test/java/org/commonjava/indy/fixture/GalleyFixture.java, filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java, pom.xml, subsys/groovy/src/test/java/org/commonjava/indy/subsys/template/fixture/TestProvider.java, test/fixtures-core/pom.xml, test/fixtures-core/src/main/java/org/commonjava/indy/test/fixture/core/HttpTestFixture.java, test/fixtures-core/src/main/java/org/commonjava/indy/test/fixture/core/TestCacheProvider.java, test/fixtures-core/src/main/java/org/commonjava/indy/test/fixture/core/TestFileEventManager.java
This is a fix for NPM support that should allow us to continue testing the new package type under real-world conditions. It was already merged to master.
=> [1.8.x] Apply maven ContentsFilteringTransfer and NPM PackageMaskingTransfer decorators

addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloContentAccessResource.java
Because of this missing, seems that all folo content rest access is not processed by the RestInterceptor, which means that the needed mdc info for sli tracing is missed now.
=> Add missing @REST annotation for folo content rest endpoint

addons/diagnostics/client-java/src/main/java/org/commonjava/indy/diag/client/IndyDiagnosticsClientModule.java, clients/core-java/src/main/java/org/commonjava/indy/client/core/Indy.java, clients/core-java/src/main/java/org/commonjava/indy/client/core/IndyClientHttp.java, pom.xml, subsys/http/src/main/java/org/commonjava/indy/subsys/http/IndyHttpProvider.java
This will forcibly close the connection manager and all connections when the client is closed.
This depends on https://github.com/Commonjava/jhttpc/pull/38.
=> use new shutdownNow() method when Indy client API is closed

addons/folo/common/src/main/java/org/commonjava/indy/folo/change/FoloExpirationWarningListener.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCache.java, deployments/pom.xml, deployments/record-extractor/pom.xml, deployments/record-extractor/src/main/java/org/commonjava/indy/tools/folo/record/ExtractOptions.java, deployments/record-extractor/src/main/java/org/commonjava/indy/tools/folo/record/Main.java
This will help us debug problems where really long-running builds end up with content missing from their sealed tracking record.
Also, adding a very small client that can deserialize and export a tracking record backup file to JSON.
=> Add a log warning when folo-in-progress expires an entry

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/util/HttpConduitWrapper.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/util/ProxyMeter.java, addons/sli/jaxrs/src/main/java/org/commonjava/indy/sli/jaxrs/GoldenSignalsFilter.java, addons/sli/jaxrs/src/main/java/org/commonjava/indy/sli/metrics/GoldenSignalsFunctionMetrics.java, core/src/main/java/org/commonjava/indy/core/ctl/ContentController.java, models/core-java/src/main/java/org/commonjava/indy/IndyRequestConstants.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/RequestContextHelper.java
This also means that we have to classify traffic without the benefit of ThreadContext
variables, or the path parameters we would normally get from the REST endpoint classes.
=> Record load metric up front when request starts

addons/sli/jaxrs/src/main/java/org/commonjava/indy/sli/jaxrs/GoldenSignalsFilter.java, addons/sli/jaxrs/src/main/java/org/commonjava/indy/sli/jaxrs/GoldenSignalsFilterMapper.java, addons/sli/jaxrs/src/test/java/org/commonjava/indy/sli/jaxrs/GoldenSignalsFilterTest.java
Today when I was doing testing with fake sli error endpoint of the new merged code, I found that all metadata sli is not reporting. After checking code I found some issues, so this PR is the fixing.
=> Fix path parsing for metadata checking of sli filter

addons/folo/client-java/src/main/java/org/commonjava/indy/folo/client/IndyFoloContentClientModule.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/change/FoloTrackingListener.java, addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/content/AbstractNPMFoloContentManagementTest.java, addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/content/DownloadFromTrackedNPMRemoteRepoTest.java, addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/content/DownloadFromTrackedRemoteRepoTest.java, addons/folo/ftests/src/main/resources/folo-content/simple.json, addons/folo/jaxrs/pom.xml, addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloContentAccessResource.java, addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloMavenContentAccessResource.java, addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloNPMContentAccessResource.java, models/core-java/src/main/java/org/commonjava/indy/model/core/AccessChannel.java
NPM content retrieving has its own logic now, but current folo service does not use it yet for npm cases. So this pr fix it by adding a new folo resource for npm cases.
=> Fix wrong handling of npm content retrieving through folo service

addons/content-browse/jaxrs/src/main/java/org/commonjava/indy/content/browse/bind/jaxrs/ContentBrowseResource.java, addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/DeprecatedFoloContentAccessResource.java, addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloAdminResource.java, addons/hosted-by-archive/jaxrs/src/main/java/org/commonjava/indy/hostedbyarc/bind/jaxrs/IndyHostedByArchiveResource.java, addons/koji/jaxrs/src/main/java/org/commonjava/indy/koji/bind/jaxrs/KojiRepairResource.java, addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessHandler.java, addons/promote/jaxrs/src/main/java/org/commonjava/indy/promote/bind/jaxrs/PromoteResource.java, addons/revisions/jaxrs/src/main/java/org/commonjava/indy/revisions/jaxrs/ChangelogResource.java, addons/revisions/jaxrs/src/main/java/org/commonjava/indy/revisions/jaxrs/RevisionsAdminResource.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/DeprecatedContentAccessResource.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/NfcResource.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/RootResource.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/admin/DeprecatedStoreAdminHandler.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/admin/MaintenanceHandler.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/admin/ReplicationHandler.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/admin/SchedulerHandler.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/admin/StoreAdminHandler.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/stats/StatsHandler.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/jaxrs/VersioningTestHandler.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/jaxrs/VersioningTestHandlerDeprecated.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/keycloak/SecurityResource.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/DTOStreamingOutput.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/ResponseHelper.java
This uses a form of StreamingOutput as a response entity in order to avoid measuring rendering / transfer times for DTOs in with latency, since these are not logical functions.
In the process, I've added logic to wrap DTO rendering / streaming with metrics for this process as well, in case we need it for diagnosis. This required switching ResponseUtils to a helper class, ResponseHelper, which is CDI injected into REST resources.
=> Switch to StreamingOutput impl for DTO rendering

addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloNPMContentAccessResource.java, addons/sli/jaxrs/src/main/java/org/commonjava/indy/sli/jaxrs/GoldenSignalsFilter.java, models/core-java/src/main/java/org/commonjava/indy/pkg/PackageTypeConstants.java
When replace tarball urls with indy context path, seems package type missed which caused a NPE in GoldenSignalsFilter.
=> Fix: missed package type for replacing npm tarball urls

models/core-java/src/main/java/org/commonjava/indy/model/core/RemoteRepository.java
Seems it is not a very critical problem which will break indy, so downgrade it for easy filter in Kibana
=> Downgrade one logger for remote repo url parsing to WARN level

addons/folo/common/src/main/java/org/commonjava/indy/folo/ctl/FoloAdminController.java, addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloMavenContentAccessResource.java, addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloNPMContentAccessResource.java, addons/folo/model-java/src/main/java/org/commonjava/indy/folo/dto/TrackedContentEntryDTO.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyAcceptHandler.java, models/core-java/src/main/java/org/commonjava/indy/model/core/AccessChannel.java
This switches usages of the new AccessChannel.NPM_REPO to use AccessChannel.NATIVE (to distinguish generic proxy use from 'native' REST interface use. It deprecates the old MAVEN_REPO value, and
switches the Maven tracking implementation to use NATIVE too...but it leaves MAVEN_REPO in place for historical reasons.
Automatically convert MAVEN_REPO AccessChannel to NATIVE in tracking report entry DTOs
=> Add NATIVE AccessChannel, remove NPM, deprecate MAVEN

Jenkinsfile
This pipeline is to push docker images to Quay.io (via Openshift builder). Briefly, it triggers an Openshift build and the latter build and push the image to the remote registry.
=> Add docker image build in Jenkinsfile

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/change/MetadataMergePomChangeListener.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/HostedMetadataRemergedOnPathPromoteToReadonlyHostedTest.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java, embedder/src/it/resources/logback.xml, embedder/src/test/resources/logback-test.xml
Found that the metadata not update issue happened on a readonly hosted target. It is caused by not set IGNORE_READONLY for this type of resource. And add a new ftest here to show the case.
=> Fix: Metadata refreshing after promotion for readonly hosted target

core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java
Seems we have bunch of useless transfer getting log from hosted repo.
We need to reduce them by checking only hit transfer getting.
=> Optimize logging for transfer getting

Jenkinsfile, addons/content-browse/ftests/src/main/java/org/commonjava/indy/content/browse/ftest/MetaListingRescheduleTimeoutTest.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenContentsFilteringTransferDecorator.java, addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/NPMPackageMaskingTransferDecorator.java, api/src/main/java/org/commonjava/indy/conf/InternalFeatureConfig.java, api/src/main/java/org/commonjava/indy/conf/SslValidationConfig.java, api/src/main/java/org/commonjava/indy/data/StoreValidator.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/util/TransferCountingInputStream.java, core/pom.xml, core/src/main/conf/conf.d/internal-features.conf, core/src/main/java/org/commonjava/indy/core/data/StoreDataSetupAction.java, core/src/main/java/org/commonjava/indy/data/DefaultStoreValidator.java, core/src/main/resources/default-internal-features.conf, core/src/main/resources/default-main.conf, db/common/src/main/java/org/commonjava/indy/db/common/AbstractStoreDataManager.java, filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java, filers/default/src/main/java/org/commonjava/indy/filer/def/IOLatencyDecorator.java, filers/default/src/main/java/org/commonjava/indy/filer/def/TimingInputStream.java, filers/default/src/main/java/org/commonjava/indy/filer/def/TimingOutputStream.java, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java, ftests/core/src/main/java/org/commonjava/indy/data/DefaultStoreValidatorTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/EmptyDisabledTimeoutsMapRetrievalTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RemoteRepoTimeoutDisablesStoreAndRetreiveTimeoutScheduleTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RemoteRepoTimeoutDisablesStoreAndShowsInDisabledTimeoutsMapTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RemoteRepoTimeoutDisablesThenReEnabledTest.java, ftests/core/src/main/java/org/commonjava/indy/jaxrs/IndySslValidationApiTest.java, pom.xml, subsys/http/src/main/java/org/commonjava/indy/subsys/http/util/HttpResources.java
NOS-2084 -> NPM repositories cannot be enabled .
Problem was that:
1. By default value of config "remote.ssl.required" was "true" and all new created remote repositories were validated based on rule for SSL needed.  solve = value changed to "false"
2. In "store" method from class "AbstractStoreDataManager" there was left out checking of config value "remote.ssl.required" and that caused all new created repos to be validated. solve = implemented if-else branch for checking config value and executing that logic only if provided config value is set to "true"
= New Test for creating "NPM"  remote repositories are added and also testing for non-ssl remote maven repo which for some reason was not disabled in previous "dev" indy environment ( test are ok and non-ssl maven repo is disabled based …
=> Fixing issue nos-2084 for disabling npm remote repository

pom.xml
This needs to be tested in an environment to make sure it's safe.
=> rollback Infinispan version to 9.4.15.Final (still a net upgrade from Indy 1.9.4)

addons/content-index/src/main/conf/conf.d/content-index.conf, addons/content-index/src/main/java/org/commonjava/indy/content/index/DefaultContentIndexManager.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/conf/ContentIndexConfig.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/conf/HostedContentIndexRescanManager.java, addons/content-index/src/main/resources/default-content-index.conf, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, embedder/pom.xml, embedder/src/test/resources/logback-test.xml, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/HostedContentIndexRescanTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RepositoryPathMaskMetadataTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/AuthoritativeIndexedContentInHostedTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/AuthoritativeIndexedContentInRemoteTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/ContentIndexDirLvWithArtifactsTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/ContentIndexDirLvWithMetadataTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/ContentIndexGroupUsageTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/ContentIndexNestedGroupAndStoreDeletionTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/ContentIndexRemoteRepoUsageTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/HostedAuthIndexWithReadonly.java, pom.xml, subsys/metrics/pom.xml, subsys/metrics/prometheus/pom.xml, subsys/metrics/prometheus/src/main/java/org/commonjava/indy/metrics/prometheus/PrometheusDeployment.java
Adding Dropwizard Metrics adapter to publish metrics to Prometheus via servlet, since our perf-test instance can't deploy GraphiteDB to a pod. This gets us ready for Prometheus anyway.
We may not need content indexing anymore in our particular deployment environment, and it might actually be hurting performance for our use case. Adding an option to disable it via config.
=> Allow disable of content index, and add prometheus metrics adapter

addons/implied-repos/common/src/main/java/org/commonjava/indy/implrepo/change/ImpliedRepositoryDetector.java, addons/implied-repos/ftests/src/main/java/org/commonjava/indy/implrepo/skim/ReuseExistingRepoIntoConfiguredGroupTest.java
Patch for https://projects.engineering.redhat.com/browse/NOSSUP-110
=> Reuse the existing repo as implied one should add it into group

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, bin/test-setup.sh, embedder/pom.xml, filers/default/pom.xml, filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java, filers/default/src/main/java/org/commonjava/indy/filer/def/conf/DefaultStorageProviderConfiguration.java, ftests/common/pom.xml, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java, pom.xml
I created a branch "master-integration-pathmap" for the integration. 
This is the first PR. With this one, you can build Indy and run bin/test-setup.sh with a local Cassandra (yum install cassandra cassandra-server; systemctl start cassandra). 
I am struggling with the ftests. It seems the cassandra unit bring some conflicts to io.netty dependency. But if you don't care about ftests, this works well. I was able to build some small projects (like partyline, weft) against this integrated Indy instance. 
Have fun playing with it!
=> Integrate with pathmapped storage

ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractContentManagementTest.java, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/AbstractContentTimeoutWorkingTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/AbstractMetadataTimeoutWorkingTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/CacheFirstTimeoutWorkingTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/MetadataFirstTimeoutWorkingTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/MetadataPassthroughTimeoutWorkingTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/MetadataTimeoutTest.java
Check physical file existence by hashed dir and file.
=> Fix ftest about how to check storage file existence

Jenkinsfile, addons/folo/common/src/main/java/org/commonjava/indy/folo/ctl/FoloAdminController.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCache.java, addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/content/DuplicateStoreAndVerifyTrackedRecordTest.java, addons/folo/model-java/src/main/java/org/commonjava/indy/folo/dto/TrackedContentEntryDTO.java, addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/TrackedContentEntry.java, addons/folo/model-java/src/test/java/org/commonjava/indy/folo/model/TrackedContentEntryTest.java, addons/folo/model-java/src/test/java/org/commonjava/indy/folo/model/TrackedContentEntryV2.java
We're missing information about how many times a given file is accessed during a build, and what the time distribution looks like between file accesses. This isn't needed for normal production use cases, but having it will give us a much better ability to simulate build users without actually running builds. With the timing information, we can sort the download / upload lists into a single "script" of artifact accesses and sizes, the replay it in a simulated environment.
We'll need more tracking information on the metadata files that get used during build alignment, but this is a step in the right direction.
Also, in the Jenkinsfile I'm making artifact deployment conditional on having an image build configuration available. This will limit CI scenarios that build for non-Commonjava forks …
=> Refine deployment from Jenkinsfile, add timestamps for access in Folo tracked entries

clients/core-java/src/main/java/org/commonjava/indy/client/core/module/IndyContentClientModule.java, models/core-java/src/main/java/org/commonjava/indy/model/core/dto/DirectoryListingDTO.java
These methods & classes are totally not working now. If we will not switch back to the old way of content-listing again, I suggest to remove them in next release.
=> Deprecated listContents in client module as it is not working now

addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/GroupMetadataFileDeletionTest.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java, embedder/pom.xml, embedder/src/cassandra/cql/load.cql, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractContentManagementTest.java, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/ContentDeletionMayDisruptGroupMetadataTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/GroupHttpHeadersFromSameRepoWhenNotInPathMaskTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/GroupMetadataMergeInfoGenTest.java
This pr abandon the embedded Cassandra server because those servers conflict with each other on file system. I move to cassandra-maven-plugin that is started up before ftests. All ftests use different keyspace to separate from others.
=> Apply cassandra-maven-plugin for ftests

addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/GroupMetadataFileDeletionTest.java, filers/default/pom.xml, filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java, filers/default/src/main/java/org/commonjava/indy/filer/def/conf/DefaultStorageProviderConfiguration.java, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractContentManagementTest.java, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java, pom.xml, subsys/cassandra/pom.xml, subsys/cassandra/src/main/conf/conf.d/cassandra.conf, subsys/cassandra/src/main/java/org/commonjava/indy/subsys/cassandra/CassandraClient.java, subsys/cassandra/src/main/java/org/commonjava/indy/subsys/cassandra/config/CassandraConfig.java, subsys/cassandra/src/main/resources/META-INF/beans.xml, subsys/cassandra/src/main/resources/default-cassandra.conf, subsys/pom.xml
This pr adds a subsystem/cassandra and separates the connection config from the storage section. So far it only contains a config object. But we might use cassandra for other purposes in the future.
=> Add subsys/cassandra for general connection settings

deployments/pathmap-migrator/README.md, deployments/pathmap-migrator/pom.xml, deployments/pathmap-migrator/src/main/java/org/commonjava/indy/pathmap/migrate/CassandraMigrator.java, deployments/pathmap-migrator/src/main/java/org/commonjava/indy/pathmap/migrate/Command.java, deployments/pathmap-migrator/src/main/java/org/commonjava/indy/pathmap/migrate/IndyStoreBasedPathGenerator.java, deployments/pathmap-migrator/src/main/java/org/commonjava/indy/pathmap/migrate/Main.java, deployments/pathmap-migrator/src/main/java/org/commonjava/indy/pathmap/migrate/MigrateCmd.java, deployments/pathmap-migrator/src/main/java/org/commonjava/indy/pathmap/migrate/MigrateException.java, deployments/pathmap-migrator/src/main/java/org/commonjava/indy/pathmap/migrate/MigrateOptions.java, deployments/pathmap-migrator/src/main/java/org/commonjava/indy/pathmap/migrate/ScanCmd.java, deployments/pathmap-migrator/src/main/java/org/commonjava/indy/pathmap/migrate/Util.java, deployments/pathmap-migrator/src/test/java/org/commonjava/indy/pathmap/migrate/IndyStoreBasedPhysicalPathGeneratorTest.java, deployments/pom.xml
This is a draft pr for the path mapped migrator. This migrator has two commands:
* scan: will scan the storage folder for all file paths, and records them to files by batch to a work dir
* migrate: will read all paths from files in work dir, and generate path mapped records into db storage
I've only tested "scan" command on a test storage with 10+ million paths with batch 50000 for a file, and it
will take about 30 mins to finish. I did not test the "migrate" command because I did not setup a local cassandra 
instance successfully yet. I'll try to do that later.
Now all commands are working in single thread mode, maybe we can try to multi-thread them later if performance is unacceptable.
=> Start path map storage migrator

deployments/pathmap-migrator/src/main/java/org/commonjava/indy/pathmap/migrate/CassandraMigrator.java, deployments/pathmap-migrator/src/main/java/org/commonjava/indy/pathmap/migrate/MigrateCmd.java, deployments/pathmap-migrator/src/main/java/org/commonjava/indy/pathmap/migrate/MigrateOptions.java, deployments/pathmap-migrator/src/test/java/org/commonjava/indy/pathmap/migrate/ChecksumCalculatorTest.java
I tested the new migrator. It has two problems. 1. The checksum is always the same so all the records are thrown to reclaim table. 2. It does not stop after done. 
This pr fix the #1 issue. 
I try to fix #2 by stop a timer. But not tested. I will test it soon.
=> Fix the path mapped migrator checksum issue

addons/folo/model-java/src/test/java/org/commonjava/indy/folo/model/TrackedContentEntryTest.java
Sometimes this test failed and the timestamp of entry and test is different (e.g., a millisecond difference). This is due to the way the timestamp was set (currentTimeMillis) and there is a gap between those two objects' creation.
=> Fix TrackedContentEntryTest

Jenkinsfile
The tarball_url is not a built-in variable but calculated in this script.
=> Fix groovy.lang.MissingPropertyException: No such property: tarball_url

deployments/pathmap-migrator/src/main/java/org/commonjava/indy/pathmap/migrate/MigrateCmd.java
This should be able to fix the migrator not exit issue.
=> [migration-tool] shutdown pathDB after done

deployments/pathmap-migrator/README.md, deployments/pathmap-migrator/src/main/java/org/commonjava/indy/pathmap/migrate/MigrateOptions.java, deployments/pathmap-migrator/src/main/java/org/commonjava/indy/pathmap/migrate/ScanCmd.java, deployments/pathmap-migrator/src/main/java/org/commonjava/indy/pathmap/migrate/Util.java
To use, add "-f" during scan mode. One example to filter http-metadata.json is:
-f .*http-metadata.json
=> Add filter to filter out the files not need to migrate

addons/path-mapped/common/pom.xml, addons/path-mapped/common/src/main/java/org/commonjava/indy/pathmapped/common/PathMappedController.java, addons/path-mapped/common/src/main/resources/META-INF/beans.xml, addons/path-mapped/jaxrs/pom.xml, addons/path-mapped/jaxrs/src/main/java/org/commonjava/indy/pathmapped/jaxrs/PathMappedResource.java, addons/path-mapped/jaxrs/src/main/resources/META-INF/beans.xml, addons/path-mapped/model-java/pom.xml, addons/path-mapped/model-java/src/main/java/org/commonjava/indy/pathmapped/model/PathMappedDeleteResult.java, addons/path-mapped/model-java/src/main/java/org/commonjava/indy/pathmapped/model/PathMappedListResult.java, addons/path-mapped/pom.xml, embedder/pom.xml, filers/default/src/main/java/org/commonjava/indy/filer/def/conf/DefaultStorageProviderConfiguration.java, pom.xml, subsys/cassandra/src/main/conf/conf.d/cassandra.conf, subsys/cassandra/src/main/resources/default-cassandra.conf
Add-on for the direct list, get and delete path-mapped files. It mainly for the maintenance, e.g, remove a stale metadata.xml, etc. 
This add-on provides below REST endpoints under "/api/admin/pathmapped".
1. list, "browse/{packageType}/{type: (hosted|group|remote)}/{name}/{path: (.*)}?recursive=true/false". If recursive is true, it lists all paths recursively. Default is false (meaning to list the direct children).
2. get/delete, "content/{packageType}/{type: (hosted|group|remote)}/{name}".
=> Addon path-mapped to provide direct listing/get/delete operations

models/core-java/src/main/java/org/commonjava/indy/model/core/AbstractRepository.java, models/core-java/src/main/java/org/commonjava/indy/model/core/ArtifactStore.java, models/core-java/src/main/java/org/commonjava/indy/model/core/Group.java, models/core-java/src/main/java/org/commonjava/indy/model/core/RemoteRepository.java
Seems there is no creation time for all of our current repos. I think
it is useful for tracking, especially for the auto-created repos like
koji-proxy and implied repos.
BTW, I'm also thinking if we also need to add the "last_update_time"
for all repos.
=> Add creation time for all repos

db/infinispan/src/main/java/org/commonjava/indy/infinispan/data/InfinispanStoreDataManager.java, db/infinispan/src/main/java/org/commonjava/indy/infinispan/data/InfinispanStoreDataMigrationAction.java, db/infinispan/src/main/java/org/commonjava/indy/infinispan/data/StoreDataCacheProducer.java, models/core-java/src/main/java/org/commonjava/indy/model/core/AbstractRepository.java, models/core-java/src/main/java/org/commonjava/indy/model/core/ArtifactStore.java, models/core-java/src/main/java/org/commonjava/indy/model/core/Group.java, models/core-java/src/main/java/org/commonjava/indy/model/core/HostedRepository.java, models/core-java/src/main/java/org/commonjava/indy/model/core/RemoteRepository.java, models/core-java/src/main/java/org/commonjava/indy/model/core/StoreKey.java, models/core-java/src/test/java/org/commonjava/indy/model/core/GroupSerializationTest.java, models/core-java/src/test/java/org/commonjava/indy/model/core/HostedRepositorySerializationTest.java, models/core-java/src/test/java/org/commonjava/indy/model/core/MixedStoreSerializationTest.java, models/core-java/src/test/java/org/commonjava/indy/model/core/RemoteRepositorySerializationTest.java, subsys/infinispan/src/main/resources/infinispan.xml
Counter-proposal to #1454 .
Previously, storing `ArtifactStore` definitions as JSON requires us to serialize/deserialize (render and parse) constantly, every time we access a repository definition. We can access dozens or even thousands of these in a request, especially in an upload request or a promotion request.
Looking at our current production deployment, we see that upload latency is up around 7 seconds at times, with about 6.98 seconds of that being consumed in the process of working with the store-definition cache.
This change implements Externalizable for all `ArtifactStore` derivatives, `StoreKey`, and related classes in the core model of Indy. It adds some testing to ensure these can be read / written appropriately using readExternal / writeExternal methods, and verifies that …
=> Switch to using Externalizable/ArtifactStore for InfinispanStoreDataManager

api/src/main/java/org/commonjava/indy/metrics/RequestContextHelper.java, models/core-java/src/main/java/org/commonjava/indy/model/core/ArtifactStore.java, models/core-java/src/main/java/org/commonjava/indy/model/core/Group.java, models/core-java/src/test/java/org/commonjava/indy/model/core/GroupSerializationTest.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/ResourceManagementFilter.java, subsys/metrics/reporter/src/main/java/org/commonjava/indy/metrics/IndyMetricsManager.java, subsys/metrics/reporter/src/main/java/org/commonjava/indy/metrics/conf/IndyMetricsConfig.java, subsys/metrics/reporter/src/main/java/org/commonjava/indy/metrics/jaxrs/interceptor/MetricsInterceptor.java
Adding cumulative call counts alongside cumulative timings, in the logging MDC. These will be logged at the end of each REST call, via the ResourceManagementFilter. We may need to do something similar for generic proxy requests, but it's not done yet.
Also, because metering latency is starting to become a bit of a concern with all the low-level metrics around file I/O, I've added configuration to allow us to specify a metering ratio, which by default will be 1:1. We can set this higher to sample 1/1, 1/10, 1/100, 1/1000 requests. This will modulo a random integer by the ratio to see if the result is zero, which should give us a sampling pattern that matches the desired ratio. This will apply the ratio to ALL requests evenly, regardless of the destination function being called.
=> Cumulative call count in logging MDC and metering ratio

db/infinispan/src/main/java/org/commonjava/indy/infinispan/data/InfinispanStoreDataMigrationAction.java, db/infinispan/src/main/java/org/commonjava/indy/infinispan/data/StoreDataCacheProducer.java
I found a problem for migration process. When we use db-based
persistence for store cache, we can not control the table name for which
store use by applying a simple "table-name" like attr in ispn xml
because it does not support this. The table name is applied by its cache
name directly. So we need to use a new cache name for the new obj-based
store, ane use the legacy "store-data" cache for migration purpose.
=> Using store-data-v1 for new object-based store-data cache

db/common/src/main/java/org/commonjava/indy/db/common/DefaultArtifactStoreQuery.java
Seems the new refactored code brings some new way to get affected
groups, but it missed some NPE check which caused 500 error.
=> FIX: NPE happened during getAffectedBy

addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexCacheProducer.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/deindex/DeIndexHandlingCache.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/deindex/DeIndexHandlingCacheListener.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/deindex/DeIndexInfo.java, subsys/infinispan/src/main/resources/infinispan.xml
Recent performance problem we met for uploading & promotion is all caused by the getAffectedBy operation, which is a time-consumed one for a full scan on store data. After checking, I found that it is mainly used for de-index or re-index content-index entries for the uploading repo. I think this de-index will not be a block factor during the upload or promotion process, which means we could make it async. This pr is doing this fix.
In this pr, I created a ISPN cache and used it like a queue, which decouple the de-index opeartion from storing process in content-index to an aync listener of ISPN listener.
Why not use a weft executor? Because the storing operation is high frequent, which means it could be blocked again if the de-index effeciency is much slower than the real physical storing …
=> Async the group de-index during upload in content-index service

deployments/pom.xml
These don't need to be on the main release cycle, and it seems there's some recursion
problem in the maven-assembly-plugin with one of them that's screwing up Indy builds.
=> don't build cache migrator or record extractor in main build.

addons/content-index/src/main/java/org/commonjava/indy/content/index/DefaultContentIndexManager.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionHelper.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, subsys/metrics/reporter/src/main/java/org/commonjava/indy/metrics/IndyMetricsManager.java
This pr focus on thread-off of two nfc cleaning ops in ContentManager and Promotion validation. These ops are all refering getGroupsAffectedBy, which is a time-consuming calling. As these ops are in the process of file storing, they are affecting the upload performance. And these nfc cleaning ops can be considered as non-real-time, which means thread-off is acceptable.
=> Thread-off two nfc cleaning ops which refers getAffectedBy

api/src/main/java/org/commonjava/indy/data/StoreDataManager.java, db/common/src/main/java/org/commonjava/indy/db/common/AbstractStoreDataManager.java, db/common/src/main/java/org/commonjava/indy/db/common/DefaultArtifactStoreQuery.java, db/infinispan/src/main/java/org/commonjava/indy/infinispan/data/InfinispanStoreDataManager.java, db/infinispan/src/main/java/org/commonjava/indy/infinispan/data/StoreByPkgCache.java, db/infinispan/src/main/java/org/commonjava/indy/infinispan/data/StoreDataCacheProducer.java, db/infinispan/src/test/src/org/commonjava/indy/infinispan/data/InfinispanTCKFixtureProvider.java, subsys/infinispan/src/main/resources/infinispan.xml
Add a new Cache which is <package, Map<type, Set<StoreKey>> to storeall Store keys based on package and type, so for affected group get method, we can avoid the full scan on all repos to get groups, but just simplified to two map get ops.
=> Limit "affected-by" with full scan opeartion in package type based set

addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessHandler.java, api/src/main/java/org/commonjava/indy/data/StoreDataManager.java, db/common/src/main/java/org/commonjava/indy/db/common/AbstractStoreDataManager.java, db/common/src/main/java/org/commonjava/indy/db/common/DefaultArtifactStoreQuery.java, db/common/src/main/java/org/commonjava/indy/db/common/StoreUpdateAction.java, db/infinispan/src/main/java/org/commonjava/indy/infinispan/data/AffectedByStoreCache.java, db/infinispan/src/main/java/org/commonjava/indy/infinispan/data/InfinispanStoreDataManager.java, db/infinispan/src/main/java/org/commonjava/indy/infinispan/data/StoreDataCacheProducer.java, db/infinispan/src/test/src/org/commonjava/indy/infinispan/data/InfinispanTCKFixtureProvider.java, ftests/core/src/main/java/org/commonjava/indy/jaxrs/IndySslValidationApiTest.java, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/BasicCacheHandle.java, subsys/infinispan/src/main/resources/infinispan.xml
This supercedes #1470 by extending the work there and simplifying the mapping represented in the affected-by cache to be a simple reverse-map of the group-to-constituent map contained in the Group definition. This will simplify updates to the cache and should make it perform a bit better, while also avoiding potential unforseen bugs when using multiple levels of group constituent nesting (groups within groups while also containing repos). If something in the middle of such a chain gets updated, recalculating a fully flattened affected-by mapping could become error prone and would definitely be expensive.
The new code simply stores a reverse map of the constituent mapping, aggregated for all groups. When the affectedBy() method is called, this reverse map is iterated using processed / …
=> Implement affected-by reverse cache

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/change/MetadataMergePomChangeListener.java
I think these logs can help us check which pom file updating triggered the metadata file clearing, which should happen in promotion process for refreshing the metadata.
=> Add some trace log for metadata clearing of pom update

addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/NFCContentListener.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, api/src/main/java/org/commonjava/indy/data/StoreDataManager.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, db/common/src/main/java/org/commonjava/indy/db/common/AbstractStoreDataManager.java, db/infinispan/src/main/java/org/commonjava/indy/infinispan/data/InfinispanStoreDataManager.java
We've used multiple threads to async the ops which are referring getGroupsAffectedBy. It's not easy to manage and refactor in the future, so this pr consolidate all these ops into single thread which is managed in StoreDataManager itself.
=> Consolidate all async getGroupAffectedBy ops in StoreDataManager

bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/admin/MaintenanceHandler.java, core/src/main/java/org/commonjava/indy/core/ctl/IspnCacheController.java
This PR add a few endpoints for debugging store related issues. It does:
1. Get the affected-by for a repo, e.g., /api/admin/maint/store/affected/maven:remote:central
2. Expose ISPN cache content ( or entry given the key ). e.g.,
/api/admin/maint/infinispan/cache/affected-by-stores
/api/admin/maint/infinispan/cache/store-data/maven:group:public
3. Forbid a dangerous clean cache endpoint ( that was added when most caches were disposable but now it is really a risk )
=> Add maint endpoint to expose ispn cache/entry and affectedby result

filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java, filers/default/src/main/java/org/commonjava/indy/filer/def/LegacyReadonlyPhysicalStore.java
This will prevent legacy files from being deleted. 
Basically we have two ways to handle deletion for legacy files. One is to delay the deletion (turn on GC later, all to-be-deleted files are in db). The other is not to delete them at all ( this PR ). I am not sure which is better and open to suggestion.
=> Not delete read-only legacy files

api/src/main/java/org/commonjava/indy/conf/DefaultIndyConfiguration.java, api/src/main/java/org/commonjava/indy/conf/IndyConfiguration.java, core/pom.xml, core/src/main/java/org/commonjava/indy/core/inject/AbstractNotFoundCache.java, core/src/main/java/org/commonjava/indy/core/inject/CassandraNotFoundCache.java, core/src/main/java/org/commonjava/indy/core/inject/ExpiringMemoryNotFoundCache.java, core/src/main/java/org/commonjava/indy/core/inject/IspnNotFoundCache.java, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/NFCGetMissingAndPaginationTest.java
Use Cassandra for NFC. This is what I mentioned early about Cassandra as clustering caches. With this approach, we got both good query support, TTL (expiration), easy clustering (Indy nodes query db independently, and db as the only source of truth). 
NFC is a simple cache. I use it as the first step forward.
=> Add CassandraNotFoundCache

subsys/cassandra/src/main/java/org/commonjava/indy/subsys/cassandra/CassandraClient.java, subsys/honeycomb/src/main/java/org/commonjava/indy/subsys/honeycomb/HoneycombFilter.java, subsys/honeycomb/src/main/java/org/commonjava/indy/subsys/honeycomb/HoneycombManager.java, subsys/honeycomb/src/main/java/org/commonjava/indy/subsys/honeycomb/IndyTraceSampler.java, subsys/honeycomb/src/main/java/org/commonjava/indy/subsys/honeycomb/IndyTracingContext.java, subsys/honeycomb/src/main/java/org/commonjava/indy/subsys/honeycomb/interceptor/HoneycombWrapperInterceptor.java
I find tons of Honeycomb info level messages in indy.log. Might be better to lower it to debug.
=> Lower the log level from info to debug in Honeycomb interceptor

addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/NFCContentListener.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, api/src/main/java/org/commonjava/indy/data/StoreDataManager.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, db/common/src/main/java/org/commonjava/indy/db/common/AbstractStoreDataManager.java
Currently we consolidated all "store affected by" async tasks to run
in one single entry point in AbstractStoreDataManager for easy
management, but it brings a problem for debugging: for thread dump, we
don't know the thread context for which task. So in this pr, we use
thread name that contains some context info for the task for easy
tracing.
=> Re-name threads in store-affected-by-async-runner pool

core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java
We should allow us to delete metadata from hosted repo like pnc-builds where sometimes the metadata is broken. This PR uses the ignore_readonly logic in DefaultDownloadManager "doDelete( final Transfer item, final EventMetadata eventMetadata )".
=> Allow deletion of hosted metadata

uis/layover/app/js/controllers.js, uis/layover/app/partials/cache-delete.html
Because we might use it for NPM metadata too.
=> Update delete cache ui to leave out maven specific msg

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenContentsFilteringTransferDecorator.java, addons/pkg-maven/common/src/test/java/org/commonjava/indy/pkg/maven/content/MavenContentFilteringTransferDecoratorTest.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/HugeMetadataDownloadTest.java
Seems currently indy will meet problem when downloading maven-metadata.xml with huge version list. This is caused by a regex to fetch the versions in metadata, which will bring StackOverflowError when the version list is a big one. We should avoid using regex here, so in the fix I used DOM+XPATH way to get that versions. This may bring little performance loss but can fix the problem.
=>  Fix download problem for maven-metadata.xml with huge version list

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, db/infinispan/src/main/java/org/commonjava/indy/infinispan/data/InfinispanStoreDataManager.java
This is the first issue I found on stage. The affectedBy method print tons of INFO log and flushed everything away. We have a dedicated API to check it in 2.0. So we don't need the INFO log anymore.
=> Adjust some debug levels

db/infinispan/src/main/java/org/commonjava/indy/infinispan/data/InfinispanStoreDataManager.java
The affectedBy result could be very huge in some cases. This pr avoid useless string objects being built.
=> Avoid affectedBy building long log messages

addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/NFCContentListener.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/change/MetadataMergePomChangeListener.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionHelper.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, api/src/main/java/org/commonjava/indy/data/StoreDataManager.java, api/src/main/java/org/commonjava/indy/util/ValuePipe.java, db/common/src/main/java/org/commonjava/indy/db/common/AbstractStoreDataManager.java
This pr get affectedBy groups at the beginning of promotion and pass it to clearStoreNFC() and contentIndex via eventMetadata. Some big builds promote throusands of paths. The fix should reduce quite some promotion time for them.
=> Save and reuse affectedBy groups during promotion

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/change/MetadataMergePomChangeListener.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, api/src/main/java/org/commonjava/indy/data/StoreDataManager.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java
The pr does 2 things:
1. save the promotion target (as well as affected) for reuse. this will reduce getArtifactStore invokes. e.g, if it promotes 1000 pom files, it will reduce to 1.
2. improve doClear to handle .info only when the .meta exists. the will cut the existency checks 50% because most affected groups (build_xxx) does not have relavent meta path at all.
=> Reuse promotion target store and improve doClear

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/change/MetadataMergePomChangeListener.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/conf/PromoteConfig.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/util/Batcher.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidationTools.java, addons/promote/common/src/test/java/org/commonjava/indy/promote/validate/PromotionValidationToolsTest.java
We have a problem using batch to promote files. 
I noticed that there is only one thread doing promotion for a small build. It promotes less than 10 files but takes 15+ minutes.
I see the promotion thread pool size is 200 which is pretty large. If the files are less, e.g., 10 files, it will ends up with one thread doing the promotion. Current batch size only works for large build with thousands of files.
This pr calculate the batch size according to thread pool size. It will work for both small and large builds. It will boost the performance of smaller builds significantly.
=> Calculate promotion batch size by the pool size

db/common/src/main/java/org/commonjava/indy/db/common/AbstractStoreDataManager.java, db/memory/src/main/java/org/commonjava/indy/mem/data/MemoryStoreDataManager.java
The affectedByAsyncRunner in constructor is only for testing. It will always be overriden by field injection in real case. GC will reclaim this abandoned thread pool but this waste time.
=> Remove affectedByAsyncRunner from AbstractStoreDataManager constructor

core/src/main/java/org/commonjava/indy/core/inject/CassandraNotFoundCache.java
For cleaning, we don't need result and it is proper to use executeAsync to improve performance.
=> Cassandra NFC to use executeAsync when do clearing

core/src/main/java/org/commonjava/indy/core/inject/CassandraNotFoundCache.java
Reverts Commonjava/indy#1537 
This caused a problem with the Cassandra session, where the operation queue was overflowing.
=> Revert "Cassandra NFC to use executeAsync when do clearing"

core/src/main/java/org/commonjava/indy/core/inject/CassandraNotFoundCache.java, filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java, subsys/cassandra/src/main/java/org/commonjava/indy/subsys/cassandra/CassandraClient.java
Create Cassandra sessions for each keyspace. In current situation, we use 2 sessions for indycache and indystorage. This helps to seperate concerns when it comes to connection problems. I expect this will help performance as well because each session manages its own connection pool.
=> Cassandra session per keyspace

addons/content-index/src/main/java/org/commonjava/indy/content/index/DefaultContentIndexManager.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/NFCContentListener.java
This is due to two reasons: 
1. NFC is not per directory but per concrete path. This makes the clean-up Java thread "store-affected-by-async-runner::ContentIndexNFCClean-store(maven:remote:central)-path(org/sonatype/spice/spice-parent/15/)" useless. And doing clean-up in the listener makes it hard to share some important information, e.g, the cached affected groups.
ps. depending on the ISPN event should be removed as we move to clustering.
2. I see lots of affected-by-async-runner threads blocking on NFC clean. This might be the cause of reboot when the load is suddenly high and the datastax connection pools are not warmed up. 
More detail is in nos-2424.
=> Disable content-index's NFCContentListener and move the clean ups to indexManager

api/src/main/java/org/commonjava/indy/conf/DefaultIndyConfiguration.java, core/src/main/java/org/commonjava/indy/core/inject/CoreProvider.java
Make sure the producer method return a singleton. Use ISPN nfc for default. 
Today we tested it and the old ispn nfc works well. The test started with low node-free mem and passed. I need to test it tmr morning to verify if it causes the reboot problem.
=> Minor improvement for NotFoundCache producer

addons/content-index/src/main/java/org/commonjava/indy/content/index/DefaultContentIndexManager.java, addons/content-index/src/main/java/org/commonjava/indy/content/index/change/StoreChangeListener.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java, db/common/src/main/java/org/commonjava/indy/db/common/AbstractStoreDataManager.java, db/infinispan/src/main/java/org/commonjava/indy/infinispan/data/InfinispanStoreDataManager.java
Based on what I found in the log, the last log before reboot was pasted at http://pastebin.test.redhat.com/844790
From this log, the failure might happened at: 
1. PromotionManager (because the info log not printed out)
affectedGroups = storeManager.query().getGroupsAffectedBy( targetKey );
logger.info( "Calculate affected groups, target: {}, affected-groups: {}", targetKey, affectedGroups );
2. StoreChangeListener. The last info log was from here.
This pr:
1. add filter to affectedby from the beginning init. So we can see getGroupsAffectedBy return quickly.
2. a few log level change.
If CI is happy, I will merge it and open debug level for indy stage, and test again.
=> Filter affected groups from initAffectedBy

deployments/launcher/pom.xml
I saw the following dependencies had been removed in the pr:
https://github.com/Commonjava/indy/pull/1507/files
We need that to export swagger.json
=> Fix the swagger missing issue

deployments/docker/pom.xml
This brings the docker kit to the same version as other sub-projects.
=> Version bump parent pom version.

addons/pkg-npm/common/pom.xml, addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/change/PackageStoreListener.java, addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/PackageMetadataGenerator.java, addons/pkg-npm/common/src/test/java/org/commonjava/indy/pkg/npm/content/PackageMetadataGeneratorTest.java, addons/pkg-npm/common/src/test/resources/metadata/scoped-version-1.json, addons/pkg-npm/common/src/test/resources/metadata/scoped-version-2.json, addons/pkg-npm/common/src/test/resources/metadata/version-1.json, addons/pkg-npm/common/src/test/resources/metadata/version-2.json, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMHostedReStoreContentTest.java, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMHostedRetrieveFileTest.java, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMHttpMetaGenerationTest.java, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMTarballContentGenerationWhenUploadTest.java, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMTwoTimesUploadsGeneratedContentsTest.java, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMUploadContentMergeRetrieveTest.java, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMVersionMetaGenerationWhenUploadTest.java, addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessHandler.java, addons/pkg-npm/model-java/src/main/java/org/commonjava/indy/pkg/npm/model/PackageMetadata.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java
As [the comment](https://projects.engineering.redhat.com/browse/NOS-2034?focusedCommentId=2057358&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2057358) mentioned, as well as what I test locally, when a package is uploaded, there is also being uploaded a json on path package/version, this can be reused when generating the aggregated metadata file. So it works so far that we don't need to generate it from tarballs. 
The PR also includes the listener to clear the aggregated metadata file when there is new package being uploaded. 
BTW, I also remove the merge operation when receiving the new uploaded package, the aggregated one can be generated by the generation method when there is missing.
=> NPM metadata generator

filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java, subsys/metrics/core/src/main/conf/conf.d/metrics.conf, subsys/metrics/reporter/src/main/conf/conf.d/metrics.conf, subsys/metrics/reporter/src/main/java/org/commonjava/indy/metrics/conf/IndyMetricsConfig.java, subsys/metrics/reporter/src/main/resources/default-metrics.conf
This pr allows us to enable/disable pathDB metrics. If needed, we can also specify which method to measure.
=> Fine control pathDB metrics

pom.xml
Not sure why this is here. Path mapped is under indy/addon.
=> Remove abandoned indy-subsys-pathmapped

boot/jaxrs/src/main/java/org/commonjava/indy/boot/jaxrs/JaxRsBooter.java
Sometimes we meet unhandled Error which breaks JVM, e.g., Caused by: java.lang.Error: Maximum permit count exceeded
at java.util.concurrent.Semaphore$Sync.tryReleaseShared(Semaphore.java:192)
This pr will handle all such cases and report the issue. The old code only set handler for main thread which is not enough.
=> Set default thread error handler

addons/repo-proxy/common/pom.xml, addons/repo-proxy/common/src/main/conf/conf.d/repo-proxy.conf, addons/repo-proxy/common/src/main/data/default-rule.groovy, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/RepoProxyAddon.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/RepoProxyContoller.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/RepoProxyException.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/RepoProxyUtils.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/conf/RepoProxyConfig.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/create/AbstractProxyRepoCreateRule.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/create/ProxyRepoCreateManager.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/create/ProxyRepoCreateRule.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/create/ScriptRuleParser.java, addons/repo-proxy/common/src/main/resources/META-INF/beans.xml, addons/repo-proxy/common/src/main/resources/default-repo-proxy.conf, addons/repo-proxy/common/src/test/java/RepoProxyUtilsTest.java, addons/repo-proxy/ftests/pom.xml, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyDefaultTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyDisableTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyMethodsTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyPatternsTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/create/RepoProxyCreatorDefaultTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/create/RepoProxyCreatorNotMatchTest.java, addons/repo-proxy/ftests/src/main/resources/beans.xml, addons/repo-proxy/jaxrs/pom.xml, addons/repo-proxy/jaxrs/src/main/java/org/commonjava/indy/repo/proxy/jaxrs/RepoProxyAdminResource.java, addons/repo-proxy/jaxrs/src/main/java/org/commonjava/indy/repo/proxy/servlet/RepoProxyDeploymentProvider.java, addons/repo-proxy/jaxrs/src/main/java/org/commonjava/indy/repo/proxy/servlet/RepositoryProxyFilter.java, addons/repo-proxy/pom.xml, embedder/pom.xml, pom.xml
This pr focus the first part of the repository proxy addon: do the automatic proxy for the hosted/group repository. Includes:
* Rewrites api url and forwards to new one.(from hosted/group repo to remote)
* Includes repo creator script way to create proxy to remote automatically
* Controls which apis will be handled in rewriting, based on api url patterns in configuration
* Controls which http methods can be included in rewriting, based on configuration
* Can be enabled/disabled
=> Repository proxy addon part 1 - automatic proxy 

core/src/main/java/org/commonjava/indy/core/content/DefaultContentDigester.java
Add debug log to catch folo 0-sized artifact problem. The problem is fixed in path-mapped storage. Adding those logs is just in case.
=> Add debug log to DefaultContentDigester

addons/repo-proxy/common/src/main/conf/conf.d/repo-proxy.conf, addons/repo-proxy/common/src/main/data/default-rule.groovy, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/NPMMetadtaRewriteResponseDecorator.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/RepoProxyContoller.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/RepoProxyResponseDecorator.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/RepoProxyUtils.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/conf/RepoProxyConfig.java, addons/repo-proxy/common/src/main/resources/default-repo-proxy.conf, addons/repo-proxy/common/src/test/java/RepoProxyUtilsTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyDefaultTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyDisableTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyMethodsTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyNPMHugeMetaContentRewriteTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyNPMMetaRewriteDisableTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyNPMMetaRewriteTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyPatternsTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/create/RepoProxyCreatorWithNPMContentRewriteTest.java
As NPM meatadata contains url which points to the npm package, we need to rewrite these urls to replace the repo path by proxy-rules.This commit did following:
* Intercept NPM metadata path, like /jquery, /@angular/core or /jquery/package.json
* Replacing url which is using the proxy-to repo path with the request repo path in the metadata content, like "tarball:"
* And this feature can be disabled by config "npm.meta.rewrite.enabled", default is enabled
=> Repository proxy addon part 2 - Controlling NPM metadata content

addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/RepoProxyUtils.java, addons/repo-proxy/common/src/test/java/org/commonjava/indy/repo/proxy/RepoProxyUtilsTest.java
When testing, I found there is a bug of extract path from a full http request path. This is a fix for it.
=> Fix a small bug of extract path from full http request path

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/keycloak/KeycloakProxyAuthenticator.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/keycloak/BasicAuthenticationOAuthTranslator.java
This debugger class actually has some code that throws two different kinds of RuntimeException, which is very dangerous considering its function is to help debug the authentication process (not change it).
=> [maint] Disable bearer token debug

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/keycloak/KeycloakProxyAuthenticator.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/keycloak/BasicAuthenticationOAuthTranslator.java
This debugger class actually has some code that throws two different kinds of RuntimeException, which is very dangerous considering its function is to help debug the authentication process (not change it).
=> [master] Disable bearer token debug

models/core-java/src/main/java/org/commonjava/indy/stats/IndyDeprecatedApis.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/ApiVersioningFilter.java
In java 8, we have better way now to solve "null-return" problem by using java.util.Optional, which makes the "null-return" more like some code smell. This pr is to refactor the api version problem by this way.
=> Refactor the getDeprecated to use Optional instead of returning null

addons/repo-proxy/common/src/main/data/default-rule.groovy, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/create/AbstractProxyRepoCreateRule.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/create/ProxyRepoCreateManager.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/create/ProxyRepoCreateRule.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/create/RepoProxyCreatorDefaultTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/create/RepoProxyCreatorNotMatchTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/create/RepoProxyCreatorWithNPMContentRewriteTest.java
In current code, when each request goes in proxy, the process needs to retrieve the proxy-to remote repo from the repo-creator script, which means needs to execute the groovy code for each request. This is not good for performance if the request number is huge. 
So this fix will cache the remote key for the group/hosted key in the request to avoid to run the groovy again for the following same hosted/hosted request, which will improve the performance.
=> Cache storekey created by repo-creator

addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/PackageMetadataGenerator.java, addons/pkg-npm/model-java/src/main/java/org/commonjava/indy/pkg/npm/model/Engines.java, addons/pkg-npm/model-java/src/main/java/org/commonjava/indy/pkg/npm/model/License.java, addons/pkg-npm/model-java/src/main/java/org/commonjava/indy/pkg/npm/model/NpmJsonOpts.java, addons/pkg-npm/model-java/src/main/java/org/commonjava/indy/pkg/npm/model/Repository.java, addons/pkg-npm/model-java/src/main/java/org/commonjava/indy/pkg/npm/model/VersionMetadata.java, models/core-java/src/main/java/org/commonjava/indy/model/core/io/IndyObjectMapper.java
There are some errors when parsing the version metadata, for example:
the metadata engines of some package are object while some others are array:
`"engines":["node >=0.6.0"]`
`"engines":{"node":"*"}`
So I enable the configuration as follows to handle the above issue:
`configure( DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true);`
=> Enhance the NPM package object

addons/repo-proxy/common/pom.xml, addons/repo-proxy/common/src/main/conf/conf.d/repo-proxy.conf, addons/repo-proxy/common/src/main/data/default-rule.groovy, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/ContentBrowseRewriteResponseDecorator.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/ContentReplacingOutputStream.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/ContentReplacingResponseWrapper.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/RepoProxyController.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/RepoProxyUtils.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/conf/RepoProxyConfig.java, addons/repo-proxy/common/src/main/resources/default-repo-proxy.conf, addons/repo-proxy/common/src/test/java/org/commonjava/indy/repo/proxy/RepoProxyUtilsTest.java, addons/repo-proxy/ftests/pom.xml, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyDefaultTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyDisableTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyMethodsTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyNPMHugeMetaContentRewriteTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyNPMMetaRewriteDisableTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyNPMMetaRewriteTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyPatternsTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/create/RepoProxyCreatorContentBrowseTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/create/RepoProxyCreatorMavenContentBrowseTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/create/RepoProxyCreatorNPMContentBrowseTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/create/RepoProxyCreatorNotMatchTest.java, addons/repo-proxy/jaxrs/src/main/java/org/commonjava/indy/repo/proxy/servlet/RepositoryProxyFilter.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/util/RequestUtils.java
This pr will replace all original repo info to its proxy to repo for content browse api, including both path info and store key info.
=> Repo-proxy: Apply content rewriting for content browse api

addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/group/PackageMetadataMerger.java, addons/pkg-npm/model-java/src/main/java/org/commonjava/indy/pkg/npm/model/io/PackageSerializerModule.java, addons/pkg-npm/model-java/src/main/java/org/commonjava/indy/pkg/npm/model/io/VersionMetadataDeserializer.java, addons/pkg-npm/model-java/src/test/java/org/commonjava/indy/pkg/npm/model/VersionMetadataTest.java, addons/pkg-npm/model-java/src/test/resources/test-package-tmp.json
Adding this aims to handle the parsing stuff more flexible I hope,
seems the rules of package metadata template is loose/open, I see
most of the repository of version metadata is a object containing
"type" and "url",  but we ran into the pakcage "tmp" which the repository
is a array, and that appears only in one of their versions(e.g.: 0.0.4).
Details see: http://registry.npmjs.org/tmp
I don't think we need to update our model to adapt this type of data,
but we have to consider it because it will break our code and cause
no versions for the package.
=> Add custom deserializer for VersionMetadata

api/src/main/java/org/commonjava/indy/model/galley/RepositoryLocation.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/AbstractRemoteRepoTimeoutTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RemoteRepoHeadTimeoutTest.java, pom.xml
Besides the Undertow/Xnio version update, there are two fixes:
1. DelayInputStream read returning -1. The @Rule expectedServer will hang on there if the stream is not complete. This cased six xxxTimeoutTest hang and eventually timeout.
2. The artifact store metadata is map<string, string> but the attributes in Location is map<string,object>. This discrepancy will miss the connection-timeout set by artifactstore.setMetadata().
=> Update undertow and xnio versions

addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/group/PackageMetadataMerger.java, addons/pkg-npm/common/src/test/java/org/commonjava/indy/pkg/npm/content/group/PackageMetadataMergerTest.java
NPM builds are consuming this merge method heavily, to save the time to construct the objectMapper for each request, let's use the injected one instead.
=> Use the injected objectMapper

pom.xml
Pathmap 1.4 contains two fixes: Skip physicalStore.exists; Lower addToReverseMap ConsistencyLevel to ONE. We will need them in next indy 2.1.x release.
=> Update to pathmap 1.4 snapshot

addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/PackageMetadataGenerator.java, addons/pkg-npm/common/src/test/java/org/commonjava/indy/pkg/npm/content/group/PackageMetadataMergerTest.java, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMGroupContentMergeRetrieveTest.java, addons/pkg-npm/model-java/src/main/java/org/commonjava/indy/pkg/npm/model/PackageMetadata.java
Use "Licence" object instead to adapt some package metadata, e.g.: http://registry.npmjs.org/deep-is
=> Fix NPM package metadata parsing error

addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/NPMStoragePathCalculator.java, addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/data/NPMSpecialPathProducer.java, addons/pkg-npm/common/src/test/java/org/commonjava/indy/pkg/npm/content/PackageMetadataGeneratorTest.java, addons/pkg-npm/common/src/test/java/org/commonjava/indy/pkg/npm/content/group/PackageMetadataMergerTest.java, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMHttpMetaDeleteTest.java
I found the following logs when checking NPM stuff in indy.log:
```
Modifying target path: immediate.http-metadata.json, appending 'package.json'
immediate.http-metadata.json/package.json not exists in fileSystem npm:remote:npmjs
Modifying target path: immediate.md5, appending 'package.json'
immediate.md5/package.json not exists in fileSystem npm:remote:npmjs
Modifying target path: immediate.sha256, appending 'package.json'
```
The correct path should be:
"immediate/package.json.md5" rather than "immediate.md5/package.json"
=> Update NPM pathCalculator to support metadata and checksum files

core/src/main/java/org/commonjava/indy/core/content/ContentGeneratorManager.java
To avoid the duplicate running to getPath and path calculator.
=> Move the getPath out from the loop

models/core-java/src/main/java/org/commonjava/indy/inject/IndyVersioningProvider.java
* Use getClass().getClassLoader() to load version properties file
* Use IndyVersioningProvider.class.getClassLoader()
* Warn if resource not found
=> [Cherry-pick] Use getClass().getClassLoader() to load version properties file (#1604)

ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java
This PR solves the issue identified in issue #1622 
The change changes when closing the session occurs. Preventing a NullPointerException on the client.cluster field.
=> Fixed handling of cassandra client.

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyAcceptHandler.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyResponseWriter.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyTransfersExecutor.java, addons/httprox/common/src/test/java/org/commonjava/indy/httprox/HttpProxyTest.java, addons/httprox/ftests/pom.xml, addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/ProxyHttpsTest.java, addons/httprox/ftests/src/main/resources/conf.d/threadpools.conf
This PR solves the issue identified in #1613 
The change ensures only one Executor is used to create threads for requests. Instead of an Executor per request.
=> Executor thread pool should live for the duration of the Application lifetime.

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyMITMSSLServer.java, addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxySSLTunnel.java, subsys/groovy/src/main/java/org/commonjava/indy/subsys/template/ScriptEngine.java
These optimizations improve execution times and overhead on the jvm process. To solve the issues in #1611 
Using a simple benchmark to drive load at the proxy these results were obtained for identical testing duration:
before: commit 8ed2ff91d3fb9ee1868fefee383b0b5033064bc7
memory allocations, total requests
231MB per second, 326 requests
after: commit 78dcb66e85123e755457354323c72a85790596e7
memory allocations, total requests
41MB per second, 338 requests
Overall CPU utilization was reduced as well.
=> Performance optimizations.

subsys/honeycomb/pom.xml, subsys/honeycomb/src/main/java/org/commonjava/indy/subsys/honeycomb/HoneycombManager.java, subsys/honeycomb/src/main/java/org/commonjava/indy/subsys/honeycomb/IndyEventPostProcessor.java
As mentioned in https://projects.engineering.redhat.com/browse/MMENG-398, It would be good if we could monitor the rate at which we're sending events from each Indy instance, up to Honeycomb. After researching, I think we can put the stuff into the method "process" of the class 
https://honeycombio.github.io/libhoney-java/io/honeycomb/libhoney/EventPostProcessor.html
=> Add metrics in the honeycomb event post processor 

addons/path-mapped/common/src/main/java/org/commonjava/indy/pathmapped/cache/PathMappedMavenGACache.java, addons/path-mapped/common/src/main/java/org/commonjava/indy/pathmapped/inject/PathMappedMavenGACacheGroupRepositoryFilter.java
a minor improvement. If no candidate match the cache pattern, skip GA cache filtering earlier.
=> Use gaCache.matchAny to reduce unnecessary filtering

addons/path-mapped/common/src/main/java/org/commonjava/indy/pathmapped/cache/PathMappedMavenGACache.java
So we not lose success ones when something bad happens. This is less useful in normal cases. But in perf test, we have to scan thursands of repos by this code.
=> Allow GA cache to scan in batch

pom.xml, subsys/cpool/pom.xml, subsys/cpool/src/main/conf/conf.d/connection-pools.conf, subsys/cpool/src/main/java/org/commonjava/indy/subsys/cpool/ConnectionPoolConfig.java, subsys/cpool/src/main/java/org/commonjava/indy/subsys/cpool/ConnectionPoolProvider.java
I used `AgroalPropertiesReader` for convenience, but can have a custom builder of the Agroal configuration that doesn't break compatibility so much.
=> Change connection pool implementation to Agroal

subsys/cassandra/src/main/java/org/commonjava/indy/subsys/cassandra/CassandraClient.java, subsys/cassandra/src/main/java/org/commonjava/indy/subsys/cassandra/ConfigurableRetryPolicy.java, subsys/cassandra/src/main/java/org/commonjava/indy/subsys/cassandra/config/CassandraConfig.java
This is another part of fix for issue 
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency ALL (3 replica were required but only 2 acknowledged the write)
by config the write retry.
=> Config cassandra write retry

subsys/metrics/core/src/main/java/org/commonjava/indy/metrics/jvm/IndyJVMInstrumentation.java
Since the thread metric requires traversing all threads and can be a little
more expensive than some other metrics, and the cached version can cache
the information for the given interval and time unit.
https://github.com/dropwizard/metrics/issues/508
=> Switch to use the cached version for thread metrics

addons/path-mapped/common/src/main/java/org/commonjava/indy/pathmapped/cache/PathMappedMavenGACache.java, addons/path-mapped/common/src/main/java/org/commonjava/indy/pathmapped/inject/PathMappedMavenGACacheGroupRepositoryFilter.java
We do maintanance when using ga cache to find out the stale stores. Here we can use async to reduce the impact on the retrieval logic. Async does not check if the operation success, but in this case, it is good enough.
=> Use executeAsync in maint op

addons/path-mapped/common/src/main/java/org/commonjava/indy/pathmapped/inject/PathMappedGroupRepositoryFilter.java, addons/path-mapped/common/src/main/java/org/commonjava/indy/pathmapped/inject/PathMappedMavenGACacheGroupRepositoryFilter.java
If the path is non-snapshot maven metadata, we use GACacheGroupRepositoryFilter result directly. And skip the default filter. This will life some Cassandra load.
=> Skip default RepositoryFilter for maven metadata when GA cache in action

db/common/src/main/java/org/commonjava/indy/db/common/DefaultArtifactStoreQuery.java
This is fix for MMENG-509. 
When querying stores, the invalid repo should print a warn and skipped. Error level is misleading.
=> Fix misleading error log during store query

addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMMetadataRevisitTimeoutTest.java, core/src/main/java/org/commonjava/indy/core/expire/ScheduleKey.java, core/src/main/java/org/commonjava/indy/core/expire/TimeoutEventListener.java, embedder/src/test/resources/logback-test.xml, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/MetadataRevisitTimeoutTest.java
We found that the npm metadata timeout for remote repo does not work
correctly. It is not working based on the initial access time, but on
the last access time, which is totally wrong way. This commit is
addressing the problem.
=> Fix a metadata timeout reset problem

addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/ContentBrowseRewriteResponseDecorator.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/ContentReplacingOutputStream.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/NPMMetadtaRewriteResponseDecorator.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/RepoProxyController.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/RepoProxyUtils.java, addons/repo-proxy/common/src/test/java/org/commonjava/indy/repo/proxy/RepoProxyUtilsTest.java
I've used a wrong API when do replacement based on the static-proxy route rule, seems some group/hosted name contains "+", which is a valid char in regex, and so when using replaceAll these chars are treated as regex but not normal charsequence. This is not correct.
=> Fix bug: wrong use of String.replaceAll(regex,replacement)

addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/RepoProxyController.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/RepoProxyUtils.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/conf/RepoProxyConfig.java, addons/repo-proxy/common/src/test/java/org/commonjava/indy/repo/proxy/RepoProxyUtilsTest.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyBlockListTest.java, addons/repo-proxy/jaxrs/src/main/java/org/commonjava/indy/repo/proxy/servlet/RepositoryProxyFilter.java
We found that there are some unavailable metadata access to indy which will take much time and block external build. This is mainly caused by main indy metadata generation time-consuming problem. And sometimes we can confirm these metadata are not supported indy, so here add this block list in statc-proxy side to make them fail-fast.
=> [Repo-proxy] Add block list support for static repo proxy

models/core-java/src/main/java/org/commonjava/indy/model/core/RemoteRepository.java
Seems this commit will break current repository data store
deserilization. As it is not needed now, I'll revert it.
This reverts commit c05504b260d0daeea73ef5aec3a840842c9e222b.
=> Revert "Add a new flag in RemoteRepository to identify if remote host is a indy instance"

addons/repo-proxy/common/pom.xml, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/ContentBrowseRemoteIndyListingRewriteManager.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/ContentBrowseRewriteResponseDecorator.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/RepoProxyController.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/conf/RepoProxyConfig.java, addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyRemoteIndyListingRewriteTest.java, clients/core-java/src/main/java/org/commonjava/indy/client/core/IndyClientHttp.java
For static-proxy, current static instance uses its own proxy remote to
render directory listing content, which is all located in the remote
cache itself. This brings problem, especially if the remote target is
also indy instance. So this commit will enable a feature that uses
remote indy listing content api instead for directory content listing
request.
=> Static-proxy: Enable remote indy listing content rewriting

pom.xml
This PR bumps Galley to
1.4-SNAPSHOT
and path-mapped-storage to
1.7-SNAPSHOT.
To take advantage of the more efficient stream handling changes in.
=> Version bump Galley and Path-mapped-storage.

api/src/main/java/org/commonjava/indy/util/ApplicationContent.java, api/src/main/resources/extra-mime.types, boot/jaxrs/pom.xml, boot/jaxrs/src/main/java/org/commonjava/indy/boot/jaxrs/IndyDeployer.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/SetContentTypeNotExistsTest.java
As Firefox or some curl or wget in old version centos will do dounble-gzip for .gz and .tgz files if the response header "Content-Encoding" is set to "gzip", it will cause chaos. This fix is addressing the problem.
=> Fix bug for firefox mis-actions of tar.gz with Content-Encoding:gzip response headers

addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/NPMPackageMaskingTransferDecorator.java
This PR looks to improve the current situation. Improving the situation identified in issue #1685 .
A micro benchmark shows the improvement using this change has these results.
```
Benchmark                            Mode  Cnt  Score   Error   Units
NPMPackageMaskBenchmark.bulk        thrpt    5  2.737 ± 1.103  ops/ms
NPMPackageMaskBenchmark.individual  thrpt    5  0.302 ± 0.003  ops/ms
```
An unsophisticated profiler shows
this is the difference in the existing code. Test named "individual"
```
....[Thread state: RUNNABLE]........................................................................
1.0%  90.0% java.io.FileInputStream.read0
0.1%   4.7% java.lang.Object.wait
0.0%   2.3% <stack is empty, everything is filtered?>
0.0%   0.7% java.io.FileInputStream.open0
0.0%   0.5% …
```
=> Changed to use bulk read method.

addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessHandler.java
Currently if a scoped package is uploaded it ends up on path `@scope/package/-/@scope/package-1.0.0.tgz`, but the correct path would be `@scope/package/-/package-1.0.0.tgz`. This should fix it.
=> [NCL-5937] Fix storage path for uploaded scoped NPM packages

addons/promote/client-java/src/main/java/org/commonjava/indy/promote/client/IndyPromoteClientModule.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/GroupPromoteRequest.java
Seems currently the group promotion does not support npm package type.
=> Promote: Enhance GroupPromoteRequest api for multi package type support

addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/PackagePath.java, addons/pkg-npm/common/src/test/java/org/commonjava/indy/pkg/npm/content/PackagePathTest.java, addons/promote/common/pom.xml, addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidationTools.java
This will be used in promotion validation as sort of
ArtifactInfo.parse in npm type
=> Promote: Expand NPMPackagePath support to be used in promotion

deployments/standalone/launcher/pom.xml, deployments/standalone/pom.xml
Not sure why they not change. I fix the standalone versions manually to 2.5.0.
=> Fix leaked version

addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/NPMStoragePathCalculator.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/model/ValidationRequest.java, addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/PromoteRequest.java, api/src/main/java/org/commonjava/indy/metrics/RequestContextHelper.java, api/src/main/java/org/commonjava/indy/util/ContentUtils.java
This fix is used to let galley ignore the NPMPathStorageCalculator handling, which will append package.json to a directory transfer and make listing not applicable.
=> Promote: Fix listing problem for promotion of npm pkg

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, pom.xml
The snapshot version should not be the raw remote version, but "xxx-snapshot". For example,
https://oss.sonatype.org/content/repositories/snapshots/org/commonjava/maven/galley/galley-transport-httpclient/0.10.4-SNAPSHOT/maven-metadata.xml
This depends on https://github.com/Commonjava/atlas/pull/87
=> Fix wrong snapshot version in metadata.xml

subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/SlashTolerationFilter.java
[ERROR] [XNIO-2 task-1] io.undertow.request no no - UT005023: Exception handling request to /
java.lang.AbstractMethodError: org.commonjava.indy.bind.jaxrs.SlashTolerationFilter.init(Ljavax/servlet/FilterConfig;)V 
It seems the jboss-servlet-api and javax.servlet.api both contains javax.servlet.Filter interface and the runtime chosen one does not impl the init/destroy methods. I did not dig why this happens but this pr should be able to fix it.
=> Fix the AbstractMethod error from SlashTolerationFilter

addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/PackagePath.java, addons/pkg-npm/common/src/test/java/org/commonjava/indy/pkg/npm/content/PackagePathTest.java
This fix is to address the verion path support in promote validation
for npm type. The version path is like ${package}/${version} or
@${scope}/${package}/${version}
=> Promote: NPM version path support

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java
Many times I found maven download obselete snapshot jar files. This is because we generate wrong <updated> tag in maven-metadata. We use the 'current' time for all snapshots, e.g., http://pastebin.test.redhat.com/899830. Unfortunately, maven use this tag to decide which snapshot to use. 
This fix generate the updated tag by the real updated time.
=> Fix maven snapshot updated

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionHelper.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/PromoteMetadataShouldSkipWithReadonlyTest.java
In promote, we should always let the transfer promotion happen
whether the target is readonly or not. But currently there is a bug
for metadata deletion in promotion. This pr is to fix the problem.
=> Promote: Fix deletion error for readonly target

subsys/honeycomb/src/main/java/org/commonjava/indy/subsys/honeycomb/IndyCassandraConnectionRootSpanFields.java
Fix NPE from constructor. This error is due to erroneous inherit instanciation follow.
=> Fix NPE from IndyCassandraConnectionRootSpanFields constructor

addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMMetadataRevisitTimeoutTest.java, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMMetadataTimeoutTest.java, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMMetadataWithContentTimeoutTest.java, addons/pkg-npm/ftests/src/main/resources/babel-parser-7.0.0-beta.48.json
These two enhanced ftests want to ensure the package metadata for npm in remote repo can be expired correctly with scheduled timeout.
=> Npm schedule: add test for remote pkg metadata timeout

db/cassandra/pom.xml, db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/CassandraStoreDataManager.java, db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/CassandraStoreQuery.java, db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/CassandraStoreUtil.java, db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/DtxArtifactStore.java, db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/config/CassandraStoreConfig.java, db/cassandra/src/test/java/org/commonjava/indy/cassandra/data/CassandraStoreTest.java, db/pom.xml, embedder/pom.xml, pom.xml
The patch only considers the basic operation against the artifact store in cassandra, for the affectedByStores, let's see if it would be better to use another table instead of the cache.
=> Init storeDataManager for cassandra

subsys/honeycomb/src/main/java/org/commonjava/indy/subsys/honeycomb/IndyCustomTraceIdProvider.java
With this, we can use the same trace-id for both in ThreadContent and Honeycomb.
=> Add IndyCustomTraceIdProvider to produce same traceId as preferedId

pom.xml
As subject.
With this, we can declare Indy supports HTTP/2. However, client side needs to change (e.g., mvn settings.xml). What I learned is to add "Upgrade: h2c" header. Maybe we need to run sth like 'curl --verbose' to verify HTTP/2 is in action.
=> Update propulsor to 1.5-SNAPSHOT for http/2

subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/SlashTolerationFilter.java
This problem will cause compilation error when after license header
formatting, which is caused by the package line removed.
=> Fix a wrong line problem

boot/jaxrs/src/main/java/org/commonjava/indy/boot/jaxrs/IndyDeployer.java
This is the right place to enable http/2. For some reason Indy does not use Propulsor undertow deployer.
=> Set UndertowOptions.ENABLE_HTTP2

addons/koji/common/src/main/java/org/commonjava/indy/koji/conf/IndyKojiConfig.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/data/KojiRemovePemMigrationAction.java
Add the flag to support to turn off PEM file configuration when we create repositories for the Koji, instead we can use the root CA certificate baked into the JVM at startup for Indy, then there is no need to maintain the server pem for this type of repos in future. 
See the issue: https://projects.engineering.redhat.com/browse/MMENG-11
=> Add flag for koji server.pem

core/src/main/java/org/commonjava/indy/core/expire/StoreKeyMatcher.java
This PR changes the matcher to cache the group name. Rather than building the group name every time the group name is needed in the stream filter condition expression.
=> Cache the group name.

addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/conf/RepoProxyConfig.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/content/RepoProxyCacheProducer.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/content/RepoProxyContentCache.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/content/RepoProxyContentLimiter.java
This adds a new cache-based content limiter for repo-proxy use cases. The idea is to avoid the table scans and other problems associated with scheduled expiration, and instead allow the eviction AND expiration to cause content to be deleted. Eviction is the main mechanism at work here, and allows us to tune disk usage for proxy use cases by tuning the number of cache entries allowed in memory.
The ScheduleManager approach tries to be a lot more correct in tracking and expiring content, and as a result it spends a lot more effort maintaining the cache for deleted or otherwise obsoleted entries. This results in a lot of table scans, using the current approach.
In contrast, the repo content limiter cache allows the entries to become obsolete, in the event content gets deleted. When this …
=> Add content limiting via expiration and eviction for repo-proxy in Indy

addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloLifecycleParticipant.java
As we have dropped the usage of git to manage data dir, and we have
switched to use infinispan to manage folo records, I don't think this
folo lifecycle action is still needed. But for safety, I just added
deprecated, and a .gitignore file existence checking here.
=> Add .gitignore checking for folo lifecycle start

core/src/main/java/org/commonjava/indy/core/ctl/SchedulerController.java, core/src/main/java/org/commonjava/indy/core/expire/ScheduleKey.java, core/src/main/java/org/commonjava/indy/core/expire/ScheduleManager.java, core/src/main/java/org/commonjava/indy/core/expire/ScheduleValue.java, core/src/main/java/org/commonjava/indy/core/expire/StoreKeyMatcher.java, core/src/main/java/org/commonjava/indy/core/expire/cache/ScheduleCacheProducer.java, core/src/test/java/org/commonjava/indy/core/expire/ScheduleManagerTest.java
We found that the ScheduleManager.cancel method will trigger the full table scan of the ScheduleCache because of the looping in its stream usage. This caused really bad performance impact on indy-static server. This commit is addressing this problem. It refactor the cache value object from a Map to a pojo which contains that map, and do indexing from ispn level. And then replace the stream looping with ispn query api.
=> Refactor schedule expiration to use ispn query api

core/src/main/java/org/commonjava/indy/core/expire/ScheduleManager.java
We received lots of JVM Blocked Threads alert today. I found those threads on indy-static were blocked by StoreKeyMatcher.matches(StoreKeyMatcher.java:52).
See full thread dump at [threaddump-20201102.log](https://github.com/Commonjava/indy/files/5474593/threaddump-20201102.log)
Each file event triggers a cancel() and the latter calls matches() which unfortunately do a **full table scan** to iterate through all cache keys. I believe this is a mistake. To find the target entry, we just use the schedulekey.
=> Fix scheduler causing blocked threads

deployments/cache-migrator/src/main/java/org/commonjava/indy/tools/cache/Main.java, deployments/cache-migrator/src/main/java/org/commonjava/indy/tools/cache/MigrationOptions.java
Provide the way to dump the FOLO records into multiple zip files based on the parameter batchSize, to avoid the timeout issue due to the large folo records on production.
```
dump folo-sealed <dir>/folo.zip -i <conf_dir>/infinispan.xml -b 100
```
=> Dump the folo record into zip files in batch

addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/PackageMetadataGenerator.java, addons/pkg-npm/model-java/src/main/java/org/commonjava/indy/pkg/npm/model/PackageMetadata.java
Versions are not sorted in npm metadata generation, which makes it not human friendly.
=> Do sorting for versions of npm metadata merging

db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/CassandraStoreDataManager.java
It uses objectMapper.writeValueAsString to convert Object into string when storing the record, need to use objectMapper.readValue to parse it back, otherwise there are some format issues. e.g.: 
Get the string directly without objectMapper keeps the quotation for the URL,  
`Remote URL: "http://download.eng.bos.redhat.com/brewroot/packages/sun-ws-metadata-2.0-api/1.0.MR1/11.ep5.el6/maven" `
The right one should be URL without the quotation:
`Remote URL: http://download.eng.bos.redhat.com/brewroot/packages/sun-ws-metadata-2.0-api/1.0.MR1/11.ep5.el6/maven`
=> Fix the parser issue

addons/promote/client-java/src/main/java/org/commonjava/indy/promote/client/IndyPromoteAdminClientModule.java, addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromoteValidationsManager.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/admin/AbstractAdminValidationTest.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/admin/RuleAndRuleSetGetTest.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/admin/RuleReloadTest.java, addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/admin/RuleSetReloadTest.java, addons/promote/jaxrs/src/main/java/org/commonjava/indy/promote/bind/jaxrs/PromoteAdminResource.java, addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/ValidationCatalogDTO.java, deployments/launcher/src/main/etc/indy/main.conf, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/ResponseHelper.java
Add these rest endpoints for promotion admin functions:
* PUT /api/admin/promotion/validation/reload/rules: reload promotion validation rules
* PUT /api/admin/promotion/validation/reload/rulesets: reload promotion validation rule-sets
* PUT /api/admin/promotion/validation/reload/all: reload rules and rulesets bundle together
* GET /api/admin/promotion/validation/rules/all: get all rules' names
* GET /api/admin/promotion/validation/rules/named/$name: get rule content by rule name
* GET /api/admin/promotion/validatoin/rulesets/all: get all rulesets' names
* GET /api/admin/promotion/validatoin/rulesets/named/$name: get ruleset content by ruleset name
* GET /api/admin/promotion/validatoin/rulesets/storekey/$storekey: get rule-set content by storeKey
=> Promotion: Add promote admin REST resource

addons/promote/client-java/src/main/java/org/commonjava/indy/promote/client/IndyPromoteAdminClientModule.java
Under jdk11, build error: addons/promote/client-java/src/main/java/org/commonjava/indy/promote/client/IndyPromoteAdminClientModule.java:[30,20] package javax.xml.ws does not exist
I found this import is not used. Removing it fix the error.
=> Remove unused imports

Jenkinsfile, pom.xml
This was originally reverted in #1785, but I got the CI builder image fixed, so it should work now. We have to merge it before Jenkins will pickup the changes to the Jenkinsfile, though, which explains this big revert-reapply mess.
This reverts commit 559158e1052edc370f48cf504caa481464602547.
=> Re-apply "Switched compliation to generate JDK11 bytecode. (#1778)"

Jenkinsfile, pom.xml
@whitingjr FYI
This will simply use the JDK11 by specifying JAVA_HOME in the Jenkinsfile, as a wrapper around all maven calls. I've also updated the javaVersion in the pom.xml.
=> re-apply JDK 11 changes, but adapted to use withEnv instead

pom.xml
This PR solves the problem where BytemanRunner tests needing to connect to another JVM.
Solves #1794
=> Allow jvm attach for ftests that use BytemanRunner.

Jenkinsfile, pom.xml
We got two problems that cause CI failure. One is the JAVA_HOME not match the latest image. I switch to maven-jdk11 agent which is verified. The second issue is upgrading to java language level 11 caused some ftests fail. atm, I reverted to 1.8.
CC @sswguo 
@ligangty has one pr including these two fixes. To make it simple ans isolated, I push this one.
=> Fix CI problem

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataCacheManager.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/cache/MetadataCacheProducer.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/marshaller/MetadataInfoMarshaller.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/marshaller/MetadataKeyMarshaller.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/marshaller/MetadataMarshaller.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/marshaller/PluginMarshaller.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/marshaller/SnapshotMarshaller.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/marshaller/SnapshotVersionMarshaller.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/marshaller/StoreKeyMarshaller.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/marshaller/VersioningMarshaller.java, addons/pkg-maven/common/src/main/resources/metadata_info.proto, addons/pkg-maven/common/src/main/resources/metadata_key.proto, pom.xml, subsys/infinispan/pom.xml, subsys/infinispan/src/main/conf/conf.d/cache-example.xml, subsys/infinispan/src/main/conf/conf.d/hotrod-client.properties, subsys/infinispan/src/main/conf/conf.d/infinispan-remote.conf, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/BasicCacheHandle.java, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/CacheProducer.java, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/config/ISPNRemoteConfiguration.java, subsys/infinispan/src/main/resources/default-infinispan-remote.conf
This patch includes:
- Init remote cache manager based on the hotrod-client.properties
- Add protobuf message and the related marshallers to support remote search
=> Udpate remote cache manager

pom.xml
This PR looks to solve the issue identified in #1803.
The version of Byteman used includes a manifest entry that allows the Transformer class to lookup this information.
=> Version bump Byteman to 4.0.13.

embedder/pom.xml, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java, pom.xml
This PR looks to solve issue #1621 so that Cassandra Server is started with JDK8.
=> Configure Cassandra Maven plugin to use Toolchains.

pom.xml, subsys/groovy/pom.xml, subsys/honeycomb/pom.xml, subsys/honeycomb/src/main/java/org/commonjava/indy/subsys/honeycomb/IndyCustomTraceIdProvider.java
Seems the missing o11yphant-honeycomb:1.3-SNAPSHOT dep is blocking other prs build like https://github.com/Commonjava/indy/pull/1832. This is fixing the problem.
=> Fix missing deps for new o11yphant:1.3-SNAPSHOT

pom.xml, subsys/groovy/pom.xml, subsys/honeycomb/pom.xml, subsys/honeycomb/src/main/java/org/commonjava/indy/subsys/honeycomb/IndyCustomTraceIdProvider.java, subsys/metrics/src/main/java/org/commonjava/indy/subsys/metrics/conf/IndyMetricsConfig.java
We need a prometheus node-label that won't also be part of the metric name, so the node prefix is not suitable. This provides a separate configuration point called `prometheus.node.label` to accomplish that task, and upgrades to o11yphant 1.3-SNAPSHOT to get configuration classes + usage that's compatible.
=> use latest o11yphant and express prom-specific node label config

db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/AffectedStoreMigrationAction.java, db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/CassandraStoreDataManager.java, db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/CassandraStoreQuery.java, db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/CassandraStoreUtil.java, db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/DtxAffectedStore.java, db/cassandra/src/test/java/org/commonjava/indy/cassandra/data/CassandraStoreTest.java, db/common/src/main/java/org/commonjava/indy/db/common/AbstractStoreDataManager.java, db/infinispan/src/main/java/org/commonjava/indy/infinispan/data/InfinispanStoreDataManager.java, db/memory/src/main/java/org/commonjava/indy/mem/data/MemoryStoreDataManager.java
To avoid to scan all the group store on querying the affectedBy each time, adding the table for the affected stores, that stores the info of the storeKey and its affected stores, and implement the method `affectedBy` and `refreshAffectedBy` as well in CassandraStoreDataManager.
=> Add table for affected stores

core/src/main/java/org/commonjava/indy/core/expire/InfinispanScheduleExpirationMigrationAction.java, core/src/main/java/org/commonjava/indy/core/expire/ScheduleManager.java, core/src/main/java/org/commonjava/indy/core/expire/cache/ScheduleCacheProducer.java, subsys/infinispan/src/main/resources/infinispan-jdbc.xml, subsys/infinispan/src/main/resources/infinispan.xml
As we will release new version in maint and I've found that the new ScheduleValue has been included, which causes the ScheduleCache data changing, I think we need the migration of this cache.
* Add new data migrator to address expiration value type change.
* Fix some NPE problem in ScheduleManager for new expiration value
type change.
=> Add schedule expiration cache migrator

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/util/HttpConduitWrapper.java
When downloading an md5 or a sha1, the metadata object is null for some
reason, but the code does not expect it in a single specific place,
while it does in others. Also setting the contentType to null seems safe,
because it is checked for null further down in the code.
Not sure if it is correct state that metadata is null, but this should
help unblock other features development in PNC.
=> Workaround NPE when downloading a checksum via httprox

core/src/main/java/org/commonjava/indy/core/inject/CoreProvider.java
When I debug the remote cache issue, and found that the log "Apply nfc provider .... " showed several times(7 times). I think this should be initialized at startup and the log should be expected only once.  Please correct me if I am wrong.
=> Init the NFC cache at startup

api/src/test/java/org/commonjava/indy/data/ArtifactStoreValidatorTest.java, filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java, filers/default/src/main/java/org/commonjava/indy/filer/def/conf/DefaultStorageProviderConfiguration.java, pom.xml
Add config storage.cassandra.replica to [storage-default]. If not set, use indy's default replica, ie., 3.
=> Pass replica when create PathDB instance

addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloCacheProducer.java, addons/folo/model-java/pom.xml, addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/TrackedContentEntry.java, addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/TrackedContentEntryTransformer.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MetadataKey.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/cache/MetadataCacheProducer.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/infinispan/CacheProducerMergeXmlTest.java, pom.xml, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/CacheProducer.java
Since the server side has been infinispan-server-runtime-11.0.9.Final-redhat-00001-loader.jar, it's better to use the same version in client side. And in case of any impact on the main code, I created a separate branch `ispn-11` for this, we can do some test before merging.
=> Update infinispan to 11.x

filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java, filers/default/src/main/java/org/commonjava/indy/filer/def/LegacyReadonlyPhysicalStore.java, filers/default/src/main/java/org/commonjava/indy/filer/def/conf/DefaultStorageProviderConfiguration.java
This allows Indy to config legacy storage using different base dir. We can mount it elsewhere like "/mnt/legacy/storage". This is useful as in:
1. legacy and new storage dirs not mixed;
2. easy back up (legacy volume is readonly, not need to backup);
3. separate from other dirs on the same volume (indy/data, indy/ui) to make the migration easier. 
I plan to test it when migrating old stage content to baremetal.
=> LegacyReadonlyPhysicalStore use separated legacyBaseDir

addons/folo/common/src/main/java/org/commonjava/indy/folo/action/FoloISPN2CassandraMigrationAction.java, addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloAdminResource.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/admin/MaintenanceHandler.java
The folo migration breaks when the dat is big (23G on prod) and cluster will reboot indy if it takes too long. I change it to call from MaintenanceHandler directly via REST.
=> Call FoloISPN2CassandraMigrationAction from REST

addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloAdminResource.java
The REST endpoint folo/admin/importToCassandra is too short. It offends the metrics code. Error:
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at org.commonjava.indy.subsys.metrics.IndyTrafficClassifier.calculateCachedFunctionClassifiers(IndyTrafficClassifier.java:121)
This pr changes it to folo/admin/report/importToCassandra. This is a minor fix. I merge it dirrectly.
=> Fix offending IndexOutOfBoundException of folo report/importToCassandra REST endpoint

api/src/main/java/org/commonjava/indy/conf/DefaultIndyConfiguration.java, pom.xml, subsys/honeycomb/src/main/java/org/commonjava/indy/subsys/honeycomb/IndyCustomTraceIdProvider.java
The new Honeycomb API has some small changes for W3C trace propagation compliance (https://www.w3.org/TR/trace-context/)
=> Upgrade honeycomb API version and add POD_NAME as potential nodeId envar source

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java
Currently the checksum of maven-metadata for group always returns the metadata content but not checksum value. Seems we bypassed it in MavenMetadataGenerator.
=> MMENG-1419 Fix incorrect group checksum files of maven-metadata.xml

addons/koji/common/src/main/java/org/commonjava/indy/koji/conf/IndyKojiConfig.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java
The new logic to check if group is enabled for koji pulling:
* Check group metadata with koji-pull tag: "false" means non-pulling and "true" to pulling ("no" and "yes" value are also accepted)
* Otherwise will check the group name with target.xxx pattern settings which follows the old way.
=> MMENG-1262 disable brew pulling when group metadata has "koji-pull:false"

addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCassandra.java
The real change is the select cql. The old cql query the full table which kills the performance (prod has huge amount of folo entries).
=> Fix folo get ids to avoid full-table scan

addons/folo/common/src/main/java/org/commonjava/indy/folo/action/FoloISPN2CassandraMigrationAction.java
This is to fix another folo migration issue. 
2021-04-27 00:38:38.420 [ERROR] [Thread-9] o.c.i.f.a.FoloISPN2CassandraMigrationAction no no - Folo content migrate failed, key: TrackingKey [build_shrinkwrap_20170602.1809]
java.lang.NullPointerException: null
at org.commonjava.indy.folo.data.DtxTrackingRecord.fromTrackedContentEntry(DtxTrackingRecord.java:127)
at org.commonjava.indy.folo.data.FoloRecordCassandra.saveTrackedContentRecords(FoloRecordCassandra.java:311)
at org.commonjava.indy.folo.data.FoloRecordCassandra.addSealedRecord(FoloRecordCassandra.java:230)
at org.commonjava.indy.folo.action.FoloISPN2CassandraMigrationAction.migrateForKey(FoloISPN2CassandraMigrationAction.java:158)
=> Fix missing store effect for some old folo entries

addons/event-publisher/common/pom.xml, addons/event-publisher/common/src/main/java/org/commonjava/indy/event/publisher/KafkaEventPublisher.java, pom.xml, subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/conf/KafkaConfig.java
Looks log appender has its config in the XML configuration(e.g.: [logback.xml](https://gitlab.cee.redhat.com/nos/nos-ansible-playbooks/-/blob/master/playbooks/nos-automation/files/indy-perf/etc/logging/logback.xml) ) we can use this producer for the connection to our internal kafka instance.
=> Add config for fileEvent topic

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/cache/MetadataCacheProducer.java
Fix the stage issue(for cluster mode):
`org.infinispan.client.hotrod.exceptions.HotRodClientException: org.infinispan.commons.CacheConfigurationException: The declared indexed type 'metadata_key.MetadataKey' is not known. Please register its proto schema file first.`
Need to make sure the .proto schema file is registered first before getting the remote cache.
=> Fix the remote metadata cache

clients/core-java/src/main/java/org/commonjava/indy/client/core/IndyClientHttp.java, models/core-java/src/main/java/org/commonjava/indy/stats/IndyVersioning.java, subsys/metrics/src/main/java/org/commonjava/indy/subsys/metrics/IndyTrafficClassifier.java, subsys/metrics/src/main/java/org/commonjava/indy/subsys/metrics/IndyTrafficClassifierConstants.java
Adding in parts of the client metrics changes that I missed in previous merge attempt.
One important point here is that I've pushed trace context propagation down into the jhttpc library, so the span creation is handled there, along with trace ID creation and passing. That's why we don't use the UUID traceId in the client layer anymore...it's handled in jhttpc, which the client API uses.
=> Merge remainder of PR #1846 from master

api/src/main/java/org/commonjava/indy/conf/InternalFeatureConfig.java, filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java, filers/default/src/main/java/org/commonjava/indy/filer/def/FileChangeTrackingDecorator.java, filers/default/src/main/java/org/commonjava/indy/filer/def/conf/DefaultStorageProviderConfiguration.java, filers/default/src/test/java/org/commonjava/indy/filer/def/FileChangeTrackingDecoratorTest.java, subsys/metrics/src/main/java/org/commonjava/indy/subsys/metrics/IndyTrafficClassifier.java
This is a way of logging the files that get changed in the system, incrementally. The purpose is to provide a more targeted list of changes for our backup systems to use to speed up the backup process.
Why? A Maven (or NPM) repository manager deals in tons of tiny files. When you build up terabytes of these files, the mere act of scanning the filesystem for changes takes hours, which can easily cause us to miss our recovery targets. This is a simple solution intended to avoid the cost of scanning for changed files.
Longer term, it may be better to build this into the filesystem / content microservice...or even use FileStorageEvents to push this behavior into a pipeline piece separated from everything (this should become possible). If we did that, we wouldn't have to have backup …
=> File change tracking

addons/path-mapped/common/src/main/java/org/commonjava/indy/pathmapped/inject/PathMappedMavenGACacheGroupRepositoryFilter.java, core/src/main/java/org/commonjava/indy/core/content/PathMaskChecker.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/fixture/ResultBufferingGroupRepoFilter.java
Fix for https://projects.engineering.redhat.com/browse/MMENG-1490.
The paths for promotion looks as follows ( including "/" at the very begining ):
```
/org/jboss/mod_cluster/mod_cluster-load-spi/1.4.3.Final-redhat-00001/mod_cluster-load-spi-1.4.3.Final-redhat-00001.jar
```
But the path mask pattern is:
```
r|org\/jboss\/mod_cluster\/.+\/1.4.3.Final-redhat-00001\/.+|
```
That regex does not match the path with the prefix "/", which prevents the downloading from brew.
=> Fix the path mask checker

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/IndyKojiContentProvider.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiTagInfoEntry.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/inject/KojiCacheProducer.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/inject/KojiTagInfoEntryMarshaller.java, addons/koji/common/src/main/resources/koji_taginfo.proto, addons/koji/common/src/test/java/org/commonjava/indy/koji/content/KojiTagMarshallerTest.java
The ProtoStream marshaller does not currently support the direct marshalling of ArrayList. Alternatively wrapping the list in a new class.
=> Wrap the kojiTagInfo list to a class for cache

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/IndyKojiContentProvider.java
Use the method getBasicCache to make sure to obtain the cache
from remote as default(e.g.: koji-tags), and return the embedded
one if there is no remote definition.
=> Fix to obtain the cache from remote as default

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java
This is to fix MMENG-1724 - Readonly hosted repositories prevent promotion.
The store caches a location object which is shared among threads (Ref to LocationUtils.toLocation). Unfortunately this object is not imutable. The flag 'readonly' is set to true/false back and forth, as in the try-finally block. This causes the problem where one promotion thread set it to false and process the deletion while another thread set it back to true and fail the first thread.
=> Fix deletion failure on readonly repo during promotion

addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/HostedMetadataRemergedOnPathPromoteToReadonlyHostedTest.java, api/src/main/java/org/commonjava/indy/model/galley/CacheOnlyLocation.java, api/src/main/java/org/commonjava/indy/util/LocationUtils.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java
In order to bypass the readonly during promotion, we have to create a non-readonly Location object. 
This is an amendment for a prev fix. What is the problem of prev fix? The answer is: we can not only override the Resource's method because the Location object can be use in very deep places, where indy try to delete the checksum transfer. At that moment, the resource object is different, so it can not bypass the readonly.
=> Use NonReadonlyLocation when need to bypass the hosted readonly permission

addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCassandra.java
=> Add an error message instead of throwing Exception for Cassandra based folo handling

addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/PackageMetadataGenerator.java
Fix the error when storing NPM metadata file to readonly repo. 
https://kibana.datahub.redhat.com/app/kibana#/doc/AWnupc913I7rbEp09huP/indy-logs-000115/log?id=AXpWi3v8XFv8eSDYvaF9&_g=h@44136fa
=> Fix the readonly issue when storing package metadata

models/core-java/src/main/java/org/commonjava/indy/model/core/io/StoreKeyDeserializer.java, models/core-java/src/main/java/org/commonjava/indy/model/core/io/StoreKeySerializer.java, models/core-java/src/test/java/org/commonjava/indy/model/core/io/ModelJSONTest.java, models/core-java/src/test/resources/model-io/hosted-with-storage-objkey.json, models/core-java/src/test/resources/model-io/hosted-with-storage-stringkey.json
We found that Indy StoreKeyDeserializer will only recongnize the
StoreKey with the pkgType:type:name format in json, and will ignore
any other format even if it is a valid json object of StoreKey. This
fix will also include the correct json object of StoreKey as correct
input.
=> Fix storekey deserialization to support object way

addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloNPMContentAccessResource.java, addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/change/PackageStoreListener.java, addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/DecoratorUtils.java, addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/NPMPackageMaskingTransferDecorator.java, addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/NPMStoragePathCalculator.java, addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/PackageMetadataGenerator.java, addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/group/PackageMetadataMerger.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDirectContentAccess.java, models/core-java/src/main/java/org/commonjava/indy/pkg/npm/model/NPMPackageTypeDescriptor.java
Fix for https://projects.engineering.redhat.com/browse/MMENG-1757, only the URLs end with `package.json` should be tailored.
After checking the logs, found that when retrieving the npm raw files such as the following two, the urls were tailored by mistake, 
from
```
@babel/helper-validator-identifier/7.10.4
@babel/helper-validator-identifier/-/helper-validator-identifier-7.10.4.tgz
```
to:
```
@babel/helper-validator-iden 
@babel/helper-validator-identifier/-/helper-validator-identifi 
```
that's why it complained the error `package not found`.
=> Fix the npm url handling

addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMRemoteMetadataContentDecorator_ProxyOriginTest.java, addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessHandler.java
If user request by the sidecar or gateway, we have to override the tarball url accordingly. We do this by passing a http header to Indy. 
@sswguo this also fix the npm hitting indy httproxy problem, when gateway is between.
=> Replace npm ENTRY_POINT_BASE_URI if proxy-origin presented

models/core-java/src/main/java/org/commonjava/indy/model/core/io/StoreKeyDeserializer.java, models/core-java/src/main/java/org/commonjava/indy/model/core/io/StoreKeySerializer.java, models/core-java/src/test/java/org/commonjava/indy/model/core/io/ModelJSONTest.java, models/core-java/src/test/resources/model-io/hosted-with-storage-objkey.json, models/core-java/src/test/resources/model-io/hosted-with-storage-stringkey.json
We found that Indy StoreKeyDeserializer will only recongnize the
StoreKey with the pkgType:type:name format in json, and will ignore
any other format even if it is a valid json object of StoreKey. This
fix will also include the correct json object of StoreKey as correct
input.
=> [Cherry-pick to maint]Fix storekey deserialization to support object way

addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMReadonlyHostedDeleteFileTest.java, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMReadonlyHostedDeleteMetadataTest.java, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMReadonlyHostedStoreFileTest.java, addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessResource.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java
Only when CHECK_CACHE_ONLY is true, we can bypass the readonly for hosted repo.
=> Allow force delte for npm metadata

addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMReadonlyHostedDeleteFileTest.java, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMReadonlyHostedDeleteMetadataTest.java, addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMReadonlyHostedStoreFileTest.java, addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessResource.java, core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java, core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java
This is used when npm meta is stale and we want to remove it manually. It has no immediate need, but it is low risk. We'd better cherry pick it to 2.5.x as well.
=> [Cherry-pick-to-maint] Allow force delte for npm metadata

addons/path-mapped/common/src/main/java/org/commonjava/indy/pathmapped/common/PathMappedController.java, addons/path-mapped/jaxrs/src/main/java/org/commonjava/indy/pathmapped/jaxrs/PathMappedResource.java
If user delete a repo or group, the pathmap/admin api will fail. like:
```
curl http://indy-indy-stage.apps.ocp-c1.prod.psi.redhat.com/api/admin/pathmapped/content/npm/group/build-17670/load-json-file/package.json
java.lang.NullPointerException
at org.commonjava.indy.pathmapped.jaxrs.PathMappedResource.get(PathMappedResource.java:140)
```
We need to avoid such because this api is meant to query/debug pathdb problems.
=> Fix api/admin/pathmap/content NPE when target repo is gone

models/core-java/src/main/java/org/commonjava/indy/model/core/io/StoreKeyDeserializer.java, models/core-java/src/main/java/org/commonjava/indy/model/core/io/StoreKeySerializer.java, models/core-java/src/test/java/org/commonjava/indy/model/core/io/ModelJSONTest.java, models/core-java/src/test/resources/model-io/hosted-with-storage-objkey.json, models/core-java/src/test/resources/model-io/hosted-with-storage-stringkey.json
We found that Indy StoreKeyDeserializer will only recongnize the
StoreKey with the pkgType:type:name format in json, and will ignore
any other format even if it is a valid json object of StoreKey. This
fix will also include the correct json object of StoreKey as correct
input.
=> [cherry-pick]Fix storekey deserialization to support object way

pom.xml
Upgraded from 1.1.0 to 1.5.1. This fixes `java.lang.NoClassDefFoundError: io/honeycomb/beeline/tracing/propagation/W3CPropagationCodec`
=> upgrade honeycomb to be compatible with o11yphant

db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/CassandraStoreDataManager.java, db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/RemoteKojiStoreDataCache.java, db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/StoreDataCacheProducer.java, subsys/infinispan/src/main/resources/infinispan.xml
This is for issue: https://issues.redhat.com/browse/MMENG-1932
Adding the temporary in-memory cache remote-koji-stores , to avoid to iterate the remote koji repositories under group brew-proxies from C*, the count of that type repo is 750+ in stage and 2300+ in prod, which slows the retrieve request down most, more details please ref the issue. thanks.
=> Add in-memory cache for remote koji stores

db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/CassandraStoreDataManager.java, db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/StoreDataStartupAction.java
The cache for remote store is an in-memory cache that should be populated at each startup.
=> Fix the startup of remote repo cache

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java, addons/koji/common/src/main/java/org/commonjava/indy/koji/data/KojiRepairManager.java
I found a lot of logs to check the repo when handling the expiration of the koji maven metadata, since we had introduced the specific query earlier, we can avoid the fullscan on repository.
=> Update to avoid the fullscan on the repository

pom.xml
Weft 1.20-SNAPSHOT include fix for the Locker.waitForLock dead lock issue.
=> Update weft version to 1.20-SNAPSHOT

core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java
I think we need to add this at the beginning of retrieve and generation. If the remote repo is not the right one for retrieving, there is also no need to try to generate content from it, avoid some loop checker.
=> Check path patterns before retrieving

db/common/src/main/java/org/commonjava/indy/db/common/DefaultArtifactStoreQuery.java, test/db/src/main/java/org/commonjava/indy/core/data/GroupDataManagerTCK.java
When checking the issue MMENG-2055, we found that the order of members of the group is not the ones as expected, Indy returns the non-group ones as first. for example: if the group `A` contains 1. `group_pnc-builds` and 2. `remote_mrrc-ga`, it should return the members in group `pnc-builds` first and then `remote_mrrc-ga`. Instead it returns the remote first and then the ones under group `pnc-builds`. The PR aims to fix it, recursing the group and adding its member first and then repeat the operation against next element. 
More details see: https://issues.redhat.com/browse/MMENG-2055
=> Fix the order of getting members in group

addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCache.java, addons/folo/common/src/test/java/org/commonjava/indy/folo/data/FoloRecordCacheTest.java, api/src/main/java/org/commonjava/indy/conf/InternalFeatureConfig.java
This is to fix MMENG-2025 (folo lost files). See details in JIRA. Although I am not sure why that happened, this is my best guess. This pr use pagination when querying from in-progress cache, add check if the size not match.
I also add a config to turn on/off query pagination.
=> Folo in-progress query use pagination

addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessHandler.java, addons/sli/src/main/java/org/commonjava/indy/sli/metrics/IndyGoldenSignalsMetricSetProvider.java, api/src/main/java/org/commonjava/indy/conf/InternalFeatureConfig.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/util/TransferCountingInputStream.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/util/TransferStreamingOutput.java, core/src/main/conf/conf.d/internal-features.conf, core/src/main/resources/default-internal-features.conf, models/core-java/src/main/java/org/commonjava/indy/IndyRequestConstants.java, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/CacheProducer.java, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/metrics/IspnCheckRegistrySet.java, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/metrics/IspnRegistrySetProvider.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/IndyDeployment.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/ResourceManagementFilter.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/TestAdminResource.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/ThreadContextFilter.java, subsys/trace/src/main/java/org/commonjava/indy/subsys/honeycomb/TraceManagerProducer.java
This provides a feature for testing, which when enabled will allow us to reset metrics on the running Indy instance, without rebooting. That will be useful when paired with the new statistical performance regression testing code elsewhere, so we can extract metrics that pertain ONLY to the test we just executed, and not require any external infrastructure for storing it.
I've also improved the latency-pause calculation, to remove file transfer times from upload / download actions from the overall latency we log in our traces. This should help us focus more on the in-code latency, and reduce noise from network sources, upstream servers, or downstream clients.
=> Enable RESET of metrics via REST. Improve latency pause calc for tracing

addons/pkg-npm/common/src/test/java/org/commonjava/indy/pkg/npm/content/group/PackageMetadataMergerTest.java, addons/pkg-npm/common/src/test/resources/metadata/package-3.json, addons/pkg-npm/model-java/src/main/java/org/commonjava/indy/pkg/npm/model/VersionMetadata.java
Checking the package metadata file:https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/deep-diff
It has different type for `DevDependencies`, let's update the value from String to Object to cover this.
=> Fix the npm metadata merge issue

pom.xml
Fix for the Hot Rod client retry issue, based on the comment of https://issues.redhat.com/browse/ISPN-10429, hotrod client retry issue was fixed in the version 9.4.17.Final. We will update it to 11.x in future which needs more changes in the codebase.
=> Update infinispan to 9.4.17.Final

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/ArchetypeCatalogGenerator.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/group/ArchetypeCatalogMerger.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/group/MavenMetadataMerger.java
Seems the archetype-catalog and maven-metadata merger missed some
type of the digesting files on group level merging.
=> Fix: Add missing digisting metadata files to merger

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/ArchetypeCatalogGenerator.java, addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/group/ArchetypeCatalogMerger.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/GroupArchetypeChecksumRequestTest.java
This is to fix MMENG-2323. We have two bugs in archetype generator. 
1. The toMergePath calculation is not right **for some cases**. For example, archetypes-catalog-2.2.0.fuse-sb2-7_10_0-00014-redhat-00001-archetype-catalog.xml.md5
The wrong toMergePath is used to iterate the member repos, and it get 0 match from members. So the content manager retrieve it from one member repo, which was wrong. In case indy got a .sha or md5 request, the safe way is just to strip off the checksum file extension.
2. In similar case, 'target.openOutputStream' will write merged content to 'archetype-catalog.xml.md5', and trigger the digest of itself and produce duplicate checksum, e.g, xx.md5.md5, etc. We need to change it to 'toMergeTarget.openOutputStream'
=> Fix maven archetype merge and checksum invalid issue

pom.xml
Galley 1.7-snapshot has a serious bug which cause files loss. The calculation of timeout has problem which return true for any files.
=> Revert Galley to 1.6

pom.xml
* jackson to 2.12.1 due to CVE-2020-25649
* swagger to 1.6.4 due to compatibility for jackson
=> Fix: upgrade jackson and swagger version

models/core-java/src/main/java/org/commonjava/indy/model/core/StoreKey.java
The following logs are from stage, which shows two transfers with the same uri and path but different hashcode, that causes the duplicated download jobs for the same transfer, let's use the name of StoreType to do hashcode instead.
```
Transfer uri: https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/
Transfer path: glob/-/glob-7.1.6.tgz
Transfer hashCode: 1913094049
----------------
Transfer uri: https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/
Transfer path: glob/-/glob-7.1.6.tgz
Transfer hashCode: 159836173
```
=> Use the name of the StoreType to do hashcode

addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/NPMPackageMaskingTransferDecorator.java, core/src/main/java/org/commonjava/indy/core/ctl/ContentController.java, pom.xml
And change some jsoup isBlank refer to commons-lang3 as jsoup should
only be used in ftests module
See: https://github.com/Commonjava/indy/security/dependabot/pom.xml/org.jsoup:jsoup/open
=> Fix: Upgrade jsoup to 1.14.2 by CVE warning

pom.xml
https://github.com/Commonjava/indy/security/dependabot/pom.xml/io.undertow:undertow-core/open
=> Fix: Upgrade undertow to 2.1.8 for CVE warning

pom.xml
https://github.com/Commonjava/indy/security/dependabot/pom.xml/org.jdom:jdom/open
Seems we don't need this jdom in our code.
=> Fix: remove jdom deps due to CVE warning

uis/layover/app/js/controllers.js, uis/layover/app/partials/group-list.html, uis/layover/app/partials/hosted-list.html, uis/layover/app/partials/remote-list.html
When listing repos on UI, it wants to get disabled stores so to show them by different style. 
However it calls SchedulerController.getDisabledStores which in turn calls 
`// TODO: This seems REALLY inefficient...
storeDataManager.getAllArtifactStores().forEach( (store)->{`  
As the old comment says, this is very slow, especially when we have huge numbers of repos. 
This pr disables it from UI. Until we fix the slowness, we have to disable this tiny UI feature, which costs a lot.
I tested on local, the listing is Ok.
=> [ui] not call StoreDisableSvc.setDisabledMap when listing repos

db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/CassandraStoreDataManager.java, models/core-java/src/test/java/org/commonjava/indy/model/model/RemoteRepositoryTest.java
The pathstyle is missing which caused the hashed path 404 issue.
=> Fix Cassandra store manager toArtifactStore pathstyle missing issue

pom.xml
Apple M1 env need this version >= 1.11.0 in order to pass the mvn build.
=> Update frontend plugin to 1.11.0

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionHelper.java
Placing the store query into for-loop causes big performance issue during promotion, since the store is same for each promotion, so let's move it out of for-loop. It may not a big issue before when we used ISPN, but it's the issue for cassandra. Especially when the number of paths is a larger one.
=> Fix the store query during promotion

db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/CassandraStoreDataManager.java, db/cassandra/src/test/java/org/commonjava/indy/cassandra/data/CassandraTCKFixtureProvider.java
Adding the in-memory cache for artifact store to avoid to frequently to query the store from cassandra during build and expiration, etc.
=> Add in-memory cache for artifact store

addons/folo/common/src/main/java/org/commonjava/indy/folo/data/DtxTrackingRecord.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCassandra.java
This is fix for [Indy is still producing partial tracking reports even though there are no restarts](https://issues.redhat.com/browse/MMENG-2546). 
We need to add the store_effect to primary key because sometimes a path appears in both DOWNLOADS and UPLOADS.
=> Add store_effect to cassandra folo primary keys

addons/folo/common/src/main/java/org/commonjava/indy/folo/data/DtxTrackingRecord.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCassandra.java
The (path,effect) may not be good enough for the primary keys. I am not sure whether Indy will download a same path from different remote repo during a build (like pom). As build scenario is unpredictable , it is safe to add the storeKey as primary key.
=> Add store_key to the cassandra folo PRIMARY keys

addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCassandra.java
Although this is not used on normal cases, we still need the deletion for testing purpose.
=> Allow cassandra Folo records deletion

addons/folo/common/src/main/java/org/commonjava/indy/folo/ctl/FoloAdminController.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/ctl/FoloConstants.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCassandra.java, addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloAdminResource.java
As suggested in JIRA, this pr is to query legacy Folo table. Two functions here: 1. get all legacy ids; 2. get legacy records by id. 
From user's perspective, the only change is "report/ids/{type}". By passing the "legacy" as the type, it will fetch the legacy ids. The api to get records by tracking-id does not change. The code will query the new table first, if not found, it will try the legacy table.
=> Add query for legacy folo table

addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCassandra.java
Sometimes one build may upload a same artifact more than once, thus we need to always override the prev record.
=> Alway override the prev folo records

addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloGenericContentAccessResource.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java
update the handler to allow generic proxy to request the content directly, that means without rewriting for cases `when path ends with '/index.html' or '/' `
=> Update checker before rewriting the request

db/common/src/main/java/org/commonjava/indy/db/common/DefaultArtifactStoreQuery.java
When migrating changes from indy-monolith to indy-repository-service,
I found a change in this DefaultArtifactStoreQuery will cause a
duplicated stores. So gave this fix to address.
=> Fix: avoid duplicate membering store in query

addons/folo/common/src/main/java/org/commonjava/indy/folo/change/FoloTrackingListener.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/ctl/FoloConstants.java, addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/content/GroupMetadataExcludedFromTrackingReportTest.java, addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/content/VerifyTrackedEntriesForNPMTest.java, addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloNPMContentAccessResource.java, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java
Fix for MMENG-2881, indy tracks the npm metadata with suffix `package.json`, which is wrong. I checked and found it just happens when client requests the metadata from group repo, the PR is to keep the origin path in EventMetadata and set it during tracking.
=> Fix the tracking path of npm metadata

addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/content/VerifyTrackedEntriesForNPMScopedPackageTest.java, addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloNPMContentAccessResource.java
The previous fix https://github.com/Commonjava/indy/pull/2059 does not cover the case for scoped npm package such as `@babel/code-frame`. Since it goes through another API which needs to change as well.
=> Fix the tracking path of scoped npm package

addons/content-browse/ftests/src/main/java/org/commonjava/indy/content/browse/ftest/StoreNPMThenListingDirTest.java, addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/NPMStoragePathCalculator.java
Indy appends package.json for NPM request, but for listing request, if the request is in the scoped level, it also appends package.json, like @babel/package.json, that is wrong.
=> Fix the NPM package listing

addons/pkg-npm/common/src/test/java/org/commonjava/indy/pkg/npm/content/VersionMetaReadTest.java, addons/pkg-npm/common/src/test/resources/metadata/pause-stream.json, addons/pkg-npm/model-java/src/main/java/org/commonjava/indy/pkg/npm/model/VersionMetadata.java, addons/pkg-npm/model-java/src/main/java/org/commonjava/indy/pkg/npm/model/converter/ObjectToLicenseConverter.java
This is to fix [MMENG-2775](https://issues.redhat.com/browse/MMENG-2775) where the deserialization failed if the NPM license has multiple values, like
"license": [
"MIT",
"Apache2"
]
I use a Jackson converter to handle that case.
=> Fix Cannot deserialize o.c.i.p.npm.model.License from Array value

addons/folo/common/src/main/java/org/commonjava/indy/folo/change/FoloTrackingListener.java
Fix the records for NPM requests twice, if user points the NPM registry to indy folo url `api/folo/track/$buildContentId/npm/remote/npmjs/`, the requests were through generic proxy and the records were stored twice, one with accessChannel `native` and another one with accessChannel `GENERIC_PROXY`.  The folo should be avoided if the request target is indy.
=> Avoid to tracking content twice if setting the NPM registry to Indy

bin/test-setup.sh
The test-setup.sh not work on Mac OS. I fixed one issue and it works well.
=> Fix test-setup.sh on Mac os

db/common/src/main/java/org/commonjava/indy/db/common/DefaultArtifactStoreQuery.java
Found that this DefaultArtifactStoreQuery logger output lots of
logs which are not very helpful in production, so downgrade them to
debug level.
=> Downgrade the logger

addons/content-browse/common/src/main/java/org/commonjava/indy/content/browse/ContentBrowseController.java, addons/content-browse/ftests/src/main/java/org/commonjava/indy/content/browse/ftest/StoreNPMThenListingDirTest.java
Still fix for MMENG-2719, it should not append package.json to browser requests, that should be just for `api/content`.
=> Fix the NPM listing

addons/content-browse/common/src/main/java/org/commonjava/indy/content/browse/ContentBrowseController.java
previously we check if the file is package.json on listing requests, it should filter the checksum files out as well.
=> hide the package.json and the checksum files

subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/ResponseHelper.java
As the [RFC 2616](https://www.ietf.org/rfc/rfc2616.txt) mentioned, _"If a message is received with both a Transfer-Encoding header field and a Content-Length header field, the latter MUST be ignored."_
So the fix is trying to avoid to set the above two headers together, if we set the `Content-Length` header explicitly, we should remove the `Transfer-Encoding` header.
=> Fix the response header

addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMMetadataTimeoutNoSchedulerTest.java, addons/sli/src/main/java/org/commonjava/indy/sli/metrics/IndyGoldenSignalsMetricSetProvider.java, deployments/cache-migrator/test-env/indy-env/conf.d/metrics.conf, pom.xml, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/metrics/IspnCheckRegistrySet.java, subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/metrics/IspnRegistrySetProvider.java
* commons-codec: 1.10 -> 1.15
* commons-compress: 1.19 -> 1.21
* archetype-catalog: 2.4 -> 3.2.1
* groovy: 2.2.1 -> 2.4.21
* Remove kafka-log-appender as useless
* Upgrade kafka-clients to 3.1.1 due to cve
* Upgrade infinispan to 9.4.24.Final
* o11yphant to 1.5-SNAPSHOT for cascading amqp-client upgrade.
=> Merge from 3.0.x for CVE fix

addons/dot-maven/common/src/main/java/org/commonjava/indy/dotmaven/DotMavenException.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloContentException.java, addons/implied-repos/model-java/src/main/java/org/commonjava/indy/implrepo/ImpliedReposException.java, api/src/main/java/org/commonjava/indy/IndyWorkflowException.java, api/src/main/java/org/commonjava/indy/action/IndyLifecycleException.java, api/src/main/java/org/commonjava/indy/data/IndyDataException.java, clients/core-java/src/main/java/org/commonjava/indy/client/core/IndyClientException.java, core/src/main/java/org/commonjava/indy/core/expire/IndySchedulerException.java, subsys/git/src/main/java/org/commonjava/indy/subsys/git/GitSubsystemException.java, subsys/groovy/src/main/java/org/commonjava/indy/subsys/template/IndyGroovyException.java
I think all indy related exception should inherit from "IndyException" for general purpose.
=> Fix: Let all indy related exceptions inherit from IndyException

addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/content/admin/BatchDeletionOfNPMPackagesTest.java, addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/NPMStoragePathCalculator.java
Fix the issue MMENG-3066 for `batch/delete` endpoint: if the request path is `path=/@redhat/infinispan`, indy deletes all the files/dirs under that, causing some of the  .tar files been deleted, this is caused by the missing step to append `package.json` for this type of the path.
=> Fix the file path for batch delete

pom.xml, subsys/cpool/src/main/conf/conf.d/connection-pools.conf, uis/layover/package-lock.json
We found that the agroal connection pool is reporting leak connection
for several times. As agroal has supported a new configuration of
"enhancedLeakReport" to tell more details of leaking problem, so this
will upgrade to use it
=> Fix: upgrade agroal to 1.16 to support enhancedLeakReport

clients/core-java/src/main/java/org/commonjava/indy/client/core/metric/ClientMetricsProducer.java
Recently the PNC team meets some CDI transitive deps missing problems when upgrades indy client libs. After checking that's caused by the new introduced client-side metrics collecting. This producer is addressing the problems. 
Now all producers are providing the beans with Alternative to avoid impact on main indy metrics producers. In future we will extract the indy-client lib into separate repos, then we can switch these producers to default
=> Fix: add a ClientMertricsProducer to solve CDI transistive deps missing problems

db/service/src/main/java/org/commonjava/indy/db/service/ServiceStoreDataManager.java, db/service/src/main/java/org/commonjava/indy/db/service/ServiceStoreQuery.java, db/service/src/test/java/org/commonjava/indy/db/service/ServiceStoreQueryTest.java
We found there is a big performance downgrade during integration test.
The most possible reason is bunch of the http requests for lots of
store query during artifacts downloading. So I add cache here to cache
some of the most commonly used queries.
=> Add Cache for ServiceStoreQuery

db/cassandra/src/main/java/org/commonjava/indy/cassandra/data/CassandraStoreDataManager.java
Not sure why the affected stores are not updated when some stores are removed. Let's adding this to avoid the NPE, which is happening on devel-master, blocking the promotion.
=> Fix the NPE issue for querying affected stores

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyResponseWriter.java
Looks .net client expects an extra CRLF in the response following [rfc2616](https://www.rfc-editor.org/rfc/rfc2616.html) .
`        generic-message = start-line
*(message-header CRLF)
CRLF
[ message-body ]
start-line      = Request-Line | Status-Line`
I had test this in generic proxy service, and this is added for production, since we still have not switch proxy on prod. thanks.
=> FIX: update the format of response based on rfc2616

boot/jaxrs/src/main/java/org/commonjava/indy/boot/jaxrs/IndyDeployer.java
let's try to ignore compressing the zip file for transporting to see if it's helpful for the issue of downloading the larger file.
=> Ignore the zip file on compressing

addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloGenericContentAccessResource.java
For MMENG-3129, some requests from client does not include the path, previously adding index.html as default does not work for some cases,  let's add another endpoint for this case. ( I checked the regex to see if there is an option to match it but looks no luck. )
=> Fix 404 for some generic proxy requests

db/service/src/main/java/org/commonjava/indy/db/service/ServiceStoreDataCacheUpdater.java, db/service/src/main/java/org/commonjava/indy/db/service/ServiceStoreDataManager.java, db/service/src/main/java/org/commonjava/indy/db/service/ServiceStoreQuery.java
We found that some query cache is not updated for store event related
stores, maybe it is caused by some missing cases we're not awaring.
Instead of the old update way, this time it will totall remove the
cache if the store event related stores are in the key of these
caches.
=> Clear service query cache for any store event related stores

db/service/src/main/java/org/commonjava/indy/db/service/ServiceStoreDataCacheUpdater.java, db/service/src/main/java/org/commonjava/indy/db/service/ServiceStoreQuery.java
We need to cleanup the affected groups' related orderedConcreteStoresInGroup query cache if the constituent store is updated.
For example: if the hosted repo is disabled, we also need to clean its affected groups' orderedConcreteStoresInGroup cache. After this, if Indy needs to retrieve this group's orderedConcreteStoresInGroup cache when generating the group maven-metadata.xml, enabled concrete stores will be fetching correctly from the query cache.
=> Fix cleanup the affected groups's related orderedConcreteStoresInGroup query cache

db/common/src/main/java/org/commonjava/indy/db/common/DefaultArtifactStoreQuery.java
Seems the getOrderedConcreteStoresInGroup with "enabled" parameter is
using a wrong refer of this "enabled" param
=> Fix: concrete in group store query missing enabled parameter

db/service/src/main/java/org/commonjava/indy/db/service/ServiceStoreDataCacheUpdater.java, db/service/src/main/java/org/commonjava/indy/db/service/ServiceStoreQuery.java
The two issues are both found in the stage log and oc2 integration testing
1. NPE: This should be caused by the repo was removed and cleanups were done already in another pod.
2. UnsupportedOperationException: This is caused by removing on the constituents unmodifiableList.
=> Fix NPE by store duplicated deletions and constituents UnsupportedOperationException issue

pom.xml
The o11yphant will have a fix for thread-safety of honeycomb span
implementation, which impact underlying weft libs
=> Update o11yphant to 1.6-SNAPSHOT

api/src/main/java/org/commonjava/indy/model/galley/CacheOnlyLocation.java, api/src/test/java/org/commonjava/indy/model/galley/CacheOnlyLocationTest.java
java.lang.ClassCastException: Cannot cast java.lang.String to java.lang.Integer
This error will occur when parsing repo "metadata" meta with number value.
Should also be fixed in the current Indy running version.
=> Fix ClassCastException during location metadata value type cast

addons/revisions/common/pom.xml, deployments/cache-migrator/pom.xml, deployments/launcher/pom.xml, deployments/standalone/launcher/pom.xml, embedder-tests/sonar-report/pom.xml, embedder/pom.xml, pom.xml, subsys/groovy/pom.xml
This upgrade is to address the java se 11 illegal-access warnings and some cve report
* Weld-se to 3.1.9: drop weld-se and use weld-se-shade
* Groovy-all to 3.0.13
=> Upgrade dependencies

addons/diagnostics/ftests/src/main/java/org/commonjava/indy/diags/ftest/DownloadDiagBundleTest.java, addons/folo/client-java/src/test/java/org/commonjava/indy/folo/client/IndyFoloContentClientModuleTest.java, addons/promote/client-java/src/test/java/org/commonjava/indy/promote/client/IndyPromoteClientModuleUrlsTest.java, addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/ContentBrowseRemoteIndyListingRewriteManager.java, clients/core-java/src/main/java/org/commonjava/indy/client/core/Indy.java, clients/core-java/src/main/java/org/commonjava/indy/client/core/IndyClientHttp.java, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java, subsys/service/src/main/java/org/commonjava/indy/subsys/service/IndyClientProducer.java
Indy client setup is too complex with bunch of constructors. It is
really prone to misunderstand which to use. Instead we should consider
to use builder pattern to reduce this complexity.
=> Feat: Add builder pattern for indy client setup

clients/core-java/src/main/java/org/commonjava/indy/client/core/Indy.java, clients/core-java/src/main/java/org/commonjava/indy/client/core/IndyClientHttp.java, clients/core-java/src/main/java/org/commonjava/indy/client/core/metric/ClientMetricManager.java, clients/core-java/src/main/java/org/commonjava/indy/client/core/metric/ClientTracerConfiguration.java, subsys/service/src/main/java/org/commonjava/indy/subsys/service/IndyClientProducer.java
Indy client now does not support otel tracing because it lacks the trace configuration for o11yphant. This PR added the configuration support and reuse Indy's trace config for service store data retrieving.
=> Feat: Add otel tracing support for indy-client

pom.xml, subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/IndyKafkaProducer.java, subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/KafkaObjectMapperSerializer.java
I found that the indy-subsys-kafka introduced quarkus deps. This is
not needed by indy-monolith now. So this commit did some refactor to
remove this deps.
=> Remove quarkus deps

pom.xml, subsys/groovy/pom.xml, subsys/groovy/src/test/java/org/commonjava/indy/subsys/template/ScriptEngineTest.java
Seems groovy-all 3.0.13 introduced a lot of groovy deps which we will
not use, so this pr just introduced exactly what we needed for our
groovy usage.
=> Optimize groovy deps

addons/pom.xml, deployments/launcher/pom.xml, embedder-tests/sonar-report/pom.xml, embedder/pom.xml, pom.xml, subsys/pom.xml
As revision is deprecated in new indy releases, I'll remove it from current maven dependency trees, but just leave all codes there for a while in coming releases.
=> Remove revision addon

addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/report/RecalculateMissingChecksumForTrackingRecordTest.java
Not sure if this it test always failed because of env issue. Re-enable
to have a test.
=> Re-enable RecalculateMissingChecksumForTrackingRecordTest

pom.xml
I found that the indy-subsys-kafka introduced quarkus deps. This is  not needed by indy-monolith now. So this commit did some refactor to  remove this deps.
=> [cherry-pick]Remove quarkus deps

addons/content-browse/ui/.babelrc, addons/content-browse/ui/package-lock.json, addons/content-browse/ui/package.json, pom.xml, uis/layover/package-lock.json, uis/layover/package.json, uis/layover/webpack.config.js
Seems we're really running out of date for bunch of the node & npm deps, so:
* Node -> 18.12.1
* NPM -> 9.4.0
* webpack -> 5.75.0
* webpack-cli -> 5.0.1
* webpack-dev-server -> 4.11.1
* react -> 16.14.0
* babel -> 7.20.x
* babel-loader -> 9.1.2
=> UI deps upgrade

addons/schedule/common/src/test/java/org/commonjava/indy/schedule/ScheduleTest.java, pom.xml
I checked out 3.0.2, and did below on my local 3.1.x branch.
git merge 3.0.2 -X ours
This merged all 3.0.2 diff to 3.1 so we don't lose anything. But if files conflict, it takes 3.1 code.
Then I manually fix the galley version.
=> Merge 3.0.2 recent changes to 3.1.x 

addons/content-browse/ui/package-lock.json, addons/content-browse/ui/package.json, addons/content-browse/ui/webpack.dev.config.js, addons/content-browse/ui/webpack.prod.config.js, pom.xml
* Roll back node version to 16.x for some compatible issue in centos7 env
* Avoid the generation of app_bundle.js.LICENTSE.txt
=> Fix for node & npm issues

addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/AbstractPromoteRequest.java
Adding the trackingId to promote request is backward compatible. PNC can set it when they are ready. Same change is made on promote service side https://github.com/Commonjava/indy-promote-service/pull/61
=> Add trackingId to PromoteRequest

subsys/http/src/main/java/org/commonjava/indy/subsys/http/util/UserPass.java
Indy httproxy log print user token like below. It is security leak.
`[INFO ] [PROXY-GET http://indy-admin.psi.redhat.com/api/folo/track/build-AYEGCYVZWLYAC/npm/group/shared-imports+yarn-public/semver/-/sem
ver-5.7.1.tgz HTTP/1.1] o.c.indy.subsys.http.util.UserPass no no - userpass is: 'build-AYEGCYVZWLYAC+tracking:eyJhbGc
`
This pr fix it.
=> Fix user token leak

addons/content-browse/pom.xml, addons/event-audit/common/pom.xml, addons/event-publisher/common/pom.xml, addons/folo/client-java/pom.xml, addons/folo/common/pom.xml, addons/koji/ftests/pom.xml, addons/pom.xml, deployments/launcher/pom.xml, embedder-tests/sonar-report/pom.xml, embedder/pom.xml, ftests/core/pom.xml, pom.xml, rest/api/src/test/java/org/commonjava/indy/rest/apigen/SwaggerExportTest.java
The content browse API is needed for content listings retrieving by
both user side and UI service side, so still need to be in content
service
=> Add content-browse API back

subsys/http/src/main/java/org/commonjava/indy/subsys/http/IndyHttpProvider.java
This PR will remove the trace injection into galley through http
client from Indy, because this http is serving for galley http
functions which are used for external http communication(e.g. remote
artifacts download). I don't think we need to start a tracing span on
this type of work.
=> Remove the trace using for indy http injection for galley

clients/core-java/pom.xml, pom.xml, subsys/trace/pom.xml, subsys/trace/src/main/conf/conf.d/trace.conf, subsys/trace/src/main/java/org/commonjava/indy/subsys/trace/TraceManagerProducer.java, subsys/trace/src/main/java/org/commonjava/indy/subsys/trace/config/IndyTraceConfiguration.java
As we start to use opentelemetry for tracing, the honeycomb native usage is deprecated and should be removed
=> Remove usage of o11yphant-trace-honeycomb

embedder/pom.xml, embedder/src/main/resources/indy-version.properties
The indy-version.properties is used to provide indy versioning info
through /api/stats/version-info API
=> Add back the indy-version.properties generation

pom.xml
Update path-mapped-storage to 2.5 that include:
1. Extend file timeout for accessing
2. Copy entry with specified creation and expiration
3. Safe storage gc
=> Update galley to 1.15 and pathmap to 2.5

addons/folo/common/src/main/java/org/commonjava/indy/folo/conf/FoloConfig.java
I checked the logs of stage and prod, found that this config ref the wrong value and it does not take effect at all. That means indy monolith still hit the folo db to create the records as well as tracking service. This may have no impact on the folo records, but it absolutely brings duplicate loads against folo table.
=> Fix the setting of recordingEnabled

addons/folo/common/src/main/java/org/commonjava/indy/folo/conf/FoloConfig.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/DtxTrackingRecord.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloCacheProducer.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloContentException.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloFileTypes.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloFiler.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloInprogressCache.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloProducer.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecord.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCache.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCassandra.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloSealedCache.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloStoreToCassandra.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloStoretoInfinispan.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/idxmodel/StoreKeyFieldBridge.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/idxmodel/TrackedContentEntry2StringMapper.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/idxmodel/TrackedContentEntryTransformer.java, addons/folo/common/src/main/java/org/commonjava/indy/folo/data/idxmodel/TrackingKey2StringMapper.java, pom.xml
* commonjava -> 18
* gson -> 2.9.1
* undertow -> 2.2.26.Final
* Resteasy jaxrs-api -> splitted and set to 3.0.12.Final
* Resteasy async-servlet -> splitted and set to 3.0.19.Final
* logback -> 1.2.12
* jackson -> 2.15.2
And also marked some folo api to deprecated
=> Bump deps version

pom.xml, subsys/jaxrs/pom.xml, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/keycloak/AuthConfig.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/keycloak/BasicAuthenticationOAuthTranslator.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/keycloak/IndyIdentityManager.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/keycloak/KeycloakDeploymentProvider.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/keycloak/SecurityResource.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/JwtTokenUtils.java, subsys/jaxrs/src/main/resources/default-auth.conf
As agreement, indy introduces the endpoint to provide the token which has longer lifespan for maven build, and still handle off the authentication to SSO if this validation failed.
=> Enable the token authentication locally for builder

deployments/cache-migrator/test-env/indy-env/conf.d/kafka.conf, subsys/kafka/pom.xml, subsys/kafka/src/main/conf/conf.d/kafka.conf, subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/IndyKafkaProducer.java, subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/boot/KafkaStreamBooter.java, subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/conf/KafkaConfig.java, subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/handler/PromoteServiceEventHandler.java, subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/trace/TracingKafkaClientSupplier.java
During testing I found that the store event can not be received
correctly through Kafka. After checking, found the reason is the
KafkaStream is not set up correctly. It should be started with a long
running state but not close immediately. So this PR makes it close in
shutdown action but not immediately
And add config to turn on/off kafka tracing
=> [cherry-pick] Fix: Kafka store event can not be received correctly

embedder/src/test/resources/logback-test.xml, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/StoreFileWithQueryParamTest.java, pom.xml
Update galley to support 'path+query' base64 encoding. This is for [MMENG-3880](https://issues.redhat.com/browse/MMENG-3880). 
Add one ftest 'StoreFileWithQueryParamTest'. It uses base64 encoded path to retrieve artifact.
=> Update galley to 1.16-SNAPSHOT to support path+query base64 encoding

pom.xml
Seems keycloak 22.0.3 has issues with our authentication.
=> Revert "Bump org.keycloak:keycloak-core from 17.0.1 to 22.0.3"

api/src/main/java/org/commonjava/indy/conf/UIConfiguration.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/IndyDeployment.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/ui/AbstractUIServlet.java, subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/ui/UIServlet.java, subsys/jaxrs/src/main/resources/default_index.html
When UI for indy is disabled, we should not let the request to root
path return a simple 404. Instead, we should provide a simple UI page
to tell that the server is still available.
=> Add simple response for disabled UI root

pom.xml
The lib 2.6-SNAPSHOT has the fix to re-partition the reclaim table by hour-of-day.
=> Update pathmappedStorageVersion to 2.6-SNAPSHOT

pom.xml
This is to get rid of Critical | dom4j:dom4j | 1.6.1
=> Update hibernateVersion to 5.10.13.Final

pom.xml
Found some ClassNotFound exception after upgrade keycloak to 22.0.1,
so roll back
=> revert keycloak version to 17.0.1

addons/path-mapped/common/src/main/java/org/commonjava/indy/pathmapped/inject/PathMappedGroupRepositoryFilter.java
Fix the issue that the members of the generic http group repo is null, causing the query against host is missing.
=> Fix the empty checker

addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/PackagePath.java
When I test promote service I hit "missing property" error of 'PackagePath.isScoped'. I corrected the name according to bean standard, and the err is gone. 
That class is copied from Indy. I guess we will hit the same issue in the future, e.g, when upgrading to newer dependency lib. So I port the fix here.
=> Update field name PackagePath.scoped

addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessHandler.java, addons/pkg-npm/model-java/src/test/java/org/commonjava/indy/pkg/npm/model/PackageMetadataTest.java
It looks like Jackson 2.15 introduced a max length for a single string value inside of the JSON document which defaults to 20 million. We need to enlarge this sort of limitation, or the following version and tarball stream writing out would have trouble since no proper JSON node data would be extracted and constructed for use.
See detail on https://issues.redhat.com/browse/MMENG-4057
=> Fix Jackson max length limitation issue for npm package metadata

subsys/service/src/main/java/org/commonjava/indy/subsys/service/IndyClientProducer.java, subsys/service/src/main/java/org/commonjava/indy/subsys/service/config/RepositoryServiceConfig.java, subsys/service/src/main/java/org/commonjava/indy/subsys/service/keycloak/KeycloakTokenAuthenticator.java
Sometimes the indy hit 401 error when sending request to repo service. This pr add a config "keycloak.auth.refresh-token-time-skew" to avoid sending soon-to-be-expired token.
fyi, Quarkus has similar config as 'quarkus.oidc.token.refresh-token-time-skew'.
=> Add repo service config refresh-token-time-skew

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java, addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/GroupMetadataMergeWithHangRemoteTest.java
1. Add Warning log output for missing metadata download and generation, and overview output for group master metadata generation failure.
2. Lower the waiting lock time slightly for metadata generation(from 5 to 4 mins).
3. Add ftest for broken remote(slow response, timeout, hang) during group metadata merge.
=> Add log output for maven metadata merge and ftest for hang remote meta test

bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java
Ticket: https://issues.redhat.com/browse/MMENG-4141
=> Fix the HEAD request to avoid reading file for checksum digest

core/src/main/conf/conf.d/durable-state.conf, core/src/main/java/org/commonjava/indy/core/conf/IndyDurableStateConfig.java, core/src/main/resources/default-durable-state.conf, core/src/test/java/org/commonjava/indy/fixture/MockTestProvider.java, core/src/test/resources/META-INF/beans.xml, db/memory/src/main/java/org/commonjava/indy/mem/data/MemoryStoreDataManager.java, db/pom.xml, db/service/src/main/java/org/commonjava/indy/db/service/StoreDataManagerProvider.java, embedder-tests/sonar-report/pom.xml, embedder/pom.xml, ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/StoreReverseMapMigrationTest.java, pom.xml, rest/api/src/test/java/org/commonjava/indy/rest/apigen/SwaggerExportTest.java, subsys/groovy/src/test/java/org/commonjava/indy/subsys/template/fixture/TestProvider.java
This indy-db-infinispan module is not used. But ftests still depends on it, so it needs to do some changes to remove dependency in ftests.
=> Remove indy-db-infinispan module

pom.xml
This reverts commit 7ae38f9a4192d6f45db090391e742d3c926288ff.
To be consistent with indy-client of the o11yphant version.
=> Revert "Update o11yphant to 1.9.2-SNAPSHOT"

subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/boot/KafkaStreamBooter.java, subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/conf/KafkaConfig.java
Pls see https://issues.redhat.com/browse/MMENG-4133 comment for the detailed explanation.
=> Add reconnect backoff config for kafka stream to avoid repeatedly connecting to host in a tight loop.

pom.xml, subsys/service/src/main/java/org/commonjava/indy/subsys/service/IndyClientProducer.java
Because indy-client 3.4.0-SNAPSHOT has removed the o11yphant deps,
this needs some code change in Indy side.
=> Use indy-client 3.4.0-SNAPSHOT

.github/workflows/maven-build.yml
Ok, seems the fix is not working as expected. Reverted.
This reverts commit 1462f846f498e662dc3acc4fd52c2ad97fe569f6.
=> Revert "Fix github action "verify with maven" to bypass in merged phase"

api/src/main/java/org/commonjava/indy/content/IndyPathGenerator.java, bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/GenericContentAccessResource.java, ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/StoreFileAndVerifyRootFileInGenericRepoTest.java
This is for [MMENG-4193](https://issues.redhat.com/browse/MMENG-4193)
The legacy approach of storing files downloaded via Indy generic http proxy was to reuse the path from remote server. However if there was root of the server requested (path = "/"), there seems to be no way to request that file from the generic-http hosted repository.
In this pr, a special handling is added to handle the "/" as filepath.
=> Handle root as a special file in generic-http repo

subsys/cassandra/src/main/java/org/commonjava/indy/subsys/cassandra/CassandraClient.java, subsys/cassandra/src/main/java/org/commonjava/indy/subsys/cassandra/config/CassandraConfig.java
Use ConstantReconnectionPolicy instead of exponential policy, see https://issues.redhat.com/browse/MMENG-4231.
=> Update Cassandra reconnect policy and default delay value

db/common/src/main/java/org/commonjava/indy/db/common/AbstractStoreDataManager.java, db/service/src/main/java/org/commonjava/indy/db/service/ServiceStoreDataManager.java
This is for [MMENG-4245](https://issues.redhat.com/browse/MMENG-4245) Indy was very slow to add a remote repository from Brew into group brew-proxies
Change 1. clean the ServiceStoreDataManager's store cache when a store is updated
I override the postStore method in ServiceStoreDataManager.
Change 2. update group changelog when the group is updated. For example, the current group brew-proxies still shows the oldest message. 
`{
"type" : "group",
"key" : "maven:group:brew-proxies",
"metadata" : {
"changelog" : "Create store maven:group:brew-proxies"
},...`
This pr update the changelog accordingly.
=> Update changelog and clean cache when group is updated

core/src/main/java/org/commonjava/indy/core/content/DefaultContentDigester.java
Fixing the issue that md5 files not in the static group, ref: https://issues.redhat.com/browse/MMENG-4250
When we publish FileEvent via Kafka, we need to calculate the checksum, but that picks CALCULATE_NO_WRITE, which means there is no checksum files generated at all, and the info is cached. Then when user request the checksum files, it says it exists as the cache value but actually there is no file in storage, which cause the failure as the jira issue mentioned: 
`Message: Path io/dropwizard/metrics/metrics-jmx/4.2.28/metrics-jmx-4.2.28.jar.md5 is not available in store`
=> Clear the metadata cache when setting FORCE_CHECKSUM_AND_WRITE

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java
Big amount of WARN found as below. 
`[WARN ] [maven-metadata-generator-12] o.c.i.p.m.c.MavenMetadataGenerator$Proxy$_$$_WeldSubclass no 172.40.1.72 - Transfer maven:remote:koji-org.wildfly.common-wildfly-common-1.2.0.Beta1_redhat_1-1:com/test/rest-to-jpa-update/1.0.0-SNAPSHOT/maven-metadata.xml not existed during maven metadata generator downloadMissing.`
This fix reduces the download from stores by checking the pattern mask first (especially for koji remote repos).
=> Add checkMask in maven metadata generator downloadMissing

bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/util/TransferStreamingOutput.java
Trying to fix MMENG-4207 `Inconsistent large downloads`
Adding the flush ensures that all the data is sent to the client after the copy is complete. Without an explicit flush(), some data might remain in the buffer and not be sent until it's full.
=> Add flush after copy during downloads

bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/util/TransferStreamingOutput.java
Reverts Commonjava/indy#2460
which will cause: write transfer error: stream was reset: CANCEL: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
=> Revert "Add flush after copy during downloads"

db/service/src/main/java/org/commonjava/indy/db/service/ServiceStoreDataManager.java
As subject.
In test, I found the caller's changelog was overridden by the default message. This pr fix it.
=> Use user changelog if present

subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/RestInterceptor.java
This is for [MMENG-4299](https://issues.redhat.com/browse/MMENG-4299) Downloads timing out hawtio-example-springboot-log4j2-4.1.0.redhat-00015.
=> Log the entry/end for each request and the elapsed time

addons/pkg-npm/model-java/src/main/java/org/commonjava/indy/pkg/npm/model/Directories.java, addons/pkg-npm/model-java/src/test/java/org/commonjava/indy/pkg/npm/model/VersionMetadataTest.java
=> Fix the incompatible issue on parsing npm version

core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java
Issue: https://issues.redhat.com/browse/MMENG-4447
- Added the `PathMaskChecker` before doing list in group level, avoid to scan all the members for each path.
=> Add PathMaskChecker on list in group level

addons/koji/common/src/test/java/org/commonjava/indy/koji/util/PathMaskCheckerTest.java, core/src/main/java/org/commonjava/indy/core/content/PathMaskChecker.java
The PR tries to extract the groupId path from the metadata file pattern, and using the groupId path to match with the specific path to filter the remote repos, especially the koji repos.  
For those repos without the metadata file patterns, will still follow the previous process.
=> Update PathMaskChecker for Directory List
