contrib/github/gh_repo.sh

Allows the sync operation to execute across multiple repos in the users nominated workspace.

Fixed directory changes to WORKSPACE

---

core/src/main/java/org/commonjava/aprox/core/expire/AproxScheduleListener.java

...in case when the trigger is not found by scheduler by the triggerKey.

Avoid potential NPE

---

.travis.yml
addons/dot-maven/common/src/main/java/org/commonjava/aprox/dotmaven/inject/DotMavenProvider.java
addons/dot-maven/common/src/main/java/org/commonjava/aprox/dotmaven/util/SettingsTemplate.java
addons/dot-maven/common/src/main/java/org/commonjava/aprox/dotmaven/webctl/DotMavenService.java
addons/dot-maven/common/src/main/java/org/commonjava/aprox/dotmaven/webctl/RequestInfo.java
addons/dot-maven/common/src/main/resources/templates/settings.xml.groovy
addons/dot-maven/ftests/pom.xml
addons/dot-maven/ftests/src/main/java/org/commonjava/aprox/dotmaven/settings/AbstractSettingsTest.java
addons/dot-maven/ftests/src/main/java/org/commonjava/aprox/dotmaven/settings/SettingsGeneratedForRemoteRepoTest.java
addons/dot-maven/jaxrs/src/main/java/org/commonjava/aprox/dotmaven/jaxrs/DotMavenDeploymentProvider.java
addons/dot-maven/jaxrs/src/main/resources/META-INF/beans.xml
addons/dot-maven/pom.xml
clients/core-java/src/main/java/org/commonjava/aprox/client/core/AproxClientHttp.java
clients/core-java/src/main/java/org/commonjava/aprox/client/core/helper/HttpResources.java
embedder-tests/easyprox/pom.xml
embedder-tests/savant/pom.xml
embedders/easyprox/pom.xml
embedders/savant/pom.xml
pom.xml
subsys/jaxrs/src/main/java/org/commonjava/aprox/bind/jaxrs/AproxDeployment.java
uis/layover/src/main/js/app/index.html

Also adding small ftest suite for dotMaven

fixing dotMaven and updating parent/bom versions.

---

addons/depgraph/jaxrs/src/main/java/org/commonjava/aprox/depgraph/jaxrs/GraphResource.java

The affected methods were reindex, errors, incomplete and variable.
They were all suffering from the same problems
* there was no slash expected/allowed after the method name, so one had to use for example /errorscommons-lang/commons-lang/2.6
* the value used / as separator between groupId, artifactId and version, but the called methods expected standard GAV with colons
* when no value passed the parameter was an empty string, but the called methods expected null

Fix reading of GAVs from URLs in GraphResource methods

---

docs/docker.md
docs/index.md
docs/revisions-addon.md
docs/traditional-install.md

Changed docker article to reference this, and adding a reference to it on the traditional install article.

Adding documentation page for revisions add-on

---

addons/depgraph/common/src/main/java/org/commonjava/aprox/depgraph/dto/WebPomDTO.java
addons/depgraph/common/src/main/java/org/commonjava/aprox/depgraph/rest/RenderingController.java
addons/depgraph/common/src/main/java/org/commonjava/aprox/depgraph/util/ConfigDTOHelper.java
addons/depgraph/common/src/test/java/org/commonjava/aprox/depgraph/dto/WebPomDTOTest.java
addons/depgraph/jaxrs/src/main/java/org/commonjava/aprox/depgraph/jaxrs/render/GraphRenderingResource.java
pom.xml

Rename every related method and class to contain pom instead of bom in
its name which is more accurate now.

Adjust BOM rendering method to optionally render simple pom

---

addons/autoprox/ftests/pom.xml
addons/folo/common/src/main/java/org/commonjava/aprox/folo/change/FoloTrackingListener.java
addons/folo/ftests/pom.xml
addons/folo/ftests/src/main/java/org/commonjava/aprox/folo/ftest/report/AbstractTrackingReportTest.java
addons/folo/ftests/src/main/java/org/commonjava/aprox/folo/ftest/report/RetrieveFileAndVerifyInTrackingReportTest.java
addons/folo/ftests/src/main/java/org/commonjava/aprox/folo/ftest/report/RetrieveFileFromGroupAndVerifyInTrackingReportTest.java
addons/folo/ftests/src/main/java/org/commonjava/aprox/folo/ftest/report/StoreFileViaGroupAndVerifyInTrackingReportTest.java
addons/folo/jaxrs/src/main/java/org/commonjava/aprox/folo/bind/jaxrs/FoloContentAccessHandler.java
addons/httprox/common/src/test/java/org/commonjava/aprox/httprox/HttpProxyTest.java
addons/httprox/ftests/src/main/java/org/commonjava/aprox/httprox/Propagate500As502ErrorTest.java
addons/implied-repos/ftests/pom.xml
clients/core-java/src/main/java/org/commonjava/aprox/client/core/AproxResponseErrorDetails.java
core/src/main/java/org/commonjava/aprox/core/content/DefaultContentManager.java
core/src/main/java/org/commonjava/aprox/core/content/DefaultDownloadManager.java
core/src/main/java/org/commonjava/aprox/core/ctl/ContentController.java
embedder-tests/easyprox/pom.xml
embedder-tests/pom.xml
embedder-tests/savant/pom.xml
ftests/common/pom.xml
pom.xml
test/fixtures-core/pom.xml

Also fixing leak of aprox-booter-api from various test fixtures, etc.

fixing tracking of uploads via group in folo, and adding ftests to folo

---

addons/depgraph/client-java/src/main/java/org/commonjava/aprox/depgraph/client/DepgraphAproxClientModule.java
addons/folo/client-java/src/main/java/org/commonjava/aprox/folo/client/AproxFoloAdminClientModule.java
addons/folo/common/src/main/java/org/commonjava/aprox/folo/ctl/FoloAdminController.java
addons/folo/common/src/main/java/org/commonjava/aprox/folo/data/FoloFileTypes.java
addons/folo/common/src/main/java/org/commonjava/aprox/folo/data/FoloFiler.java
addons/folo/common/src/main/java/org/commonjava/aprox/folo/data/FoloRecordCache.java
addons/folo/common/src/test/java/org/commonjava/aprox/folo/data/FoloRecordCacheTest.java
addons/folo/common/src/test/java/org/commonjava/aprox/folo/data/FoloRecordManagerTest.java
addons/folo/ftests/src/main/java/org/commonjava/aprox/folo/ftest/content/AbstractFoloContentManagementTest.java
addons/folo/ftests/src/main/java/org/commonjava/aprox/folo/ftest/content/admin/DownloadFromTrackedAndRetrieveInRepoZipTest.java
addons/folo/jaxrs/src/main/java/org/commonjava/aprox/folo/bind/jaxrs/FoloAdminHandler.java
ftests/common/src/main/java/org/commonjava/aprox/ftest/core/AbstractAproxFunctionalTest.java
subsys/jaxrs/src/main/java/org/commonjava/aprox/bind/jaxrs/util/ResponseUtils.java
subsys/jaxrs/src/main/java/org/commonjava/aprox/bind/jaxrs/util/TransferStreamingOutput.java

[Fixes #215] Implementing repo.zip download for tracking record content

---

pom.xml

...to get inherited and mixin fields in paths results.

Update deps to latest snapshots

---

api/src/main/java/org/commonjava/indy/model/galley/RepositoryLocation.java
models/core-java/src/main/java/org/commonjava/indy/model/core/AbstractRepository.java
models/core-java/src/main/java/org/commonjava/indy/model/core/RemoteRepository.java
uis/layover/src/main/js/app/js/services.js
uis/layover/src/main/js/app/partials/includes/hosted-view.html
uis/layover/src/main/js/app/partials/includes/remote-view.html
uis/layover/src/main/js/app/partials/remote-edit.html
uis/layover/src/main/js/app/partials/remote-list.html

Add allowsSnapshots and allowsReleases to remote repositories to allow
metadata filtering based on these flags.

Add content flags to remote repositories

---

uis/layover/src/main/js/app/js/controllers.js
uis/layover/src/main/js/app/partials/remote-list.html

Also making the listing formatting prettier.

Fix #275: Remote repositories listing is missing capabilities

---

.gitignore

Got un-tracked notification for building files in maven build, so add them to gitignore

add eclipse project files and missing idea files to gitignore

---

addons/folo/model-java/src/test/java/org/commonjava/indy/folo/dto/TrackedContentEntryDTOTest.java
subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/ResourceManagementFilter.java

...coming from resource cleanup in a finally block of ResourceManagementFilter

Fixing DTO imports and attempting to head off any exceptions in ResourceManagementFilter

---

core/src/main/resources/templates/text_html/directory-listing.groovy
filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java
pom.xml

Follows https://github.com/Commonjava/galley/pull/99

Remote repo contents filtering

---

ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/AbstractContentTimeoutWorkingTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/AbstractMetadataTimeoutWorkingTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/CacheFirstTimeoutWorkingTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/MetadataFirstTimeoutWorkingTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/StoreAndVerifyJarViaDirectDownloadTest.java

Adding test to make sure jar content upload/download works.
Also fixing some license headers.

ftest attempting to replicate #294

---

addons/autoprox/common/src/main/java/org/commonjava/indy/autoprox/data/AutoProxDataManagerDecorator.java
addons/autoprox/common/src/test/java/org/commonjava/indy/autoprox/fixture/TestAutoProxyDataManager.java
addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexManager.java
addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexObserver.java
addons/dot-maven/common/src/main/java/org/commonjava/indy/dotmaven/data/StorageAdvisor.java
addons/dot-maven/common/src/main/java/org/commonjava/indy/dotmaven/store/sub/ArtifactStoreSubStore.java
addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidationTools.java
addons/setback/common/src/main/java/org/commonjava/indy/setback/data/SetBackSettingsManager.java
api/src/main/java/org/commonjava/indy/content/IndyLocationExpander.java
api/src/main/java/org/commonjava/indy/data/StoreDataManager.java
core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java
core/src/main/java/org/commonjava/indy/core/ctl/NfcController.java
db/memory/src/main/java/org/commonjava/indy/mem/data/MemoryStoreDataManager.java
test/db/src/main/java/org/commonjava/indy/core/data/GroupDataManagerTCK.java

Supercedes PR #309 by resolving merge conflicts I introduced.

Fixing merge problems with PR #309 after my regression and test bugfix-a-thon

---

addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexObserver.java
api/src/main/java/org/commonjava/indy/change/event/ArtifactStoreEnablementEvent.java
db/memory/src/main/java/org/commonjava/indy/mem/data/MemoryStoreDataManager.java
embedders/savant/src/test/resources/logback.xml

Adding some logging to investigate group merged content handling

---

addons/folo/client-java/src/main/java/org/commonjava/indy/folo/client/IndyFoloAdminClientModule.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/change/FoloTrackingListener.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/ctl/FoloAdminController.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCache.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/data/idxmodel/AffectedStoreRecordKey.java
addons/folo/common/src/test/java/org/commonjava/indy/folo/data/FoloRecordCacheTest.java
addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/report/AbstractCacheReportTest.java
addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/report/CachedReportWhenDeleteStoreTest.java
addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/report/CachedReportWhenDeleteTransferTest.java
addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloAdminResource.java
addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/AffectedStoreRecord.java
addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/TrackedContent.java
addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/TrackedContentEntry.java
addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/TrackedContentRecord.java
addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/RetrievedPomInAlwaysOnTrackingReportTest.java
addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/RetrievedPomInSuffixTrackingReportTest.java

fix the ftest failure in httprox with new rest layer entity.

In Indy's Folo add-on, compute checksum, etc. for file usage up front

---

addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexCache.java
addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexCacheProducer.java
addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexManager.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloCacheProducer.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloInprogressCache.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCache.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloSealedCache.java
addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloContentAccessResource.java
addons/folo/model-java/pom.xml
addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/StoreKeyFieldBridge.java
addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/TrackedContentEntry.java
addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/TrackedContentEntryTransformer.java
addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/TrackedContentRecord.java
addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/TrackingKey.java
subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/inject/CacheProducer.java
subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/inject/qualifer/IndyCacheManager.java
subsys/infinispan/src/main/resources/infinispan.xml

In PR, I found that it needs a new FieldBridge for TrackedContentEntry's  storeKey field as it is not marked as indexed. And I extract all producer of the cache to each addon modules which I think it is better to make them with their cache consumers.

NOS-437 and small refactor for NOS-131

---

addons/koji/common/src/main/resources/scripts/stores/koji-repo-creator.groovy

For some reason the script is duplicated there... Addition to #374

Fix MissingPropertyException in brew pull once again

---

addons/koji/common/src/main/data/scripts/stores/koji-repo-creator.groovy
addons/koji/common/src/main/resources/scripts/stores/koji-repo-creator.groovy

I was to lazy to set-up the brew pull env to test the fixed script and
this is what I get. But I checked the rest closely now and it seems it
is all in ok now. Hopefully a new deployment will confirm that.

Fix another MissingPropertyException - originatingPath

---

addons/koji/common/src/main/data/scripts/stores/koji-repo-creator.groovy
addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java
addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiRepositoryCreator.java
addons/koji/common/src/main/resources/scripts/stores/koji-repo-creator.groovy

Fix another MissingPropertyException - eventMetadata

---

addons/koji/common/src/main/data/scripts/stores/koji-repo-creator.groovy
addons/koji/common/src/main/resources/scripts/stores/koji-repo-creator.groovy

Seems like I'm not a good groovy compiler.

Fix another MissingPropertyException - ENTRY_POINT_STORE

---

addons/koji/common/src/main/data/scripts/stores/koji-repo-creator.groovy
addons/koji/common/src/main/resources/scripts/stores/koji-repo-creator.groovy

NOS-583 - Fix NPE when transfering a koji build repo

---

addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java
addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java

NCL-2414 - Fix brew pull to correctly sync all brew build repo contents

---

addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCache.java
addons/folo/model-java/src/main/java/org/commonjava/indy/folo/model/TrackedContentEntry.java

Fix log formatting

---

addons/promote/common/src/main/data/promote/rules/no-pre-existing-paths.groovy
addons/revisions/common/src/main/conf/conf.d/revisions.conf
addons/revisions/common/src/main/java/org/commonjava/indy/revisions/conf/RevisionsConfig.java
addons/revisions/common/src/main/resources/default-revisions.conf

validation rule prevents promotion when path already exists in target.

turn off revisions by default, add new validation rule

---

embedders/pom.xml
subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/CacheProducer.java

Correct IllegalStateException when Infinispan tries to stop

---

addons/koji/ftests/pom.xml
core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java
embedder-tests/savant/pom.xml
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RepositoryPathMaskTest.java
models/core-java/src/main/java/org/commonjava/indy/model/core/AbstractRepository.java

First shot! Will add some other ftests later on. Please comment and let me know whether I am copying your idea correctly. There are 2 TODOs in the decorator code (questions) and please help out.

Implement domain and basic logic for repository path masks

---

planning/koji-content-retrieval.md

Adding sequence diagram txt for Koji content-retrieval use case (optimistic).

---

addons/koji/common/src/main/data/scripts/stores/koji-repo-creator.groovy
addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java
addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiRepositoryCreator.java
addons/koji/common/src/main/resources/scripts/stores/koji-repo-creator.groovy
ftests/core/pom.xml
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/ProxyRemoteKojiContentTest.java

Hi John, I have come up with the code change. Seems mostly I just delete ... Please review it. The ftest is not complete yet. I have questions in TODO. BTW, please merge NOS-639 if no problem since this one depends on it. I'll add more test cases later on for Non-koji as well as koji tests.

Refactor KojiContentManagerDecorator for path masks

---

embedder-tests/savant/pom.xml
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RepositoryPathMaskExtTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RepositoryPathMaskMetadataTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RepositoryPathMaskTest.java

@jdcasey , some more test cases for path mask. Please review.

Non-Koji Functional tests for path mask feature

---

clients/core-java/src/main/java/org/commonjava/indy/client/core/Indy.java
clients/core-java/src/main/java/org/commonjava/indy/client/core/IndyClientHttp.java
clients/core-java/src/main/java/org/commonjava/indy/client/core/auth/BasicAuthenticator.java
clients/core-java/src/main/java/org/commonjava/indy/client/core/auth/IndyClientAuthenticator.java
clients/core-java/src/main/java/org/commonjava/indy/client/core/auth/OAuth20BearerTokenAuthenticator.java

@jdcasey , I managed to refactor it without breaking backward compatibility. I did ftests on my local and passed. Hopefully CI won't let me down. Please review.

Convert IndyClientHttp to use jHTTPc instead of direct httpclient

---

.gitignore
addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexManager.java
addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java
addons/pkg-maven/ftests/pom.xml
addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java
clients/core-java/src/main/java/org/commonjava/indy/client/core/IndyClientHttp.java
db/memory/src/main/java/org/commonjava/indy/mem/data/MemoryStoreDataManager.java
db/memory/src/test/java/org/commonjava/indy/mem/data/ConcurrencyTest.java

* Use ReentrantLock keyed to StoreKey for synchronization in MemoryStoreDataManager
* Use WeakHashMap for ReentrantLock maps everywhere to avoid keeping references to key instances

Fix deadlock in MemoryStoreDataManager

---

addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java
addons/promote/common/src/main/data/promote/rules/artifact-refs-via.groovy
addons/promote/common/src/main/data/promote/rules/no-snapshots.groovy
addons/promote/common/src/main/data/promote/rules/no-version-ranges.groovy
addons/promote/common/src/main/data/promote/rules/parsable-pom.groovy
addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java
addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidationTools.java
addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidator.java
addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/model/ValidationRequest.java
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/rule/AbstractValidationRuleTest.java
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/rule/ArtifactRefs_PromoteWithParent_RuleTest.java
addons/promote/ftests/src/main/resources/artifact-refs-via/child.pom.xml
addons/promote/ftests/src/main/resources/artifact-refs-via/parent.pom.xml
addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/PathsPromoteResult.java
addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/ValidationResult.java
addons/promote/model-java/src/test/java/org/commonjava/indy/promote/model/PathsPromoteResultTest.java
pom.xml

@ligangty I'm incorporating your failing ftest here. I had to make quite a few changes to surrounding code that I had wrong, particularly in PromotionValidationTools. In the end, this is simpler than submitting some sort of patch or PR back to your dev branch.

ftests and fixes for masked source repo on by-paths promote

---

addons/autoprox/jaxrs/pom.xml
api/src/main/java/org/commonjava/indy/action/IndyLifecycleManager.java
api/src/main/java/org/commonjava/indy/action/UserLifecycleManager.java
api/src/main/java/org/commonjava/indy/action/fixture/AlternativeUserLifecycleManager.java
core/pom.xml
core/src/main/java/org/commonjava/indy/core/lifecycle/IndyUserLifecycleManager.java
ftests/core/pom.xml
ftests/core/src/main/java/org/commonjava/indy/ftest/core/lifecycle/UserIndyLifecycleManagerTest.java
ftests/core/src/main/resources/lifecycle/boot01.groovy
ftests/core/src/main/resources/lifecycle/boot02.groovy
ftests/core/src/main/resources/lifecycle/migrate01.groovy
ftests/core/src/main/resources/lifecycle/shutdown01.groovy
ftests/core/src/main/resources/lifecycle/start01.groovy
subsys/groovy/src/test/resources/META-INF/beans.xml

@jdcasey , a late commit due to other pnc tasks. please review. The ftest is not good. I just print something and check them manually. If you know how to assert it, please let me know.

Support user-defined Boot / Migration / Startup / Shutdown scripts

---

planning/promote/promote_group_lifecycle.md
planning/promote/promote_paths_lifecycle.md

Hi, @jdcasey, I've created doc and moved it as child page of promotion add on page. This commit includes the sequence diagram script files.

AdAdd sequence diagram for the life-cycle of promotion addon

---

addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/change/FoloPomDownloadListener.java
addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java
addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/rule/FullRuleStack_GroupWithOneOfTwoHosts_RuleTest.java
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/rule/NoPreExistingPaths_GroupWithOneOfTwoHosts_RuleTest.java
clients/core-java/src/main/java/org/commonjava/indy/client/core/Indy.java
clients/core-java/src/main/java/org/commonjava/indy/client/core/IndyClientHttp.java
embedders/savant/src/main/resources/META-INF/beans.xml
pom.xml

* also add option to use PasswordManager with Indy client to enable BASIC auth

Put Koji content decorator at top of invocation order, and add tests for promotion rules

---

addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromoteValidationsManager.java

Want to check if there is rule/rule-set files enabled.

Add some log for checking rule files in PromoteValidationsManager

---

subsys/git/pom.xml
subsys/git/src/test/java/org/commonjava/indy/subsys/git/AbstractGitManagerTest.java
subsys/git/src/test/java/org/commonjava/indy/subsys/git/GitManagerConcurrentTest.java
subsys/git/src/test/java/org/commonjava/indy/subsys/git/GitManagerTest.java

Seems the git add/delete needs some level of the lock to avoid concurrent opers

NOS-730 Add concurrent test for GitManager

---

addons/folo/common/src/main/java/org/commonjava/indy/folo/change/FoloTrackingListener.java
addons/httprox/common/src/test/java/org/commonjava/indy/httprox/HttpProxyTest.java
addons/koji/common/src/main/java/org/commonjava/indy/koji/conf/IndyKojiConfig.java
addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiBuildAuthority.java
addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java
addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java
addons/koji/common/src/test/java/org/commonjava/indy/koji/content/KojiMavenMetadataProviderTest.java
addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenContentAdvisor.java
addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidationTools.java
addons/promote/common/src/test/java/org/commonjava/indy/promote/data/PromotionManagerTest.java
api/src/main/java/org/commonjava/indy/content/ContentDigester.java
api/src/main/java/org/commonjava/indy/content/ContentManager.java
api/src/main/java/org/commonjava/indy/content/DirectContentAccess.java
core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java
core/src/main/java/org/commonjava/indy/core/content/DefaultDirectContentAccess.java
core/src/test/java/org/commonjava/indy/core/ctl/ContentControllerTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/MixContentRescheduleTimeoutTest.java
pom.xml
subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/IndyDeployment.java
subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/ResourceManagementFilter.java
subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/UnhandledIOExceptionHandler.java

merge @ligangty original PR with refactors I just did, and create feature branch to contain the work until we're ready to merge back to the main dev/maint branches.

Indy 1.1.x koji authority

---

addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidationTools.java

[promote] Allow getting validation stores without the target one

---

addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexObserver.java
addons/koji/common/pom.xml
addons/pkg-maven/ftests/pom.xml
addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/RecursiveGroupMetadataClearOnUploadTest.java
addons/pkg-maven/ftests/src/main/resources/logback-test.xml
core/src/main/java/org/commonjava/indy/core/content/AbstractMergedContentGenerator.java
pom.xml

* there is a test, but it doesn't seem to work correctly yet. It passes even when the race condition is in place.

fix race condition propagating metadata deletion through nested groups

---

addons/autoprox/common/src/test/java/org/commonjava/indy/autoprox/fixture/TestAutoProxyDataManager.java
addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexManager.java
addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexObserver.java
addons/implied-repos/common/src/test/java/org/commonjava/indy/implrepo/fixture/TestValidRemoteStoreDataManager.java
addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/RecursiveGroupMetadataClearOnMemberAddTest.java
addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidator.java
api/src/main/java/org/commonjava/indy/change/event/ArtifactStoreDeletePostEvent.java
api/src/main/java/org/commonjava/indy/change/event/ArtifactStorePostUpdateEvent.java
api/src/main/java/org/commonjava/indy/content/ContentManager.java
api/src/main/java/org/commonjava/indy/data/StoreDataManager.java
core/src/main/java/org/commonjava/indy/core/change/GroupConsistencyListener.java
core/src/main/java/org/commonjava/indy/core/change/StorageDeletionListener.java
core/src/main/java/org/commonjava/indy/core/change/event/DefaultStoreEventDispatcher.java
core/src/main/java/org/commonjava/indy/core/change/event/IndyFileEventManager.java
db/memory/src/main/java/org/commonjava/indy/mem/data/MemoryStoreDataManager.java

streamline group recursion in content index cleanup, and don't fire file events in content index cleanup

make post-style events async, content index event improvements

---

test/db/src/main/java/org/commonjava/indy/core/data/GroupDataManagerTCK.java

Hi @jdcasey 
Today when I read the code, I found two lines of code which really made me confused:
https://github.com/Commonjava/indy/blob/master/db/memory/src/main/java/org/commonjava/indy/mem/data/MemoryStoreDataManager.java#L436
Seems this "processed" keys never be updated, so what it is used for?
https://github.com/Commonjava/indy/blob/master/db/memory/src/main/java/org/commonjava/indy/mem/data/MemoryStoreDataManager.java#L456
withthis line of code, I've a test case in this commit with "createTwoGroupsAndAffectedByForTwoLevel()"., which I think it will result. What I'm confused is with //FIXME.

New TCK tests for StoreDataManager

---

core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/DownloadFromSecondRemoteAfterFirstHostedRepoTest.java
models/core-java/src/main/java/org/commonjava/indy/model/core/Group.java

Also, cut down on Group.toString verbosity

Improve iteration through list of stores when looking for Transfer

---

pom.xml

* This will need to be merged AFTER https://github.com/Commonjava/galley/pull/160

Upgrade galley to get better listing debug output

---

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiBuildAuthority.java

Brew contains many builds that produced rpms along with Maven artifacts.
Those were skipped because they had no artifactId for the rpm archives.

Do not drop builds containing non-maven artifacts

---

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java

Do not check the same version multiple times if a different build of the
same version is already added to the list.

(master) Koji metadata generation speedup

---

pom.xml

...to track the ISPN IllegalSTateException when using fast local cache more easily

Use latest galley 0.13.x snapshot

---

addons/folo/model-java/pom.xml
addons/pom.xml
addons/relate/common/pom.xml
addons/relate/common/src/main/conf/conf.d/relate.conf
addons/relate/common/src/main/java/org/commonjava/indy/relate/RelateAddOn.java
addons/relate/common/src/main/java/org/commonjava/indy/relate/change/RelatePomStorageListener.java
addons/relate/common/src/main/java/org/commonjava/indy/relate/conf/RelateConfig.java
addons/relate/common/src/main/java/org/commonjava/indy/relate/content/RelateContentGenerator.java
addons/relate/common/src/main/java/org/commonjava/indy/relate/util/RelateGenerationManager.java
addons/relate/common/src/main/resources/META-INF/beans.xml
addons/relate/common/src/main/resources/default-relate.conf
addons/relate/ftests/pom.xml
addons/relate/ftests/src/main/java/org/commonjava/indy/relate/ftest/PomDownloadListenerTest.java
addons/relate/ftests/src/main/java/org/commonjava/indy/relate/ftest/PomUploadListenerTest.java
addons/relate/ftests/src/main/java/org/commonjava/indy/relate/ftest/RelDownloadBeforePomTest.java
addons/relate/pom.xml
embedder-tests/savant-report/pom.xml
embedder-tests/savant/pom.xml
embedders/savant/pom.xml
models/core-java/pom.xml
models/core-java/src/main/java/org/commonjava/indy/model/core/io/IndyObjectMapper.java
pom.xml

First working version. More tests needed. Please review and not merge it.

Dependency graph pre-parsed fragments

---

pom.xml
subsys/metrics/pom.xml
subsys/metrics/src/main/conf/conf.d/metrics.conf
subsys/metrics/src/main/java/org/commonjava/indy/IndyMetricsManager.java
subsys/metrics/src/main/java/org/commonjava/indy/measure/annotation/IndyMetrics.java
subsys/metrics/src/main/java/org/commonjava/indy/measure/annotation/Measure.java
subsys/metrics/src/main/java/org/commonjava/indy/measure/annotation/MetricNamed.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/conf/IndyMetricsConfig.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/filter/HealthCheckMetricFilter.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/filter/JVMMetricFilter.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/filter/SimpleMetricFilter.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/healthcheck/IndyHealthCheck.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/healthcheck/IndyHealthCheckRegistrySet.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/healthcheck/impl/ThreadDeadlockHealthCheck.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/jaxrs/interceptor/MetricsInterceptor.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/jaxrs/producer/IndyProducer.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/jvm/IndyJVMInstrumentation.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/reporter/ReporterIntializer.java
subsys/metrics/src/main/resources/META-INF/beans.xml
subsys/metrics/src/main/resources/default-metrics.conf
subsys/pom.xml

@jdcasey 
This is my init code PR, please review it.

init module subsys-metrics

---

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java

This should avoid race conditions when promoting conflicting repository
contents from multiple repos at the same time.

Synchronize hosted repo promotion to group

---

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java

This should avoid race conditions when promoting conflicting repository
contents from multiple repos at the same time.

[master] Synchronize hosted repo promotion to group

---

addons/httprox/common/src/main/conf/conf.d/httprox.conf
addons/httprox/common/src/main/java/org/commonjava/indy/httprox/conf/HttproxConfig.java
addons/httprox/common/src/main/java/org/commonjava/indy/httprox/data/HttProxRegisterSpecialPathStartupAction.java
addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyResponseWriter.java
addons/httprox/common/src/main/resources/default-httprox.conf
addons/httprox/ftests/pom.xml
addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/AutoCreateRepoAndRetrieveNoCacheFileTest.java
filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java

This depends on https://github.com/Commonjava/galley/pull/181

Add nocache.patterns property to HttpProx conf and register to SpecialPathManager

---

ftests/metrics/src/main/resources/default-test-metrics.conf
pom.xml
subsys/metrics/pom.xml
subsys/metrics/src/main/conf/conf.d/metrics.conf
subsys/metrics/src/main/java/org/commonjava/indy/metrics/conf/IndyMetricsConfig.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/jaxrs/producer/IndyProducer.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/reporter/ReporterIntializer.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/zabbix/reporter/HostUtil.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/zabbix/reporter/IndyZabbixReporter.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/zabbix/sender/IndyZabbixSender.java
subsys/metrics/src/main/resources/default-metrics.conf

@jdcasey  Hi, Please review the code .
At the same time, I will continue refacing.

create zabbix sender and zabbix reporter

---

addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/report/RecalculateMissingChecksumForTrackingRecordTest.java
addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/report/UseChecksumFromTransferDecoratorForTrackingRecordTest.java

Use TimingDependent category to try to avoid byteman collisions

---

addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/report/UseChecksumFromTransferDecoratorForTrackingRecord_Sha1FileTest.java
subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/IndyDeployment.java
subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/ResourceManagementFilter.java

Also, cleanup a bunch of dead, commented code in IndyDeployment

(1.1.x) Log REST requests to org.commonjava.topic.rest.inbound

---

deployments/launchers/base/src/main/conf/logging/logback.xml
deployments/launchers/savant/src/main/etc/indy/logging/logback.xml

Use a clean indy-1.1.x branch with this commit to track.

Enable a separate logger for special cases

---

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyAcceptHandler.java
addons/implied-repos/common/src/main/java/org/commonjava/indy/implrepo/change/ImpliedRepositoryDetector.java
addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java
core/src/main/java/org/commonjava/indy/core/ctl/ReplicationController.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/MetaListingRescheduleTimeoutTest.java

Use this split branch for this OOM issue.

Fix a potential OOM problem of repo creator

---

addons/koji/common/pom.xml
addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java
addons/koji/common/src/main/java/org/commonjava/indy/koji/metrics/IndyKojiMetricsNames.java

@jdcasey As my understand your mail, I add metrics in koji.
Sorry about  the code style, I will fix it. 
Please review it.

add metrics feature in koji

---

core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RepositoryPathMaskExtTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RepositoryPathMaskMetadataTest.java

NOS-939: Differentiate between plaintext and regexps in path mask

---

addons/koji/common/pom.xml
addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiBuildAuthority.java
addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java
addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java
addons/koji/common/src/main/java/org/commonjava/indy/koji/metrics/IndyMetricsKojiNames.java
subsys/metrics/src/main/java/org/commonjava/indy/IndyMetricsNames.java

@jdcasey 
According to your comment, I updated the code.
Please review it.
Other question, In the situation, I take another PR or I just add other commits on the old PR(https://github.com/Commonjava/indy/pull/698) or I just force update the old PR.
Please tell me, which way is better.
Thanks!

[NOS-906] annotate koji for metrices collections

---

addons/promote/common/src/main/conf/conf.d/promote.conf
addons/promote/common/src/main/java/org/commonjava/indy/promote/conf/PromoteConfig.java
addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java
addons/promote/common/src/main/resources/default-promote.conf
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/GroupPromoteSourceIsReadOnlyTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/StoreThenGetUnSuffixedDirAndDownloadTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/StoreThenGetUnSuffixedDirAndDownloadViaGroupTest.java
pom.xml

Catching up to changes in 1.1.x

(master) read-lock hosted repos on by-group promote; pom version upgrades; fix ftests

---

addons/pkg-npm/common/src/test/java/org/commonjava/indy/pkg/npm/content/group/PackageMetadataMergerTest.java
addons/pkg-npm/jaxrs/pom.xml
addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessResource.java
addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/PackageContentAccessHandler.java
addons/pkg-npm/pom.xml
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java
pom.xml

Hi, John
There seem some conflicts couldn't merge automatically, I'm not sure if it will be ok after nos-936 PR be merged. let me know any issue for the PR code or mege stuff.
Thanks.

NOS-937, Implement PackageContentAccessResource for NPM

---

.gitignore
pom.xml
scripts/folo-repair/README.md
scripts/folo-repair/folofix/__init__.py
scripts/folo-repair/folofix/command.py
scripts/folo-repair/folofix/downloader.py
scripts/folo-repair/folofix/reporter.py
scripts/folo-repair/setup.py
scripts/multibuild/README.md
scripts/multibuild/mb/__init__.py
scripts/multibuild/mb/builder.py
scripts/multibuild/mb/command.py
scripts/multibuild/mb/reporter.py
scripts/multibuild/mb/util.py
scripts/multibuild/mb/vagrant.py
scripts/multibuild/sample-testfile.yaml
scripts/multibuild/setup.py

merge folo-scripts-1.1.x and multibuild from indy-vagrant-nfs

---

.gitignore
scripts/folo-repair/README.md
scripts/folo-repair/folofix/__init__.py
scripts/folo-repair/folofix/command.py
scripts/folo-repair/folofix/downloader.py
scripts/folo-repair/folofix/reporter.py
scripts/folo-repair/setup.py
scripts/multibuild/README.md
scripts/multibuild/mb/__init__.py
scripts/multibuild/mb/builder.py
scripts/multibuild/mb/command.py
scripts/multibuild/mb/reporter.py
scripts/multibuild/mb/util.py
scripts/multibuild/mb/vagrant.py
scripts/multibuild/sample-testfile.yaml
scripts/multibuild/setup.py

(master) Merge folo-scripts-1.1.x and multibuild script from indy-vagrant-nfs

---

ftests/metrics/src/main/resources/default-test-metrics.conf
pom.xml
subsys/metrics/pom.xml
subsys/metrics/src/main/conf/conf.d/metrics.conf
subsys/metrics/src/main/java/org/commonjava/indy/metrics/conf/IndyMetricsConfig.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/reporter/ReporterIntializer.java
subsys/metrics/src/main/resources/default-metrics.conf

add Elasticsearch reporter for metrics

---

addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexManager.java
addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java
addons/content-index/src/main/java/org/commonjava/indy/content/metrics/IndyMetricsContentIndexNames.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCache.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/metrics/IndyMetricsFoloNames.java
core/src/main/java/org/commonjava/indy/core/change/StoreEnablementManager.java
core/src/main/java/org/commonjava/indy/core/metrics/IndyMetricsCoreNames.java
subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/metrics/IndyMetricsJaxrsNames.java

Annotate update

---

api/src/main/java/org/commonjava/indy/model/galley/CacheOnlyLocation.java
api/src/main/java/org/commonjava/indy/model/galley/GroupLocation.java
api/src/main/java/org/commonjava/indy/model/galley/RepositoryLocation.java
core/src/test/java/org/commonjava/indy/core/content/DefaultDownloadManagerTest.java
pom.xml

This PR need waiting for galley PR merged: https://github.com/Commonjava/galley/pull/196

add NOS-946 readonly protections associate Location implements in indy and unit test for this

---

uis/layover/app/js/filters.js
uis/layover/app/js/services.js
uis/layover/app/partials/group-edit.html
uis/layover/app/partials/hosted-edit.html
uis/layover/app/partials/includes/group-view.html
uis/layover/app/partials/includes/hosted-view.html
uis/layover/app/partials/includes/remote-view.html
uis/layover/app/partials/remote-edit.html

@jdcasey 
BackPort to indy-1.1.x

[NOS-912] format timestamp

---

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/PromoteAllTest.java
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/PromoteDryRunTest.java
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/RollbackTwoArtifactsTest.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java
core/pom.xml
core/src/main/java/org/commonjava/indy/core/ctl/ContentController.java
core/src/main/java/org/commonjava/indy/core/model/StoreHttpExchangeMetadata.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/DownloadContentHasLengthHeaderHostedTest.java
subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/ResponseUtils.java

Build on #747 by fixing ftests for http-metadata generation on content storage

---

deployments/launchers/savant/pom.xml
deployments/launchers/savant/src/main/etc/indy/logging/logback.xml
pom.xml
subsys/metrics/src/main/conf/conf.d/elasticsearch.properties

[NOS-1006] add elasticsearch appender of logback support

---

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java

It checks if a koji repo with the same name exists and if so, then it
uses it with a warning message if it is enabled or it acts like if no
matching build was found in koji.

[1.1.x][NOS-1052] Do not re-enable koji repos with a new request

---

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java

It checks if a koji repo with the same name exists and if so, then it
uses it with a warning message if it is enabled or it acts like if no
matching build was found in koji.

[NOS-1052] Do not re-enable koji repos with a new request

---

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java

Conflicts:
addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java

[1.2.x] parallelize metadata downloads when generating group metadata

---

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java

Conflicts:
addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java

[master] parallelize metadata downloads when generating group metadata

---

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiContentManagerDecorator.java

kojiji was refactored and the listArchivesForBuild method does not use
maven package type anymore and because of that the result is missing the
maven-specific fields like groupId, artifactId etc and that causes NPE.
Workarounding it by building the query ourselves adding the type there.
The stacktrace was:
```
org.commonjava.indy.IndyWorkflowException: Cannot retrieve builds for: org.optaplanner:optaplanner-bom:pom:6.5.0.Final-redhat-16. Error: Koji withSession lambda command failed: null
at org.commonjava.indy.koji.content.KojiContentManagerDecorator.proxyKojiBuild(KojiContentManagerDecorator.java:380) ~[indy-embedder-savant-1.1.11.jar:na]
at org.commonjava.indy.koji.content.KojiContentManagerDecorator.findKojiBuildAnd(KojiContentManagerDecorator.java:288) …
```

[1.2.x] Fix NPE in koji add-on

---

core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/ReDownloadOnContentTransferExceptionTest.java

[1.2.x] Handle TransferContentException and partial download errors.

---

core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/ReDownloadOnContentTransferExceptionTest.java

[master] Handle TransferContentException and partial download errors.

---

api/src/main/java/org/commonjava/indy/IndyWorkflowException.java
ftests/core/pom.xml
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/GroupMetadataConcurrentAccessTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/fixture/CallableDelayedDownload.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/fixture/SlowInputStream.java
models/core-java/src/main/java/org/commonjava/indy/IndyException.java

Add missing things from https://github.com/Commonjava/indy/pull/789 to master. Relevant PR on the master is https://github.com/Commonjava/indy/pull/791 .

Add missing things for nos-1074 from 1.1.x to master

---

uis/layover/app/partials/hosted-list.html

There was a typo in property name - packagetype vs packageType.

[master][UI] Fix hosted repo detail link from the hosted list

---

addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessHandler.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java

[npm] restrict content-type with json in headers directly to simplify merging with http-meta

---

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/keycloak/KeycloakProxyAuthenticator.java

* fixes sending challenge response when successfully authorized
* fixes challenge response status and header
Backported #817

[1.2.x] Httprox fixes

---

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/keycloak/KeycloakProxyAuthenticator.java

* fixes sending challenge response when successfully authorized
* fixes challenge response status and header

[master] Httprox fixes

---

api/src/main/java/org/commonjava/indy/action/IndyLifecycleEventManager.java
api/src/main/java/org/commonjava/indy/change/EventUtils.java
core/src/main/java/org/commonjava/indy/core/change/event/DefaultStoreEventDispatcher.java
core/src/main/java/org/commonjava/indy/core/change/event/IndyFileEventManager.java
core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java
core/src/main/java/org/commonjava/indy/core/expire/ScheduleManager.java
ftests/core/src/main/resources/logback-test.xml
subsys/flatfile/src/main/java/org/commonjava/indy/subsys/datafile/change/DataFileEventManager.java

...and improve reporting when errors happen in ScheduleManager

Handle cases where the JEE event dispatcher is null

---

pom.xml

galley 0.16.1-SNAPSHOT -> 0.16.1
partyline 1.11 -> 1.12
weft 1.4.1 -> 1.5

Change dependency versions

---

clients/core-java/src/main/java/org/commonjava/indy/client/core/module/IndyNfcClientModule.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/NFCForGroupsWithGroupsTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/NFCForTwoGroupsWithSameHostedTest.java
pom.xml

Galley 0.16.1-SNAPSHOT -> 0.16.1
Partyline 1.11 -> 1.12
wEFT 1.4.1 -> 1.15

Update dependencies and porting from indy-1.2.x

---

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java
addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java

1. add check for artifact version parsing
2. add persistence for maven version relevant ISPN caches to boost the performance

Fix invalid group maven-metadata.xml when proxy for Brew build

---

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java

The latch is waiting on one store, but we don't know which one and why. Adding more debug messages.

Add debug message for not respond on request issue

---

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java
addons/promote/common/src/test/java/org/commonjava/indy/promote/data/PromotionManagerTest.java
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/GroupNFCEntryClearedOnByPathPromoteTest.java
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/GroupNFCEntryClearedOnPromoteTest.java
clients/core-java/src/main/java/org/commonjava/indy/client/core/module/IndyNfcClientModule.java
db/memory/src/main/java/org/commonjava/indy/mem/data/MemoryArtifactStoreQuery.java

Back off of UI changes in #911 (which still need to be addressed in the long term) and fix the NPE potential. Fold in merged commit from #917 in the middle of these.

Address NPE in directory listing by itself

---

ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/GroupMembershipDeletionMayDisruptMetadataTest.java

Wait some time for the event-related action to finish.

Fix unstable byteman test GroupMembershipDeletionMayDisruptMetadataTest

---

addons/diagnostics/common/pom.xml
addons/diagnostics/common/src/main/java/org/commonjava/indy/diag/data/DiagnosticsManager.java
addons/diagnostics/jaxrs/src/main/java/org/commonjava/indy/diag/bind/jaxrs/DiagnosticsResource.java
db/flat/src/main/java/org/commonjava/indy/flat/data/DataFileStoreConstants.java
db/flat/src/main/java/org/commonjava/indy/flat/data/DataFileStoreDataManager.java
db/flat/src/main/java/org/commonjava/indy/flat/data/LegacyDataMigrationAction.java
db/flat/src/test/java/org/commonjava/indy/flat/data/LegacyDataMigrationActionTest.java
uis/layover/app/index.html

I tested it and the repo download works well. UI also updated - it is under the diagnostic bundle menu item.

 Exposing zip download endpoint in the API to get repo definitions

---

ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/GroupMembershipDeletionMayDisruptMetadataTest.java

Fix GroupMembershipDeletionMayDisruptMetadataTest instability

---

addons/httprox/common/src/main/data/scripts/stores/httprox-repo-creator.groovy
addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/AbstractProxyRepositoryCreator.java
addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyCreationResult.java
addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyRepositoryCreator.java
addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyResponseWriter.java
addons/httprox/common/src/main/java/org/commonjava/indy/httprox/util/HttpConduitWrapper.java
addons/httprox/common/src/main/resources/scripts/stores/httprox-repo-creator.groovy
addons/httprox/common/src/test/java/org/commonjava/indy/httprox/AbstractProxyRepositoryCreatorTest.java
addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/AbstractHttproxFunctionalTest.java
addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/AutoCreateRepoAndRetrievePomTest.java
addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/AutoCreateRepoWithTrackingIdTest.java
models/core-java/src/main/java/org/commonjava/indy/model/core/ArtifactStore.java

Per-build separation of httprox repositories

---

core/src/main/java/org/commonjava/indy/core/inject/IspnNotFoundCache.java
core/src/main/java/org/commonjava/indy/core/inject/NfcConcreteResourceWrapper.java
subsys/infinispan/src/main/resources/infinispan-jdbc.xml
subsys/infinispan/src/main/resources/infinispan.xml

Update clearMissing(Location location) by query instead of stream/filter

---

addons/koji/common/src/test/java/org/commonjava/indy/koji/content/KojiMavenMetadataProviderTest.java
core/src/test/java/org/commonjava/indy/core/inject/ExpiringMemoryNotFoundCacheTest.java
core/src/test/java/org/commonjava/indy/fixture/MockGalleyProvider.java
embedder/pom.xml
rest/api/src/test/resources/META-INF/beans.xml
subsys/groovy/pom.xml
subsys/groovy/src/test/java/org/commonjava/indy/subsys/template/fixture/TestProvider.java
subsys/metrics/src/main/conf/conf.d/metrics.conf
subsys/metrics/src/main/java/org/commonjava/indy/IndyMetricsManager.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/conf/IndyMetricsConfig.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/reporter/ReporterIntializer.java
subsys/metrics/src/main/resources/default-metrics.conf
test/fixtures-core/src/main/java/org/commonjava/indy/test/fixture/core/MockGalleyProvider.java

This depends on https://github.com/Commonjava/galley/pull/245

Use metric to measure remote repo transport

---

addons/koji/common/src/main/java/org/commonjava/indy/koji/inject/KojijiProvider.java
pom.xml
subsys/metrics/src/main/conf/conf.d/metrics.conf
subsys/metrics/src/main/java/org/commonjava/indy/metrics/conf/IndyMetricsConfig.java
subsys/metrics/src/main/resources/default-metrics.conf

This depends on https://github.com/release-engineering/kojiji/pull/100

Keep metrics on Koji xmlrpc calls if available

---

.gitignore
addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidator.java
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/rule/FullRuleStack_GroupWithOneOfTwoHosts_RuleTest.java

Also fix a ftest which failed because of NOS-1166

Parallel promotion validation rule execution

---

addons/content-index/src/main/java/org/commonjava/indy/content/index/warmer/ContentIndexWarmer.java
addons/content-index/src/main/java/org/commonjava/indy/content/index/warmer/ContentWarmerStartupAction.java
addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessHandler.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/util/TransferStreamingOutput.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/IndyMetricsConstants.java
subsys/metrics/src/main/java/org/commonjava/indy/metrics/jaxrs/interceptor/MetricsInterceptor.java

new metric is for transferred bytes back to user

Add cache-warmer startup action for content index, and add transferred metric

---

addons/content-index/src/main/java/org/commonjava/indy/content/index/warmer/ContentIndexWarmer.java
subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/metrics/IspnCheckRegistrySet.java

Pull back on the pre-population of the content index to concrete stores to make it run a bit faster and with less memory usage.
Improve the ISPN metrics to make most of them RATES instead of cumulative.

Make content index cache warming less aggressive, improve ISPN metrics

---

uis/layover/app/js/controllers.js
uis/layover/app/js/services.js
uis/layover/app/partials/hosted-edit.html
uis/layover/app/partials/includes/hosted-view.html
uis/layover/app/partials/includes/remote-view.html
uis/layover/app/partials/remote-edit.html

The pathMaskPatterns text area format is not plain lines, it is well-formatted JSON, e.g.,
[
"abc*",
...
]
It looks pretty.

UI for view/edit pathMaskPatterns

---

addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java
subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/metrics/IspnCheckRegistrySet.java

@ligangty What do you think of this idea?

readonly hosted repo implies authoritative index

---

ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/prefetch/RemotePrefetchDisableTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/prefetch/RemotePrefetchDownloadWithPathMaskPlaintextTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/prefetch/RemotePrefetchDownloadWithPathMaskRegsTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/prefetch/RemotePrefetchDownloadingTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/prefetch/RemotePrefetchRescanTest.java
uis/layover/app/js/controllers.js
uis/layover/app/js/services.js
uis/layover/app/partials/hosted-edit.html
uis/layover/app/partials/includes/hosted-view.html
uis/layover/app/partials/includes/remote-view.html
uis/layover/app/partials/remote-edit.html

And revert ui pathmask setting functions as it is not needed in this fix patch

Skip prefetch ftests due to failure on different environments

---

deployments/pom.xml
test/pom.xml

This reverts commit 214f081936fd9c795a0b9f6649481d83970d752e.

Revert "Remove docker module from release"

---

deployments/launcher/src/main/bin/indy.sh
pom.xml
subsys/infinispan/pom.xml
subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/config/ISPNDBConfiguration.java
subsys/infinispan/src/main/resources/infinispan-jdbc.xml

Also add some lost dependencies for ISPN jdbc store

Fix ISPN jdbc parameter to match with OSE settings

---

addons/content-index/src/main/java/org/commonjava/indy/content/index/ContentIndexManager.java
addons/content-index/src/main/java/org/commonjava/indy/content/index/DefaultContentIndexManager.java
addons/content-index/src/main/java/org/commonjava/indy/content/index/DirectoryLvContentIndexManagerDecorator.java
addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java
addons/content-index/src/main/java/org/commonjava/indy/content/index/PackageIndexingStrategy.java
addons/pkg-maven/common/pom.xml
addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/index/MavenIndexingStrategy.java
api/src/main/java/org/commonjava/indy/util/PathUtils.java
api/src/test/java/org/commonjava/indy/util/PathUtilsTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/AuthoritativeIndexedContentInHostedTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/AuthoritativeIndexedContentInRemoteTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/ContentIndexDirLvWithArtifactsTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/ContentIndexDirLvWithMetadataTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/ContentIndexGroupUsageTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/contentindex/ContentIndexRemoteRepoUsageTest.java
ftests/core/src/main/resources/META-INF/beans.xml

This was a big nasty merge that resolved conflicts with the original PR, then refactored to support package-type specific indexing strategies. Somehow, other catch-up type changes got swept up too. I'll review / resolve these after merge.

merging PR #1029 with refactor, and catch up on missing things

---

addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java
core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java
core/src/main/java/org/commonjava/indy/core/content/PathMaskChecker.java
models/core-java/src/main/java/org/commonjava/indy/model/core/AbstractRepository.java
models/core-java/src/main/java/org/commonjava/indy/model/core/ArtifactStore.java

cherrypicking commits from 1.3.0.x (#1022)

[master] Add path masks to groups

---

addons/koji/common/src/main/java/org/commonjava/indy/koji/data/KojiRepairManager.java

@jdcasey I find two more places where we do not need koji session. Pls review.

Not need to login in KojiRepairManager

---

boot/jaxrs/src/main/java/org/commonjava/indy/boot/jaxrs/JaxRsBooter.java

I found that gzip encoding for http request is not enabled in indy starter(also happened on production). After checking code, found it is only enabled when starting port < 1. Not sure if this has some special meaning. 
I've enabled it in all cases as some of our static resources (js or css) are not so small (> 200k), so this can help to reduce the bandwith for them.
@jdcasey do you know what cases for that port<1? If some special meaning please let me know and I'll change it back.

Enable gzip encoding in undertow for all cases

---

models/core-java/pom.xml
pom.xml

jackson change: 2.4.1 -> 2.9.7
Fix CVE:
CVE-2018-7489
CVE-2017-7525

Aplly jackson-2.9.7 to prevent jackson CVE

---

addons/koji/common/src/main/java/org/commonjava/indy/koji/data/KojiRepairManager.java
addons/koji/jaxrs/src/main/java/org/commonjava/indy/koji/bind/jaxrs/KojiRepairResource.java
addons/koji/model-java/src/main/java/org/commonjava/indy/koji/model/IndyKojiConstants.java

Which means koji remote metadata will never timeout

Add REST to fix koji remote metadata timeout to -1

---

addons/content-browse/common/src/main/java/org/commonjava/indy/content/browse/ContentBrowseController.java
addons/content-browse/ui/package.json

And fix the description of content-browse ui project

Add metrics for new Content browse service

---

addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/ProxyHttpsDownloadTgzTest.java

Yarn install always fails on downloading fsevents-1.2.4.tgz. I add this ftest to make sure httproxy can download it. It works well. Although I am not very sure, it seems the yarn install problem is on yarn side.

Add ProxyHttpsDownloadTgzTest for downloading fsevents-1.2.4.tgz which yarn install always fails

---

db/memory/src/main/java/org/commonjava/indy/mem/data/MemoryStoreDataManager.java

And also:
* Extract lock handling function to single variable
* Wrapped NPE for storing repo in lock action
P.S.:
When testing stage, sometimes the opLocks.lockAnd in
MemDataStoreMgr.store will cause NPE which is very tricky, even if the
vars in this lockAnd has been checked against null value. I'm suspecting
that there are some unknown null checking in the lambda functions which
are used in this operation, but I don't have clues for that yet. So I
wrapped the NPE firstly and return a false flag to indicate the store
operation failed. When the root cause of this NPE is found, will
refactor this commit for the NPE handling.

[Port to master] Add logger for NPE checking in MemDataStoreMgr

---

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/keycloak/KeycloakProxyAuthenticator.java
pom.xml

Github reports some vulnerabilities. I fixed two high/moderate risks of them as recommended.

Fix vulnerabilities found by github

---

pom.xml
subsys/kafka/pom.xml
subsys/kafka/src/main/conf/conf.d/kafka.conf
subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/IndyKafkaProducer.java
subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/conf/KafkaConfig.java
subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/util/LogbackFormatter.java
subsys/kafka/src/main/resources/META-INF/beans.xml
subsys/kafka/src/main/resources/default-kafka.conf
subsys/kafka/src/test/java/org/commonjava/indy/subsys/kafka/KafkaTest.java
subsys/kafka/src/test/resources/logback-test.xml
subsys/kafka/src/test/resources/producer.properties
subsys/pom.xml

IndyKafkaProducer. It provides blocking/non-blocking send, given the topic name and message. 
Add a util class LogbackFormatter which can be used to format messages ( e.g., to JSON as wanted by PNC ), by a logger/encoder def in logback.xml.

Add subsys/kafka

---

deployments/cache-migrator/src/main/java/org/commonjava/indy/tools/cache/Main.java
deployments/cache-migrator/test-env/indy-env/logging/logback.xml
deployments/cache-migrator/test-env/local-env-setup.sh

Fix the cache-migrator

---

subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/CacheProducer.java

When try to enable distributed cache, I found current way may cause
ISPN000343 problem. Because distributed cache needs transport support in
global config, so if the cache manager does not enable it and then add
this type of cache by cacheManager.defineConfiguration, it will report
this error. So this commit is a workaround fix for the problem.
With this fix, when we use customer+classpath config way, we should
enable <transport/> in customer config first, and then add any
distributed caches in both these configurations.

Init cache manager with customer config when both customer and classpath config exist

---

addons/diagnostics/common/src/main/java/org/commonjava/indy/diag/data/DiagnosticsManager.java
addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java
pom.xml
test/clients/diags/get-thread-counts.py
test/clients/diags/setup.sh

Also adding a small diagnostic client that summarizes thread counts by rough thread-group.

Upgrade Weft to fix ThreadLocal problem

---

deployments/cache-migrator/src/main/java/org/commonjava/indy/tools/cache/DataType.java
deployments/cache-migrator/src/main/java/org/commonjava/indy/tools/cache/Main.java
deployments/cache-migrator/src/main/java/org/commonjava/indy/tools/cache/MigrationOptions.java

I don't use GZIPInputStream/GZIPOutputStream when dump/load json object,
cause i found that there is memory leak using that, and that can be added
later when i figure out how that works well.

Add option to dump/load json object

---

filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java
filers/default/src/main/java/org/commonjava/indy/filer/def/PartylineClusterLockCache.java
filers/default/src/main/java/org/commonjava/indy/filer/def/PartylineClusterLockCacheProducer.java
subsys/infinispan/src/main/resources/infinispan.xml

This is a leftover from previous RP.

Rename partyline GLM cache to partyline-cluster-locks

---

addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidator.java

Catch all exceptions in promotion executeValidationRule

---

pom.xml
subsys/infinispan/src/main/conf/conf.d/infinispan-cluster.conf
subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/CacheProducer.java
subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/config/ISPNClusterConfiguration.java
subsys/infinispan/src/main/resources/infinispan-cluster.xml
subsys/infinispan/src/main/resources/jgroups-tcp.xml

I try to separate the replicated-cache from the exiting local caches since i ran into some weird thing when i did the integrate test for that. The thing is it tried to replicate other caches as well(not sure, but it reports the ClassNotFoundException as the class is in Indy local caches but never be used in AuditQuery side ).

Add ISPN cluster config

---

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiPathPatternFormatter.java
addons/koji/common/src/main/java/org/commonjava/indy/koji/data/KojiRepairManager.java

Add skipVersionTest flag when doing Koji path mask repair

---

addons/promote/common/src/main/java/org/commonjava/indy/promote/conf/PromoteConfig.java
addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidationTools.java
addons/promote/common/src/test/java/org/commonjava/indy/promote/data/PromotionManagerTest.java
addons/promote/common/src/test/java/org/commonjava/indy/promote/validate/PromotionValidationToolsTest.java

Here is the wanted paralleledInBatch.

[1.7.x] Support paralleledInBatch in promotion tool

---

addons/promote/common/src/main/java/org/commonjava/indy/promote/conf/PromoteConfig.java
addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidationTools.java
addons/promote/common/src/test/java/org/commonjava/indy/promote/data/PromotionManagerTest.java
addons/promote/common/src/test/java/org/commonjava/indy/promote/validate/PromotionValidationToolsTest.java

Port from 1.7.x.
* Support paralleledInBatch in promotion tool
* Move batchsize to config and fix commented issues

Support paralleledInBatch in promotion tool (#1209)

---

addons/koji/jaxrs/src/main/java/org/commonjava/indy/koji/bind/jaxrs/KojiRepairResource.java
addons/promote/common/src/main/data/promote/rules/parsable-pom.groovy
addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidator.java
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/rule/AbstractValidationRuleTest.java
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/rule/ParsablePomRuleByPathTest.java
addons/promote/jaxrs/src/main/java/org/commonjava/indy/promote/bind/jaxrs/PromoteResource.java
subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/JaxRsUriFormatter.java

Fix baseUrl

---

addons/promote/common/src/main/data/promote/rules/artifact-refs-via.groovy
addons/promote/common/src/main/data/promote/rules/no-pre-existing-paths.groovy
addons/promote/common/src/main/data/promote/rules/no-snapshots.groovy
addons/promote/common/src/main/data/promote/rules/no-version-ranges.groovy

Remove nested paralleledEach from default promotion groovy

---

addons/diagnostics/common/src/main/java/org/commonjava/indy/diag/data/DiagnosticsManager.java

We will need this once switching to ISPN data store.

Repo bundle maintainance to move away from file system

---

boot/jaxrs/src/main/java/org/commonjava/indy/boot/jaxrs/IndyDeployer.java
boot/jaxrs/src/main/java/org/commonjava/indy/boot/jaxrs/RestConfig.java

This fixes the rest.conf issue (I mentioned in prev PR) so that we can specify io/worker threads for undertow.

Fix RestConfig (ioThreads,workerThreads)

---

subsys/metrics/reporter/src/main/java/org/commonjava/indy/metrics/IndyMetricsManager.java
subsys/metrics/reporter/src/main/java/org/commonjava/indy/metrics/jaxrs/interceptor/MetricsInterceptor.java

This causes a spike in Elasticsearch + Kafka volume that we will need to plan for.

remove metric logging via MDC

---

db/common/src/main/java/org/commonjava/indy/db/common/AbstractStoreDataManager.java

The weird NPE is caused by auto unbox while the tryLock timeout. I add the timeout to 30 sec, just in case. The fix is to replace boolean with Boolean and check null.
btw, I moved the long lambda to a method. You can ignore it. Nothing changed.

Fix NPE in StoreDataManager caused by Locker timeout

---

addons/changelog/common/src/main/conf/conf.d/repo-changelog.conf
addons/changelog/common/src/main/java/org/commonjava/indy/changelog/RepoChangeHandler.java
addons/changelog/common/src/main/java/org/commonjava/indy/changelog/cache/RepoChangelogCacheProducer.java
addons/changelog/common/src/main/java/org/commonjava/indy/changelog/conf/RepoChangelogConfiguration.java
addons/changelog/common/src/main/resources/default-repo-changelog.conf
addons/changelog/ftests/src/main/java/org/commonjava/indy/changelog/RepoChangelogStoreTest.java
subsys/infinispan/src/main/resources/infinispan-cluster.xml
subsys/infinispan/src/main/resources/infinispan.xml

* Add UUID way for event id generation
* Disable change event by default
* Some fix for cache settings

Some adjustment for change event auditing

---

pom.xml

Update versions for galley, bom, partyline, propulsor, aq. Prepare for Indy 1.8 release.

Update dependency versions to formal releases

---

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java
addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/group/MavenMetadataMerger.java
addons/pkg-maven/ftests/src/main/java/org/commonjava/indy/pkg/maven/content/GroupMetadataForRemoteSnapshotTest.java
core/src/main/java/org/commonjava/indy/core/change/StoreContentListener.java

This is to address NOS-1847 -- Snapshot metadata are not getting merged.

Fix snapshot metadata generation

---

addons/changelog/common/src/main/java/org/commonjava/indy/changelog/RepoChangeHandler.java
db/common/src/main/java/org/commonjava/indy/db/common/AbstractStoreDataManager.java

Seems the repo delete event is not bundled together with repo update event. So need to handle it separately.

Fix problem of missing delete repo change event

---

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java
addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/group/MavenMetadataMerger.java
addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionHelper.java
addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/HostedMetadataRemergedOnPathPromoteSnapshotTest.java
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/PromoteRemoteReDownloadTest.java
ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractContentManagementTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/HostedMetadataMergeSnapshotTest.java

This is for NOSSUP-65. This is on top of https://github.com/Commonjava/indy/pull/1279 so please just review the third commit.

Promotion redownload remote artifacts if expired

---

.gitignore

I forgot this folder is still in other dev local envs

Add bower_components to git ignore

---

core/src/main/java/org/commonjava/indy/core/change/StoreContentListener.java

We found sometimes that the group maven-metadata not updated in time,
which should be caused by the async way of the metadata cleanup. So
should rollback to old drain/synchronized way to let it update in time.

Rollback store cleanup to drain way

---

core/src/main/java/org/commonjava/indy/core/change/StoreContentListener.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/GroupMembershipAddMayDisruptMetadataRefreshTest.java

Also, adding a regression test to ensure this doesn't happen again.

Fix path-cleanup submit to drain service, not to executor service.

---

addons/sli/jaxrs/src/main/java/org/commonjava/indy/sli/jaxrs/GoldenSignalsFilter.java

I'm not sure if there are un-handled exception in indy http process chain. But for double check here, mark them as error if they really happened.

Mark sli error when some un-handled exception happened

---

addons/diagnostics/client-java/src/main/java/org/commonjava/indy/diag/client/IndyDiagnosticsClientModule.java
addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloContentAccessResource.java
clients/core-java/src/main/java/org/commonjava/indy/client/core/Indy.java
clients/core-java/src/main/java/org/commonjava/indy/client/core/IndyClientHttp.java
pom.xml
subsys/http/src/main/java/org/commonjava/indy/subsys/http/IndyHttpProvider.java

* Adding shutdownNow() feature to jhttpc, and wiring into Indy client API
* Adding @REST annotation to FoloContentAccessResource

Catch up to changes in Indy 1.8.x

---

addons/folo/common/src/main/java/org/commonjava/indy/folo/change/FoloExpirationWarningListener.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCache.java
deployments/pom.xml
deployments/record-extractor/pom.xml
deployments/record-extractor/src/main/java/org/commonjava/indy/tools/folo/record/ExtractOptions.java
deployments/record-extractor/src/main/java/org/commonjava/indy/tools/folo/record/Main.java
pom.xml

Also, add a small client that can deserialize a backup tracking record file and export to JSON

Add warning when folo-in-progress entries are expired

---

Jenkinsfile
core/src/test/java/org/commonjava/indy/core/conf/DefaultIndyConfigFactoryTest.java

The Jenkins on nos-automation will be using it to trigger a build. And the new Jenkins takes no more than 39 min.

Add Jenkinsfile for nos-automation

---

Jenkinsfile

Support snapshot deployment. I have provisioned a proper settings.xml to nos-automation slave.

Update Jenkinsfile to support snapshot

---

addons/diagnostics/common/src/main/java/org/commonjava/indy/diag/log/LoggerDTO.java
addons/diagnostics/common/src/main/java/org/commonjava/indy/diag/log/LoggerManager.java
addons/diagnostics/jaxrs/src/main/java/org/commonjava/indy/diag/bind/jaxrs/DiagnosticsResource.java

* GET /api/diag/logger/configured/all: get all configured logger status
* GET /api/diag/logger/name/$name: get logger status by logger name
* GET /api/diag/logger/configured/name/$name: get configured logger status
by logger name
* PUT /api/diag/logger/name/$name/$level: change logger level by name

Add rest endpoint to manipulate current logger status

---

addons/diagnostics/jaxrs/src/main/java/org/commonjava/indy/diag/bind/jaxrs/DiagnosticsResource.java

And change logger/all to logger/configured/all which is more exact it
is providing

Changed return message of configured/name logger if not found

---

clients/core-java/src/main/java/org/commonjava/indy/client/core/Indy.java
clients/core-java/src/main/java/org/commonjava/indy/client/core/IndyClientHttp.java

The update allows to specify which Logging MDC values are copied to http request headers made by Indy client.

Pass defined Logging MDC as request headers.

---

Jenkinsfile
addons/content-browse/jaxrs/src/main/java/org/commonjava/indy/content/browse/bind/jaxrs/ContentBrowseResource.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/ctl/FoloAdminController.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCache.java
addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/content/DuplicateStoreAndVerifyTrackedRecordTest.java
addons/folo/model-java/src/main/java/org/commonjava/indy/folo/dto/TrackedContentEntryDTO.java
addons/folo/model-java/src/test/java/org/commonjava/indy/folo/model/TrackedContentEntryTest.java
addons/folo/model-java/src/test/java/org/commonjava/indy/folo/model/TrackedContentEntryV2.java
addons/implied-repos/common/src/main/java/org/commonjava/indy/implrepo/change/ImpliedRepositoryDetector.java
addons/implied-repos/ftests/src/main/java/org/commonjava/indy/implrepo/skim/ReuseExistingRepoIntoConfiguredGroupTest.java
api/src/main/java/org/commonjava/indy/data/StoreValidator.java
api/src/main/java/org/commonjava/indy/util/ApplicationHeader.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java
boot/jaxrs/src/main/java/org/commonjava/indy/boot/jaxrs/IndyDeployer.java
clients/core-java/src/main/java/org/commonjava/indy/client/core/module/IndyContentClientModule.java
core/src/main/java/org/commonjava/indy/data/DefaultStoreValidator.java
db/common/src/main/java/org/commonjava/indy/db/common/AbstractStoreDataManager.java
ftests/core/src/main/java/org/commonjava/indy/data/DefaultStoreValidatorTest.java
ftests/core/src/main/java/org/commonjava/indy/jaxrs/ContentBrowseHeadRequestTest.java
models/core-java/src/main/java/org/commonjava/indy/model/core/dto/DirectoryListingDTO.java
subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/ResponseHelper.java
subsys/metrics/prometheus/src/main/java/org/commonjava/indy/metrics/prometheus/IndySampleBuilder.java
subsys/metrics/prometheus/src/main/java/org/commonjava/indy/metrics/prometheus/PrometheusDeployment.java
uis/layover/package-lock.json
uis/layover/package.json

This feature branch may stay for a while. I merge master to this branch so they don't diverge too far.

Master integration pathmap mergemaster

---

Jenkinsfile

* switch to using openshift api to control/follow image build
* fix hook url var to my_bc in Jenkinsfile
* provide better feedback about bc selection process
* typo in stage end brace

Cherry-pick: switch to using openshift api to control/follow image build (#1415)

---

deployments/pathmap-migrator/src/main/java/org/commonjava/indy/pathmap/migrate/ScanCmd.java

And concurrently run scan from package level

Avoid one not needed traverse of first level package path

---

Jenkinsfile

I fix (remove) some dup lines that caused the CI failure. Push it again. I will abandon old PR if this passes.

Add data_tarball_url so we can incorporate default promotion rules in image build

---

api/src/main/java/org/commonjava/indy/metrics/RequestContextHelper.java
subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/ResourceManagementFilter.java
subsys/metrics/reporter/src/main/java/org/commonjava/indy/metrics/jaxrs/interceptor/MetricsInterceptor.java

…then report these in the REST end log

Accumulate timing info for different types of calls in a given user request

---

filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java
filers/default/src/main/java/org/commonjava/indy/filer/def/IOLatencyDecorator.java
filers/default/src/main/java/org/commonjava/indy/filer/def/TimingInputStream.java
filers/default/src/main/java/org/commonjava/indy/filer/def/TimingOutputStream.java
pom.xml
subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/ResourceManagementFilter.java
subsys/metrics/reporter/src/main/java/org/commonjava/indy/metrics/IndyMetricsManager.java
subsys/metrics/reporter/src/main/java/org/commonjava/indy/metrics/jaxrs/interceptor/MetricsInterceptor.java

fixes NPE that came out in testing

Fix cumulative timing measurement and add accumulation for non-intercepted metrics

---

subsys/metrics/reporter/src/main/java/org/commonjava/indy/metrics/IndyMetricsManager.java

Seems this accumulating log is overflowing stage indy log now, so I level it down to debug here.

Level down metricsManager log for accumulating to trace

---

db/infinispan/src/main/java/org/commonjava/indy/infinispan/data/InfinispanStoreDataManager.java
db/infinispan/src/test/src/org/commonjava/indy/infinispan/data/InfinispanGroupManagementTest.java
db/infinispan/src/test/src/org/commonjava/indy/infinispan/data/InfinispanTCKFixtureProvider.java
test/db/src/main/java/org/commonjava/indy/core/data/GroupDataManagerTCK.java

And following:
* One more tck case for complex group hierarchy for affected by
testing
* Removed commented code in infinispan data store manager for pretty

Add tck for ispn store data manager

---

db/common/src/main/java/org/commonjava/indy/db/common/DefaultArtifactStoreQuery.java

This getArtifactStore resides in a deep loop, which will cause serious
performance problem if the loop size is very huge(Actually it is). So
need to extract it out from this loop.

Extract getStore operation from deep loop for affected by

---

addons/content-index/src/main/java/org/commonjava/indy/content/index/NFCContentListener.java

Today when I do another round of load-testing, I fount that the upload speed is much better now, but the download speed is growing worse. After checking code, I found the most possible problem is the NFCContentListener.nfcClearByContaining. It is also referring the getGroupsAffectedBy ops. So that means each new content index added to cache will trigger this time-consuming ops, and it happens very frequently in download process. So I thread-off it again here.

Thread-off getAffectedBy ops in NFCContentListener

---

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java

* Simplify lambda
* Remove useless null check
* Use try resource instead
* Charset standardization

Code optimization - MavenMetadataGenerator

---

deployments/launcher/pom.xml
deployments/launcher/src/main/resources/META-INF/beans.xml
embedder/pom.xml
embedder/src/main/resources/META-INF/beans.xml
pom.xml
subsys/honeycomb/src/main/resources/default-honeycomb.conf
subsys/jaxrs/pom.xml
subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/IndyDeployment.java
subsys/newrelic/pom.xml
subsys/newrelic/src/main/conf/conf.d/newrelic.conf
subsys/newrelic/src/main/java/org/commonjava/indy/subsys/newrelic/NewRelicFilter.java
subsys/newrelic/src/main/java/org/commonjava/indy/subsys/newrelic/NewRelicManager.java
subsys/newrelic/src/main/java/org/commonjava/indy/subsys/newrelic/config/NewRelicConfiguration.java
subsys/newrelic/src/main/java/org/commonjava/indy/subsys/newrelic/interceptor/NewRelicInterceptorUtils.java
subsys/newrelic/src/main/java/org/commonjava/indy/subsys/newrelic/interceptor/NewRelicMeasureInterceptor.java
subsys/newrelic/src/main/java/org/commonjava/indy/subsys/newrelic/interceptor/NewRelicWrapperEndInterceptor.java
subsys/newrelic/src/main/java/org/commonjava/indy/subsys/newrelic/interceptor/NewRelicWrapperInterceptor.java
subsys/newrelic/src/main/java/org/commonjava/indy/subsys/newrelic/interceptor/NewRelicWrapperStartInterceptor.java
subsys/newrelic/src/main/resources/META-INF/beans.xml
subsys/newrelic/src/main/resources/default-newrelic.conf
subsys/pom.xml

Also, adding other Honeycomb interceptors to the beans.xml to make sure they work.

New Relic telemetry support

---

filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java
filers/default/src/main/java/org/commonjava/indy/filer/def/conf/DefaultStorageProviderConfiguration.java

This pr is the Indy conterpart for path-map dedup pattern.

Add deduplicatePattern for generic and npm filesystem

---

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/change/MetadataMergePomChangeListener.java
addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java
uis/layover/app/index.html
uis/layover/app/js/controllers.js
uis/layover/app/js/services.js
uis/layover/app/partials/cache-delete.html

Fix a few log messages. Update maintanance ui a bit, update "Delete Cache" to "Delete Metadata", add "Thread Dump" menu.

Correct log message in pomupdatelistener and update the maintenance ui

---

deployments/launcher/pom.xml
pom.xml

to replace release plugin dependency check

add enforcer plugin for enable enforcer:enforce check when release new version

---

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyMITMSSLServer.java

This PR adds changes to the Indy proxy man in the middle server.
Using a shared field the request and response threads work together more effectively. Responsibility to cleanup is assigned to the request thread.
Whereas the response handler thread can be initiated when a timeout happens.  The response thread sets a field as suggested in #1521 
Also set on the ServerSocket object is a timeout. Ensures that if a timeout occurs during the window then the call to .accept() will timeout. Allowing the proxy server to recover from the timeout.

Canceled request causes NullPointerException and perf issue.

---

pom.xml

Galley 1.2 delivers an important fix for download job (clean finished http download job in finally block).

Update galley version

---

addons/template/client-java/pom.xml
addons/template/common/pom.xml
addons/template/ftests/pom.xml
addons/template/jaxrs/pom.xml
addons/template/model-java/pom.xml
addons/template/pom.xml
bin/mkaddon.py

* Make it work in python3
* Fix version missing for pom parent

Fix addon make script

---

api/src/main/java/org/commonjava/indy/conf/DefaultIndyConfiguration.java
api/src/main/java/org/commonjava/indy/conf/IndyConfiguration.java
core/src/main/java/org/commonjava/indy/core/ctl/NfcController.java
core/src/main/java/org/commonjava/indy/core/inject/CassandraNotFoundCache.java
core/src/main/java/org/commonjava/indy/core/inject/CoreProvider.java
core/src/main/java/org/commonjava/indy/core/inject/IspnNotFoundCache.java

I really doubt the reboot issue is caused by NFC. but in case we want to revert to ISPN nfc, we can use this.

Support different NFC impl

---

addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessHandler.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/util/RequestUtils.java
deployments/standalone/launcher/pom.xml
deployments/standalone/pom.xml
subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/IndyResources.java

Will use this more widely in coming features, like static-proxy

Extract directory listing check to RequestUtils for usage in other modules

---

addons/content-index/src/main/java/org/commonjava/indy/content/index/IndexingContentManagerDecorator.java
addons/path-mapped/common/src/main/java/org/commonjava/indy/pathmapped/inject/PathMappedGroupRepositoryFilter.java
addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenMetadataGenerator.java
api/src/main/java/org/commonjava/indy/conf/DefaultIndyConfiguration.java
api/src/main/java/org/commonjava/indy/conf/IndyConfiguration.java
api/src/main/java/org/commonjava/indy/content/GroupRepositoryFilter.java
boot/jaxrs/src/main/java/org/commonjava/indy/boot/jaxrs/JaxRsBooter.java
core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java
core/src/main/java/org/commonjava/indy/core/content/group/AbstractGroupRepositoryFilter.java
core/src/main/java/org/commonjava/indy/core/content/group/GroupRepositoryFilterManager.java
core/src/main/java/org/commonjava/indy/core/content/group/ReversePatternNameGroupRepositoryFilter.java
core/src/main/resources/default-main.conf
deployments/launcher/src/main/etc/indy/main.conf
embedder/pom.xml
filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java
ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RepositoryFilterTest.java
ftests/core/src/main/resources/repofilter/rh-pattern-repofilter.groovy
pom.xml
subsys/metrics/core/src/main/conf/conf.d/metrics.conf
subsys/metrics/reporter/src/main/conf/conf.d/metrics.conf
subsys/metrics/reporter/src/main/java/org/commonjava/indy/metrics/conf/IndyMetricsConfig.java
subsys/metrics/reporter/src/main/resources/default-metrics.conf

Cherry picked 4 latency fixes from master to maint.

Cherry pick latency fixes from master to maint

---

core/src/main/java/org/commonjava/indy/core/content/DefaultContentDigester.java
pom.xml

Apply pathmap 1.3-SNAPSHOT (consistency level fix)

---

models/core-java/src/main/java/org/commonjava/indy/stats/IndyDeprecatedApis.java

We found some weird issue from prod, that the apiVersion header got from client is "unknown", which caused NUmberFormatException in code. So this code is to solve the problem.

Fix bug of unknown api version

---

api/src/main/java/org/commonjava/indy/conf/DefaultIndyConfiguration.java
api/src/main/java/org/commonjava/indy/conf/IndyConfiguration.java
api/src/main/java/org/commonjava/indy/util/ApplicationStatus.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/admin/DeprecatedStoreAdminHandler.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/admin/StoreAdminHandler.java
clients/core-java/src/main/java/org/commonjava/indy/client/core/module/IndyStoresClientModule.java
core/src/main/java/org/commonjava/indy/core/ctl/AdminController.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/DeleteGroupWithContentTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/DeleteHostedRepoWithContentTest.java

Load test created many group/hosted repos on stage. This pr is to remove them together with their content. To safe guard the content deletion, I add a config.

Allow delete repo with content

---

addons/path-mapped/common/src/main/java/org/commonjava/indy/pathmapped/inject/PathMappedGroupRepositoryFilter.java
subsys/cassandra/src/main/java/org/commonjava/indy/subsys/cassandra/CassandraClient.java

This is a cherry-pick from maint branch.
* Fix npe in getStrategyPath
* Set cassandra so timeout to 120s

Fix npe in getStrategyPath (#1587)

---

Jenkinsfile
addons/content-browse/ui/pom.xml
pom.xml
uis/layover/pom.xml

This pr makes front-end-maven-plugin to be able to use a specified npm
registry in system env_var named "NPMREGISTRY" to replace default npm
registry

Update npm registry to point to specified one

---

addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessHandler.java

Seems npm direcotry listing is different from maven way, so I revert  my change of npm content directory listing telling condition here.

Fix wrong directory listing for npm content

---

addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/group/PackageMetadataMerger.java
addons/pkg-npm/common/src/test/java/org/commonjava/indy/pkg/npm/content/group/PackageMetadataMergerTest.java
addons/pkg-npm/model-java/src/main/java/org/commonjava/indy/pkg/npm/model/io/VersionMetadataDeserializer.java

Missing the module in the merge method.

Register the packageSerializerModule inside merge as well

---

subsys/cassandra/src/main/java/org/commonjava/indy/subsys/cassandra/CassandraClient.java
subsys/cassandra/src/main/java/org/commonjava/indy/subsys/cassandra/ConfigurableRetryPolicy.java
subsys/cassandra/src/main/java/org/commonjava/indy/subsys/cassandra/config/CassandraConfig.java

* Support retries when Cassandra read timeout
* Add warn message

[Cherry-pick] Support retries when Cassandra read timeout (#1591)

---

addons/path-mapped/common/src/main/java/org/commonjava/indy/pathmapped/cache/PathMappedMavenGACache.java
addons/path-mapped/common/src/main/java/org/commonjava/indy/pathmapped/inject/PathMappedMavenGACacheGroupRepositoryFilter.java
api/src/main/java/org/commonjava/indy/conf/DefaultIndyConfiguration.java
api/src/main/java/org/commonjava/indy/conf/IndyConfiguration.java
core/src/main/java/org/commonjava/indy/core/inject/CassandraNotFoundCache.java
deployments/launcher/src/main/etc/indy/main.conf
ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java
ftests/core/pom.xml
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RepositoryFilterGACacheTest.java
pom.xml
subsys/cassandra/src/main/java/org/commonjava/indy/subsys/cassandra/CassandraClient.java
subsys/cassandra/src/main/java/org/commonjava/indy/subsys/cassandra/util/SchemaUtils.java

This is for MMENG-390. Design doc is at https://docs.engineering.redhat.com/display/HTD/Use+GA+cache+to+improve+maven+retrieval
This is a pretty big pr. I'd like to hear from you any questions.

Support GA cache repository filter

---

bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/admin/MaintenanceHandler.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/util/MaintenanceController.java

Get tombstone stores (no content and not in any group) for clean up. This api will only do the query. We will use a script to call the original delete-store api to delete them.

Get tombstone stores

---

core/src/main/java/org/commonjava/indy/core/expire/ScheduleManager.java

Add this to monitor the whole content expiring process.

Add one more logger for content expiring

---

pom.xml

Prepare for next indy release.

Update pathmapped to 1.5

---

pom.xml

to use the latest pathmap fix.

Update pathmap to 1.6-snapshot

---

db/common/src/main/java/org/commonjava/indy/db/common/DefaultArtifactStoreQuery.java

This is an amendment for previous pr #1654 to specify which store has problem.

Update warn log to identify store in question

---

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenContentsFilteringTransferDecorator.java

This implements a method necessary now that FilterOutputStream has been removed from inheritance hierarchy.

Add bulk write method for stream.

---

addons/diagnostics/common/src/main/java/org/commonjava/indy/diag/data/DiagnosticsManager.java
addons/diagnostics/jaxrs/src/main/java/org/commonjava/indy/diag/bind/jaxrs/DiagnosticsResource.java

Enable filtering of thread dump results by state

---

models/core-java/src/main/java/org/commonjava/indy/model/core/RemoteRepository.java

This will be used in static-proxy content listing enhancement to get the correct content listing result.

Add a new flag in RemoteRepository to identify if remote host is a indy instance

---

bin/test-setup.sh
uis/layover/app/index.html
uis/layover/app/js/app.js
uis/layover/app/js/controllers.js
uis/layover/app/js/utils.js

As title. 
This pr also includes a change in test-setup.sh. By default it starts local indy via disk storage so we won't need a local cassandra up.

UI list group/repos by packageType

---

deployments/launcher/src/main/resources/META-INF/beans.xml
embedder/src/main/resources/META-INF/beans.xml

Apply o11 flat interceptors

---

addons/content-browse/client-java/src/main/java/org/commonjava/indy/content/browse/client/IndyContentBrowseClientModule.java
addons/repo-proxy/common/pom.xml
addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/ContentBrowseRemoteIndyListingRewriteManager.java
addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/RepoProxyController.java
addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyBlockListTest.java
addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyFeaturesBundledTest.java
addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyPatternsTest.java
addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyRemoteIndyListingRewriteGetTest.java
addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyRemoteIndyListingRewriteHeadTest.java
addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/TestUtils.java

Closed this pr by accident, so restore it here.

Static-proxy: Support head request remote indy listing content rewriting

---

addons/content-browse/client-java/src/main/java/org/commonjava/indy/content/browse/client/IndyContentBrowseClientModule.java
addons/content-browse/ui/package-lock.json
addons/repo-proxy/common/pom.xml
addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/ContentBrowseRemoteIndyListingRewriteManager.java
addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/ContentBrowseRewriteResponseDecorator.java
addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/ContentReplacingOutputStream.java
addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/NPMMetadtaRewriteResponseDecorator.java
addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/RepoProxyController.java
addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/RepoProxyUtils.java
addons/repo-proxy/common/src/main/java/org/commonjava/indy/repo/proxy/conf/RepoProxyConfig.java
addons/repo-proxy/common/src/test/java/org/commonjava/indy/repo/proxy/RepoProxyUtilsTest.java
addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyBlockListTest.java
addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyFeaturesBundledTest.java
addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyPatternsTest.java
addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyRemoteIndyListingRewriteGetTest.java
addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/RepoProxyRemoteIndyListingRewriteHeadTest.java
addons/repo-proxy/ftests/src/main/java/org/commonjava/indy/repo/proxy/ftest/TestUtils.java
addons/repo-proxy/jaxrs/src/main/java/org/commonjava/indy/repo/proxy/servlet/RepositoryProxyFilter.java
clients/core-java/src/main/java/org/commonjava/indy/client/core/IndyClientHttp.java
deployments/standalone/launcher/pom.xml
deployments/standalone/pom.xml
pom.xml
uis/layover/package-lock.json
uis/layover/package.json

Merge recent master changes to o11yphant branch.

O11yphant merge master

---

pom.xml

galley 1.4-snap -> 1.4
path-mapped-storage 1.7-snap -> 1.7

Update lib versions

---

pom.xml

Version bump weft to 1.7-SNAPSHOT version.

---

api/pom.xml

Adds missing activation-api library.

Added JDK11 dependency to indy-api project.

---

subsys/cassandra/src/main/java/org/commonjava/indy/subsys/cassandra/CassandraClient.java
subsys/honeycomb/pom.xml
subsys/honeycomb/src/main/java/org/commonjava/indy/subsys/honeycomb/IndyCassandraConnectionRootSpanFields.java
subsys/honeycomb/src/main/java/org/commonjava/indy/subsys/honeycomb/config/IndyHoneycombConfiguration.java

This is the Indy impl for abstract CassandraConnectionRootSpanFields.

Add IndyCassandraConnectionRootSpanFields

---

uis/layover/package-lock.json
uis/layover/package.json

This reverts commit ed4363db19cdb19181cf8d323523857e9800e1da.
It fixes MMENG-757 UI broken issue.

Revert "Bump angular from 1.5.8 to 1.8.0 in /uis/layover"

---

addons/koji/common/src/main/java/org/commonjava/indy/koji/inject/KojijiProvider.java
addons/pkg-maven/common/src/test/java/org/commonjava/indy/pkg/maven/content/MavenContentFilteringTransferDecoratorTest.java
filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java
pom.xml
subsys/metrics/pom.xml

For what it worth, from this pr we get rid of 100% direct dropwizard dependency.

Adopt galley/weft/pathmap/kojiji o11yphant changes

---

addons/promote/common/pom.xml
addons/promote/common/src/main/data/promote/rules/npm-no-pre-existing-paths.groovy
addons/promote/common/src/main/data/promote/rules/npm-parsable-package-meta.groovy
addons/promote/common/src/main/data/promote/rules/npm-version-pattern.groovy
addons/promote/common/src/main/java/org/commonjava/indy/promote/conf/PromoteConfig.java
addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidationTools.java
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/rule/NPMParsablePkgMetaRuleByPathTest.java
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/rule/NPMVersionPatternRuleTest.java
addons/promote/ftests/src/main/resources/npm-parsable-pkg-meta/package.json
addons/promote/ftests/src/main/resources/npm-version-pattern/package-invalid.json
addons/promote/ftests/src/main/resources/npm-version-pattern/package-redhat-scoped-invalid.json
addons/promote/ftests/src/main/resources/npm-version-pattern/package-redhat-scoped-valid.json
addons/promote/ftests/src/main/resources/npm-version-pattern/package-scoped-invalid.json
addons/promote/ftests/src/main/resources/npm-version-pattern/package-scoped-valid.json
addons/promote/ftests/src/main/resources/npm-version-pattern/package-valid.json

* npm-no-pre-existing-paths.groovy
* npm-version-pattern.groovy
* npm-parsable-package-meta.groovy

Promote: Add npm promotion rules and ftests

---

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionHelper.java
addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionManager.java
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/PromoteMetadataShouldSkipWithReadonlyTest.java

For pr: https://github.com/Commonjava/indy/pull/1721

Merge last commit to maint

---

subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/GoldenSignalsFilter.java

Add debug message to GoldenSignalsFilter

---

core/src/test/java/org/commonjava/indy/fixture/MockTestProvider.java
subsys/groovy/src/test/java/org/commonjava/indy/subsys/template/fixture/TestProvider.java
subsys/honeycomb/src/main/java/org/commonjava/indy/subsys/honeycomb/config/IndyHoneycombConfiguration.java

Add honeycomb console transport for debug purpose

---

addons/pkg-maven/common/pom.xml
models/core-java/pom.xml
subsys/groovy/pom.xml

When I do pure build in my machine, I found these missing direct deps
cause build error, so here add them.

Add some missing direct dependencies

---

pom.xml

Bacause the http2 fix in 1.5 snapshot is not useful.

Revert propulsorVersion to 1.4

---

addons/promote/common/src/main/data/promote/rules/maven-project-version-pattern.groovy
addons/promote/common/src/main/data/promote/rules/npm-version-pattern.groovy
addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/model/ValidationRequest.java
addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/ValidationRuleSet.java

This PR looks to improve the efficiency of promotion. Avoiding the repeated creation of regex objects. Typically used by Groovy scripts.
This needs co-ordinating with configuration management. To promote the changes to Groovy scripts in each environment.

Improved pattern matching processing during promotion.

---

addons/koji/common/src/main/java/org/commonjava/indy/koji/conf/IndyKojiConfig.java

I hit this error msg issue when running the latest img today.

Fix koji config error message

---

core/src/main/conf/conf.d/durable-state.conf
core/src/main/java/org/commonjava/indy/core/conf/IndyDurableStateConfig.java
core/src/main/resources/default-durable-state.conf

To keep them consistent and extendable, let's move all the config for durable state into this config. 
For: https://projects.engineering.redhat.com/browse/MMENG-918

Add configuration for all durable state

---

pom.xml

path-mapped-storage to 1.8
o11yphant to 1.0
galley to 1.5
kojiji to 2.13
weft to 1.18

Update SNAPSHOT version for deps

---

core/src/main/java/org/commonjava/indy/core/expire/ScheduleValue.java

Fix ScheduleValue Class is non-public or has no public no-arg constructor

---

pom.xml

O11 has a minor fix to avoid dup init of metrics reporters.

Update o11 to 1.2

---

addons/koji/common/src/main/java/org/commonjava/indy/koji/data/KojiRemovePemMigrationAction.java

Most of the koji repos have no description in place, so need to identify it by the name.

Fix for filtering the koji repos

---

core/src/main/java/org/commonjava/indy/core/expire/InfinispanScheduleExpirationMigrationAction.java
core/src/main/java/org/commonjava/indy/core/expire/ScheduleManager.java
core/src/main/java/org/commonjava/indy/core/expire/cache/ScheduleCacheProducer.java
subsys/infinispan/src/main/resources/infinispan-jdbc.xml
subsys/infinispan/src/main/resources/infinispan.xml

* Add new data migrator to address expiration value type change.
* Fix some NPE problems in ScheduleManager for new expiration value
type change.

Add schedule expiration cache migrator

---

addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromoteValidationsManager.java

Logs to track the added, removed and changed rules & rule-sets after reloading.(rules changes can not be tracked yet)

Add logging for promotion validation rule bundles reload

---

Jenkinsfile
pom.xml

This PR changes the compiler configuration to generate JDK11 bytecode (major version: 55).

Switched compliation to generate JDK11 bytecode.

---

Jenkinsfile
pom.xml

This reverts commit 85c3af868c2afcad7a331ad7f5ef0e97648c769f.
I had to revert this Commonjava/indy#1788 until we get the CI system fixed to pull the latest jenkins maven agent image version.

Revert "Switched compliation to generate JDK11 bytecode. (#1778)"

---

Jenkinsfile

This change is intended to test the Jenkins file environment variable scope settings.
The CI workflow stage outputs are not changed.

Added little test to check env variable can be set.

---

Jenkinsfile
pom.xml

Revert "Re-apply "Switched compliation to generate JDK11 bytecode. (#1778)""

---

embedder/pom.xml
ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java
ftests/common/src/main/resources/test-cassandra.yaml

This avoids problems with cassandra-maven-plugin on JDK11

Switch ftests over to use dynamically provisioned embedded cassandra

---

addons/folo/common/src/main/java/org/commonjava/indy/folo/FoloUtils.java
addons/hosted-by-archive/client-java/src/main/java/org/commonjava/indy/hostedbyarc/client/IndyHostedByArchiveClientModule.java
addons/path-mapped/jaxrs/src/main/java/org/commonjava/indy/pathmapped/jaxrs/PathMappedResource.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/ContentAccessHandler.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/admin/DeprecatedStoreAdminHandler.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/admin/ReplicationHandler.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/admin/StoreAdminHandler.java
clients/core-java/src/main/java/org/commonjava/indy/client/core/helper/HttpResources.java
core/src/main/java/org/commonjava/indy/core/conf/DefaultIndyConfigFactory.java

This PR looks to plug a few causes of resource leaks. Closing of resources.

Code changes to eliminate InputStream IO resource leaks.

---

Jenkinsfile
toolchains.xml

This PR is the 1st of two PRs to solve #1621.
Changes introduced here will provide the necessary toolchains.xml file to the build environment and the command line flag to declare the file.

Add Maven toolchains support to the environment.

---

Jenkinsfile

This commit fixes the command line options for the CI to execute the verify phase.

Set env variable for verify phase and set toolchains on command line.

---

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyMITMSSLServer.java

This PR ensures the resource is closed.

Fix to close resource when exception is thrown.

---

addons/httprox/common/src/main/java/org/commonjava/indy/httprox/handler/ProxyMITMSSLServer.java

This will help diagnose problem clients.

Add useful exception message.

---

addons/koji/common/src/main/resources/koji_metadata.proto
addons/pkg-maven/common/src/main/resources/metadata_info.proto
addons/pkg-maven/common/src/main/resources/metadata_key.proto

https://developers.google.com/protocol-buffers/docs/overview
```
Required Is Forever You should be very careful about marking fields as required.
If at some point you wish to stop writing or sending a required field, it will
be problematic to change the field to an optional field – old readers will consider
messages without this field to be incomplete and may reject or drop them
unintentionally. You should consider writing application-specific custom validation
routines for your buffers instead. Some engineers at Google have come to the
conclusion that using required does more harm than good; they prefer to use only
optional and repeated.
```

Update the field rule from required to optional

---

pom.xml
subsys/infinispan/pom.xml

Fix the error from indy-perf: `Caused by: java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder`

Add gson for infinispan hotrod client query

---

addons/schedule/common/src/main/java/org/commonjava/indy/schedule/ScheduleDBUtil.java
addons/schedule/model-java/pom.xml
addons/schedule/model-java/src/main/java/org/commonjava/indy/schedule/datastax/model/DtxExpiration.java

Updating the clustering column from the UID to storeKey and jobName, to avoid to generate multiple expiration for the same schedule during the same period, that happens when the same file is accessed several times and the schedule timeout is reset after each access, then a new expiration is generated/stored for each update of the same schedule. And we only need to keep the latest one for the same storeKey and jobName.
for instance the following records generated on indy-perf when i checked the expiration table:
```
expirationpid | scheduleuid                          | expirationtime                  | jobname                           | storekey
---------------+--------------------------------------+---------------------------------+-----------------------------------+-------------------- …
```

Update the clustering column for expiration

---

pom.xml

This PR looks to finish all the changes necessary to solve #1505 .

Version bump target bytecode generation to JDK11.

---

uis/layover/app/js/app.js
uis/layover/app/js/services.js

I found the UI "New..." button not work. This fix it.

Fix UI new repo button not work issue

---

scripts/move-repos/README.md
scripts/move-repos/get-repos.sh
scripts/move-repos/import-repos.py

This script is used to move repos from one instance to another. We will use it when deploying Indy monolith cluster. Please refer to the README for more information.

Add scripts/move-repos for repo migration

---

addons/content-index/src/main/java/org/commonjava/indy/content/index/ISPFieldStringKey2StringMapper.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloCacheProducer.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/data/idxmodel/StoreKeyFieldBridge.java
addons/folo/common/src/test/java/org/commonjava/indy/folo/data/FoloRecordCacheTest.java
addons/folo/common/src/test/resources/infinispan-test.xml
addons/httprox/common/src/test/java/org/commonjava/indy/httprox/HttpProxyTest.java
addons/httprox/common/src/test/resources/infinispan-test.xml
addons/pkg-maven/common/src/test/java/org/commonjava/indy/pkg/maven/content/MetadataCacheManagerTest.java
addons/pkg-maven/common/src/test/resources/infinispan-test.xml
addons/promote/common/src/test/java/org/commonjava/indy/promote/data/PromotionManagerTest.java
addons/schedule/common/src/test/java/org/commonjava/indy/schedule/ScheduleTest.java
core/src/test/java/org/commonjava/indy/core/ctl/ContentControllerTest.java
core/src/test/resources/infinispan-test.xml
db/infinispan/src/main/java/org/commonjava/indy/infinispan/data/InfinispanStoreDataManager.java
db/infinispan/src/test/java/org/commonjava/indy/infinispan/data/InfinispanGroupManagementTest.java
db/infinispan/src/test/java/org/commonjava/indy/infinispan/data/InfinispanTCKFixtureProvider.java
db/infinispan/src/test/resources/infinispan-test.xml
deployments/cache-migrator/test-env/indy-env/infinispan.xml
ftests/common/src/main/resources/infinispan-test.xml
pom.xml
subsys/infinispan/src/main/resources/infinispan-cluster.xml
subsys/infinispan/src/main/resources/infinispan-jdbc.xml
subsys/infinispan/src/main/resources/infinispan.xml

1. Bump the version of protostreamVersion to 4.3.5.Final
2. Fix the test based on the doc: https://infinispan.org/docs/11.0.x/titles/upgrading/upgrading.html

Fix the test relates to ispn 11.x 

---

addons/folo/common/src/main/java/org/commonjava/indy/folo/action/FoloISPN2CassandraMigrationAction.java

It seems we need more controls over the folo migration action. Some can fail and we need to log the failed ones.

Catch exceptions in FoloISPN2CassandraMigrationAction

---

pom.xml

Fix version for subsys-trace

---

api/src/main/java/org/commonjava/indy/conf/DefaultIndyConfiguration.java
clients/core-java/src/main/java/org/commonjava/indy/client/core/helper/HttpResources.java
rest/api/src/test/java/org/commonjava/indy/rest/apigen/SwaggerExportTest.java

This should be the reason for ftest failures.

Fix NPE in ftests

---

addons/folo/common/src/main/java/org/commonjava/indy/folo/action/FoloISPN2CassandraMigrationAction.java

This include:
1. write completed and failed folo ids to /opt/indy/var/lib/indy/data/folo/{completed.out / failed.out}. So we can look at them.
2. support re-run. when rerun the migration, it loads the prev completed ids and skip them.

More control over folo migration to support retry

---

addons/event-publisher/common/pom.xml
addons/event-publisher/common/src/main/java/org/commonjava/indy/event/publisher/FileEventPublisher.java
addons/event-publisher/common/src/main/java/org/commonjava/indy/event/publisher/KafkaEventPublisher.java
addons/event-publisher/pom.xml
addons/pom.xml
pom.xml

To ref the fileEvent models defined in https://github.com/Commonjava/indy-event-model. And for kafka producer, since we already have one for log stuff, I will figure out how to introduce another one, as there are two different kafka instances.

Produce file event to kafka

---

addons/promote/common/src/main/data/promote/rules/maven-no-pre-existing-paths.groovy
addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/rule/NoPreExistingPaths_IdempotentPromotion_RuleTest.java

Fix for https://projects.engineering.redhat.com/browse/MMENG-1505. Let's see if this works and then we can update the groovy file later.

Support idempotent promotion

---

core/src/main/java/org/commonjava/indy/core/content/ContentMetadataGenerator.java

Found some problems of checksum generation but can not reproduce on local, so add these logs for tracking

Add logs to track checksum generation

---

addons/koji/common/src/main/java/org/commonjava/indy/koji/inject/KojiTagInfoMarshaller.java

Try to fix the issue when I test the remote cache: koji-tags
`o.c.i.s.infinispan.RemoteCacheHandle no 10.0.39.36 - Failed to complete operation: No marshaller registered for Java type java.util.ArrayList`

try to fix the no marshaller issue

---

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/cache/MavenMetadataCacheListener.java

The downloadManager handles setting/resetting the Readonly flag against the hosted repository.

Fix the deletion of transfer on cache expired

---

addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCassandra.java

Add an error message instead of throwing Exception for Cassandra based folo handling

---

addons/path-mapped/jaxrs/src/main/java/org/commonjava/indy/pathmapped/jaxrs/PathMappedResource.java

Fix PathMappedResource get content_type

---

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/IndyKojiContentProvider.java

It still complains the no marshaller issue but different:
`No marshaller registered for Java type org.commonjava.indy.koji.content.KojiTagInfoEntry`
Since we need to register the marshaller classes before getting the remote cache. Actually there is already an existing injected koji-tags cache in this class, so no need to do that each time.

Using the injected cache instead

---

addons/promote/ftests/src/main/java/org/commonjava/indy/promote/ftest/HostedMetadataRemergedOnPathPromoteToReadonlyHostedTest.java
api/src/main/java/org/commonjava/indy/model/galley/CacheOnlyLocation.java
api/src/main/java/org/commonjava/indy/util/LocationUtils.java
core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java

Use NonReadonlyLocation when need to bypass the hosted readonly permission

---

addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloNPMContentAccessResource.java
addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/change/PackageStoreListener.java
addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/DecoratorUtils.java
addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/NPMPackageMaskingTransferDecorator.java
addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/NPMStoragePathCalculator.java
addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/PackageMetadataGenerator.java
addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/group/PackageMetadataMerger.java
core/src/main/java/org/commonjava/indy/core/content/DefaultDirectContentAccess.java
models/core-java/src/main/java/org/commonjava/indy/pkg/npm/model/NPMPackageTypeDescriptor.java

[Cherry-pick] Fix for NPM readonly issue and url handling

---

addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMRemoteMetadataContentDecorator_ProxyOriginTest.java
addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessHandler.java

* Replace npm ENTRY_POINT_BASE_URI if proxy-origin presented
* Add ftest

[Cherry-pick] Replace npm ENTRY_POINT_BASE_URI if proxy-origin presented (#1943)

---

core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/ReDownloadOnContentTransferExceptionTest.java

This PR aims to fail the request earlier when we ran into the communication exception with remote server, that was discussed in the issue: https://projects.engineering.redhat.com/browse/MMENG-1490 . And currently Indy returns null if there is such kind of exceptions.

Fail the request for any connection error with remote server

---

addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMReadonlyHostedDeleteFileTest.java
addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMReadonlyHostedDeleteMetadataTest.java
addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMReadonlyHostedStoreFileTest.java
addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessResource.java
core/src/main/java/org/commonjava/indy/core/content/DefaultContentManager.java
core/src/main/java/org/commonjava/indy/core/content/DefaultDownloadManager.java

* Allow force delte for npm metadata
* Fix npm meta deletion 404 issue and use one single delete REST method

[Cherry-pick] Allow force delte for npm metadata (#1950)

---

addons/pkg-npm/jaxrs/src/main/java/org/commonjava/indy/pkg/npm/jaxrs/NPMContentAccessHandler.java

I observed many concurrent npm package.json requests and sometimes the item.openInputStream reported IOException. 
This is not possible for normal cases, because just before the open call, there is an exists call which checks not null of "storageFile = pathDB.getStorageFile(...)". The open call use same check but got null.
This might happen when one request generated the metadata, but before it returns the input stream, the other request regenerate it and delete the prev entry.
This pr add a retry (less then 3 times) and wait (500 ms) to handle such race conditions.
This is for MMENG-1796.

Add retry for npm content openInputStream

---

subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/SlashTolerationFilter.java

Update the SlashTolerationFilter to use the filterChain instead of forward, and normalize the request url.

[Cherry-pick] Normalize the request url

---

.github/workflows/merge-build.yml
.github/workflows/pr-build.yml
addons/folo/ftests/src/main/java/org/commonjava/indy/folo/ftest/report/ReportIdsGettingTest.java
addons/schedule/common/pom.xml
addons/schedule/common/src/test/java/org/commonjava/indy/schedule/ScheduleTest.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/util/TransferStreamingOutput.java
db/cassandra/pom.xml
db/cassandra/src/test/java/org/commonjava/indy/cassandra/data/CassandraGroupManagementTest.java
db/cassandra/src/test/java/org/commonjava/indy/cassandra/data/CassandraStoreTest.java
embedder/pom.xml
ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractContentManagementTest.java
ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/admin/GetContentByPathmapAdminTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/category/ClusterTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/ContentDeletionMayDisruptGroupMetadataTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RepositoryFilterGACacheTest.java
pom.xml
subsys/cassandra/src/main/java/org/commonjava/indy/cassandra/testcat/CassandraTest.java
subsys/metrics/src/main/conf/conf.d/metrics.conf
subsys/metrics/src/main/resources/default-metrics.conf
subsys/trace/src/main/conf/conf.d/trace.conf
subsys/trace/src/main/resources/default-trace.conf

This change also updates the o11yphant dependency to **1.5-SNAPSHOT**.
Based on some quick testing in different configurations, this should FIX the performance problem Indy experiences when tracing is enabled.
Depends on: https://github.com/Commonjava/o11yphant/pull/62

Implement rate/size metrics for transfers and update trace/metric config examples

---

api/src/main/resources/extra-mime.types
subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/ResponseHelper.java

Seems we are using application/maven+xml as the media type for pom   file, and it is not a standard media type which may cause media type  parsing error in jaxrs. So we changed it to text/xml here.

Change the pom mediatype mapping to xml

---

pom.xml

Weft 1.20 include the fix for locker.

Update weft to 1.20

---

pom.xml

Update postgresql to 42.2.24

---

pom.xml

Ref the latest galley which supports checking file timeout before returning it.

Update galley to 1.7-SNAPSHOT

---

subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/IndyDeployment.java

This is a cherry-pick from master branch. thanks.

[Cherry-pick] Fix tolerating multi slashes anywhere at the path

---

filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java
filers/default/src/main/java/org/commonjava/indy/filer/def/conf/DefaultStorageProviderConfiguration.java
pom.xml

Enable storageTimeoutEnabled config and update to galley-1.7-snapshot.

Enable storageTimeoutEnabled

---

pom.xml

To include the allow removeEmptyDir fix.

Update pathmapped version to 2.0-SNAPSHOT

---

pom.xml

CVE: https://cve.report/CVE-2021-42550

Fix: upgrade logback to 1.2.9 for CVE issue

---

pom.xml

jackson: 2.10.1 -> 2.12.1
logback: 1.2.3 -> 1.2.9
swagger: 1.5.9 -> 1.6.4

[Master] upgrade pom versions for CVE issue

---

addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/NPMPackageMaskingTransferDecorator.java
core/src/main/java/org/commonjava/indy/core/ctl/ContentController.java
pom.xml

jsoup -> 1.14.2
undertow -> 2.1.8.Final
remove jdom

[master] Upgrade some poms for CVE warning

---

pom.xml

This reverts commit 0a9ac33698398bc8dd92bf35f464f9f47b67fe95. Indy on c2 hit a lot of conn leaks. Revert ispn to old version to test.

Revert "Update infinispan to 9.4.17.Final"

---

pom.xml

Update frontend plugin to 1.11.0

---

pom.xml

There are some fixes in infinispan side since 9.4.15.Final, details pls ref the following notes:
https://issues.redhat.com/secure/ConfigureReleaseNote.jspa?projectId=12310799&version=12354350
let's have a test first. thanks.

Update infinispan to 9.4.23.Final

---

addons/promote/common/src/main/java/org/commonjava/indy/promote/data/PromotionHelper.java

Fix the store query during promotion

---

pom.xml

This reverts commit 912ee2cbbf96c02cdea7dc85e440bbf0d6324770.

Revert "Update infinispan to 9.4.23.Final"

---

addons/folo/common/src/main/java/org/commonjava/indy/folo/data/DtxTrackingRecord.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCassandra.java

There is a hardcode table name in DtxTrackingRecord. This pr corrects it.

Fix DtxTrackingRecord table name

---

addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloGenericContentAccessResource.java

After moving generic proxy from Indy, we need to introduce this specific folo api for it, to accept the tracking_id.

Add folo resource for generic-http

---

addons/folo/common/src/main/java/org/commonjava/indy/folo/ctl/FoloAdminController.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecord.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/data/FoloRecordCassandra.java
addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloAdminResource.java

Unfortunately, the "recordManager instanceof FoloRecordCassandra" does not work after Weld injection. I fix it by add two legacy methods to interface.

Fix query for legacy folo

---

addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloAdminResource.java

This is the fix for [NCLSUP-627] (https://issues.redhat.com/browse/NCLSUP-627)

Return empty folo report when not found

---

filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java
filers/default/src/main/java/org/commonjava/indy/filer/def/conf/DefaultStorageProviderConfiguration.java
pom.xml

Adapt to the config changes in path map storage lib.

Add config for storage.physical.file.existence.check.enabled

---

addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMMetadataTimeoutNoSchedulerTest.java
core/src/main/java/org/commonjava/indy/core/conf/IndySchedulerConfig.java
pom.xml

This test disables Scheduler to test storage level timeout. It depends on https://github.com/Commonjava/galley/pull/387

Update Galley to 1.8-SNAPSHOT and add NPMMetadataTimeoutNoSchedulerTest

---

pom.xml

And removed plexus-container-default as it is not needed superficially

Some version bump for cve issues

---

bin/test-setup.sh

Fix test-setup.sh on Mac os

---

addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloGenericContentAccessResource.java

this should be set and will be checked in `FoloTrackingListener`.

Set origin_path on generic folo request

---

addons/schedule/common/src/test/java/org/commonjava/indy/schedule/ScheduleTest.java
api/src/main/java/org/commonjava/indy/conf/InternalFeatureConfig.java
core/src/main/java/org/commonjava/indy/core/change/StoreEnablementManager.java
ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RemoteRepoTimeoutDisablesStoreAndShowsInDisabledTimeoutsMapTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/content/RemoteRepoTimeoutDisablesThenReEnabledTest.java

This is for [MMENG-2974](https://issues.redhat.com/browse/MMENG-2974). I did not remove the feature directly but use a config to disable it.

Disable store auto disable and reenablement

---

addons/koji/common/src/main/java/org/commonjava/indy/koji/content/KojiMavenMetadataProvider.java

* Remove metadata cache for Koji Maven metadata
* Some IDE warnig fix

Code optimization

---

addons/sli/src/main/java/org/commonjava/indy/sli/metrics/IndyGoldenSignalsMetricSetProvider.java
pom.xml
subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/metrics/IspnCheckRegistrySet.java
subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/metrics/IspnRegistrySetProvider.java

* Remove kafka-log-appender as useless
* Upgrade kafka-clients to 3.1.1 due to cve
* Upgrade Infinispan to 9.4.24.Final

Upgrade o11yphant to 1.5-SNAPSHOT for cve fix

---

addons/pkg-maven/common/src/main/java/org/commonjava/indy/pkg/maven/content/MavenContentsFilteringTransferDecorator.java

Fix issue: Disable access to external entities in XML parsing
(based on: https://rules.sonarsource.com/java)

[ESS] fix the blocker vulnerability reported by sonarqube

---

addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/NPMStyleSuccessiveRetrievalTest.java
addons/httprox/ftests/src/main/java/org/commonjava/indy/httprox/RetrievedContentMatchesContentLength_SlowClient_Test.java
addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMHostedRetrieveFileTest.java
addons/pkg-npm/ftests/src/main/java/org/commonjava/indy/pkg/npm/content/NPMRemotePackageContentRetrieveTest.java
addons/promote/common/src/main/java/org/commonjava/indy/promote/validate/PromotionValidationTools.java
addons/promote/common/src/test/java/org/commonjava/indy/promote/data/PromotionManagerTest.java
api/src/main/java/org/commonjava/indy/CustomJsonLayout.java
api/src/main/java/org/commonjava/indy/util/AcceptInfoParser.java
clients/core-java/src/main/java/org/commonjava/indy/client/core/module/IndySchedulerClientModule.java
ftests/common/src/main/java/org/commonjava/indy/ftest/core/AbstractIndyFunctionalTest.java
subsys/cpool/src/main/java/org/commonjava/indy/subsys/cpool/ConnectionPoolConfig.java
subsys/infinispan/src/main/java/org/commonjava/indy/subsys/infinispan/metrics/IspnRegistrySetProvider.java
subsys/metrics/src/main/java/org/commonjava/indy/subsys/metrics/conf/IndyMetricsConfig.java
subsys/trace/src/main/java/org/commonjava/indy/subsys/honeycomb/config/IndyTraceConfiguration.java

Fix part of the following issues: 
- Denail of Service(DoS)
- Weak Cryptography

[ESS] fix the medium security hotspots

---

embedder/pom.xml
pom.xml

This new profile is used to compensate the loss release versions to
staging repo(like nexus)

Fix: Add a new pom profile for release deploy

---

filers/default/src/main/java/org/commonjava/indy/filer/def/DefaultGalleyStorageProvider.java
uis/layover/package-lock.json
uis/layover/package.json

Cherry-pick from master of npm security patches

---

ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/AddAndDeleteGroupTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/AddAndDeleteHostedRepoTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/AddAndDeleteRemoteRepoTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/AddHostedRepoThenModifyAndVerifyTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/AddRemoteRepoThenModifyAndVerifyTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/CreateGroupThenModifyAndVerifyChangesTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/GetRemoteByUrlTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/GroupAdjustmentToMemberDeletionTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/HostedAuthIndexWithReadonly.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/ListStoresByTypeTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/ReadonlyHostedRepoDeleteTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/RemoteRepoInValidUrlTest.java
ftests/core/src/main/java/org/commonjava/indy/ftest/core/store/RemoteRepoValidUrlTest.java

This will save some time for ftests.

Disable Store related ftests because of repo-service not related

---

subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/boot/KafkaStreamBooter.java
subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/conf/KafkaConfig.java

Add config max kafka.records.per.partition

Add env POD_NAME to define consumer group

---

db/service/src/main/java/org/commonjava/indy/db/service/ServiceStoreDataCacheUpdater.java

We found some ConcurrentModificationException error with Weft
ExecutorService decorated by O11yphant tracing, so before the fix of
this bug, we will use JUC ExecutorService instead.

Fix: Use JUC ExecutorService instead of weft one for ServiceStoreCacheUpdator

---

core/src/main/java/org/commonjava/indy/core/change/event/DefaultStoreEventDispatcher.java
db/common/src/main/java/org/commonjava/indy/db/common/AbstractStoreDataManager.java

I find both store-affected-by-async-runner and indy-event-dispatch ConcurrentModificationException will affect the store delete event cleanups like on .sha1, .md5, same with: https://github.com/Commonjava/indy/pull/2186/files

Fix: Use JUC ExecutorService instead of weft one for DefaultStoreEventDispatcher, AbstractStoreDataManager

---

pom.xml
subsys/trace/src/main/java/org/commonjava/indy/subsys/honeycomb/config/IndyTraceConfiguration.java

The o11yphant will have a fix for thread-safety of honeycomb span
implementation, which impact underlying weft libs

Update o11yphant to 1.6-SNAPSHOT

---

pom.xml

Not sure why 1.6 build does not contain new commited PRs, so rebuild the 1.7 and includes it here.

Upgrade o11yphant to 1.7

---

addons/event-publisher/common/pom.xml
addons/event-publisher/common/src/main/java/org/commonjava/indy/event/publisher/FileEventPublisher.java
addons/event-publisher/common/src/main/java/org/commonjava/indy/event/publisher/KafkaEventPublisher.java
addons/event-publisher/pom.xml
addons/pom.xml
pom.xml
subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/conf/KafkaConfig.java

Resubmit the files for target branch changing. https://github.com/Commonjava/indy/pull/2209
There were two PRs which had been reviewed but not sure why they are missing from the codebase, let's bring them back and to see if the CI passed. thanks.
https://github.com/Commonjava/indy/pull/1878
https://github.com/Commonjava/indy/pull/1889

 [Cherry-picks] Produce file event to kafka & config updates

---

subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/IndyKafkaProducer.java

this producer used the Deprecated `LogKafkaConfig`, let's update it to make it consistent with what the kafka streams is using.

Update the kafka producer with the latest config

---

addons/schedule/common/src/test/java/org/commonjava/indy/schedule/ScheduleTest.java
subsys/kafka/pom.xml
subsys/kafka/src/main/conf/conf.d/kafka.conf
subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/boot/KafkaStreamBooter.java
subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/event/DefaultIndyStoreEvent.java
subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/event/TopicType.java
subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/handler/PromoteServiceEventHandler.java
subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/handler/RepoServiceEventHandler.java
subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/handler/ServiceEventHandler.java
subsys/kafka/src/main/resources/default-kafka.conf
subsys/kafka/src/test/java/org/commonjava/indy/subsys/kafka/KafkaConsumerStreamTest.java

Handle promote complete event to clean NFC

---

pom.xml

No bit change. Just a few minor add-on in pathmappedStorage 2.2.

Update pathmappedStorageVersion to 2.2

---

addons/event-publisher/common/src/main/java/org/commonjava/indy/event/publisher/KafkaEventPublisher.java
embedder/pom.xml
pom.xml
subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/IndyKafkaProducer.java
subsys/kafka/src/test/java/org/commonjava/indy/subsys/kafka/KafkaTest.java

The previous producer was mainly for log forwarder, the PR updated the methods to support sending Object message.

Refine the kafka producer 

---

addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/data/NPMSpecialPathProducer.java
addons/schedule/common/src/test/java/org/commonjava/indy/schedule/ScheduleTest.java
pom.xml

Ref the comments of the PR https://github.com/Commonjava/galley/pull/406 .

Fix the issue of deleting checksum files

---

addons/event-publisher/common/src/main/java/org/commonjava/indy/event/publisher/KafkaEventPublisher.java

This PR is derived from https://github.com/Commonjava/indy/pull/2261 to reduce duplicate code.

Simple refactoring: extract duplicate code to one method

---

bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/admin/ContentAdminResource.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/util/ContentAdminController.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/util/FoloFileTypes.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/util/FoloFiler.java
bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/util/TrackingContentController.java
core/src/main/java/org/commonjava/indy/core/model/StoreEffect.java
core/src/main/java/org/commonjava/indy/core/model/TrackedContentEntry.java
core/src/main/java/org/commonjava/indy/core/model/TrackingKey.java
core/src/main/java/org/commonjava/indy/core/model/dto/ContentEntryDTO.java
core/src/main/java/org/commonjava/indy/core/model/dto/ContentTransferDTO.java
core/src/main/java/org/commonjava/indy/core/model/dto/TrackedContentDTO.java

tracking records for the Indy Tracking Service

add `recalculateEntrySet` endpoint to recalculate and `getZipRepository` endpoint

---

addons/promote/model-java/src/main/java/org/commonjava/indy/promote/model/AbstractPromoteRequest.java

Add trackingId to PromoteRequest

---

api/src/main/java/org/commonjava/indy/conf/UIConfiguration.java

Just found that the ui configuration missed the enabled option, so added

Add ui enabled configuration

---

addons/folo/common/src/main/java/org/commonjava/indy/folo/change/FoloTrackingAdjustListener.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/change/FoloTrackingListener.java
addons/folo/common/src/main/java/org/commonjava/indy/folo/conf/FoloConfig.java
addons/folo/jaxrs/src/main/java/org/commonjava/indy/folo/bind/jaxrs/FoloAdminResource.java

add config to disable folo admin and listeners

---

addons/promote/client-java/src/main/java/org/commonjava/indy/promote/client/IndyPromoteClientModule.java

Update promoteByPath with trackingId

---

core/src/main/java/org/commonjava/indy/core/inject/AbstractNotFoundCache.java
core/src/main/java/org/commonjava/indy/core/inject/CassandraNotFoundCache.java
core/src/main/java/org/commonjava/indy/core/inject/ExpiringMemoryNotFoundCache.java
core/src/main/java/org/commonjava/indy/core/inject/IspnNotFoundCache.java

This is for MMENG-3703 | Disable NFC for Hosted Repositories in Indy
[MMENG-3703](https://issues.redhat.com/browse/MMENG-3703)

Disable NFC for hosted repository

---

core/src/main/java/org/commonjava/indy/core/inject/AbstractNotFoundCache.java
core/src/main/java/org/commonjava/indy/core/inject/CassandraNotFoundCache.java
core/src/main/java/org/commonjava/indy/core/inject/ExpiringMemoryNotFoundCache.java
core/src/main/java/org/commonjava/indy/core/inject/IspnNotFoundCache.java

Disable NFC for hosted repo

---

subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/ui/UIServlet.java
subsys/jaxrs/src/test/java/org/commonjava/indy/bind/jaxrs/ui/UIServletTest.java

Prevent UIservlet from Path Traversal attack (#2299)

---

core/src/main/java/org/commonjava/indy/data/DefaultStoreValidator.java
pom.xml
subsys/trace/src/main/java/org/commonjava/indy/subsys/trace/TraceManagerProducer.java

Remove TracerType from o11yphant

---

pom.xml

The new version include the fix for copy/dedup issue (missing physical file).

Update pathmappedStorageVersion to 2.4

---

clients/core-java/src/main/java/org/commonjava/indy/client/core/metric/ClientMetricManager.java
core/src/main/java/org/commonjava/indy/data/DefaultStoreValidator.java
pom.xml
subsys/trace/src/main/java/org/commonjava/indy/subsys/trace/TraceManagerProducer.java

This is a cherry-pick from https://github.com/Commonjava/indy/pull/2323

[cherry-pick]Remove TracerType from o11yphant

---

pom.xml

Update galley to 1.15 and pathmap to 2.5

---

pom.xml

* httpclient to 4.5.13
* bouncycastle to 1.67

[cherry-pick]Bump dependency versions

---

deployments/cache-migrator/test-env/indy-env/conf.d/kafka.conf
subsys/kafka/pom.xml
subsys/kafka/src/main/conf/conf.d/kafka.conf
subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/IndyKafkaProducer.java
subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/boot/KafkaStreamBooter.java
subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/conf/KafkaConfig.java
subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/trace/TracingKafkaClientSupplier.java

And also add support for kafka producer tracing.

Add config to turn on/off kafka tracing

---

subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/boot/KafkaStreamBooter.java
subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/handler/PromoteServiceEventHandler.java

During testing I found that the store event can not be received
correctly through Kafka. After checking, found the reason is the
KafkaStream is not set up correctly. It should be started with a long
running state but not close immediately. So this PR makes it close in
shutdown action but not immediately.

Fix: Kafka store event can not be received correctly

---

subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/keycloak/BasicAuthenticationOAuthTranslator.java
subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/keycloak/IndyIdentityManager.java
subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/keycloak/SecurityResource.java
subsys/jaxrs/src/main/java/org/commonjava/indy/bind/jaxrs/util/JwtTokenUtils.java

Including the build-id into the token and then verifying the requests based on the token.

Support to generate the random access token per build

---

pom.xml

Because these docker stuff is never used anymore.

Remove all docker related stuff

---

bindings/jaxrs/src/main/java/org/commonjava/indy/core/bind/jaxrs/admin/StoreAdminHandler.java
subsys/kafka/src/main/java/org/commonjava/indy/subsys/kafka/trace/TracingKafkaClientSupplier.java

These APIs are migrated to Indy Repository Service, so we should not  let them work here. Here will forbid them if repo service is enabled.

Forbid all Store Admin APIs

---

addons/content-browse/common/pom.xml
addons/content-browse/pom.xml
addons/koji/common/pom.xml
pom.xml
rest/api/src/test/java/org/commonjava/indy/rest/apigen/SwaggerExportTest.java

* Use indy-content-browse-model-java from indy-model library
* Use indy-koji-model-java from indy-model library
* Disable SwaggerExportTest as it is not used in 3.3.0

Deps adjustment

---

pom.xml

Update galley to 1.16

---

addons/content-browse/pom.xml
addons/content-browse/ui/.babelrc
addons/content-browse/ui/package-lock.json
addons/content-browse/ui/package.json
addons/content-browse/ui/pom.xml
addons/content-browse/ui/webpack.dev.config.js
deployments/launcher/pom.xml
pom.xml

The indy content browse UI is still in use in some cases, so we should bring it back here.

Bring the content-browse UI back

---

addons/event-publisher/common/src/main/java/org/commonjava/indy/event/publisher/KafkaEventPublisher.java

This fix is for [MMENG-3880](https://issues.redhat.com/browse/MMENG-3880). The event's sourcePath is used for folo originUrl.
In case the generic proxy downloading from remote site, we get incorrect folo record, e.g, "originUrl" : "https://code.jquery.com/L2pxdWVyeS0zLjcuMS5taW4uanM_cGFyYW09YQ". This is because proxy encode the path before sending to main Indy.
This pr decode the base64 path before Indy sending event to folo if ATTR_PATH_ENCODE is set.

Decode base64 for remote fileEvent.setSourcePath

---

api/src/main/java/org/commonjava/indy/content/IndyPathGenerator.java
pom.xml

(Hold until 3.3.3 is released)

Update IndyPathGenerator to support PathStyle.base64url

---

addons/pkg-npm/common/src/main/java/org/commonjava/indy/pkg/npm/content/PackageMetadataGenerator.java
addons/pkg-npm/model-java/src/main/java/org/commonjava/indy/pkg/npm/model/Dist.java
addons/pkg-npm/model-java/src/main/java/org/commonjava/indy/pkg/npm/model/VersionMetadata.java
addons/pkg-npm/model-java/src/main/java/org/commonjava/indy/pkg/npm/model/io/VersionMetadataDeserializer.java

Fix https://issues.redhat.com/browse/MMENG-3929

Add missing fields for npm version object

---

pom.xml
subsys/infinispan/pom.xml
subsys/infinispan/src/main/resources/infinispan-jdbc.xml.deprecated

We are not using postgresql in indy anymore. Due to some CVE
reporting, let's remove it.

Remove dep of postgresql

---

pom.xml

Update indy-client to include the fix: https://github.com/Commonjava/indy-client/pull/28
Ref: MMENG-4156

Update indy-clients to 3.3.3-SNAPSHOT

---

.github/workflows/maven-push.yml
.github/workflows/maven-verify.yml

This is a following fix for 1462f846f. And also removed java 8 installation as it is not used anymore.

Separate github action to verify and push for pr open and merged phases

---

pom.xml

Upgrade to 1.1.4 to include the fix for the issue in Artifact Path parser.

Upgrade atlas to 1.1.4

---

.github/workflows/maven-push.yml
pom.xml

Update pom.xml with correct central url and add distributionManagement
Remove unnecessary fields in actions

using correct maven central as value
